### ISSUE TITLE
Useless error message

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#1020]
_From @imperugo on July 27, 2016 14:29_

Hi, 
today I had a problem deploying my aspnet core application on Azure.
The error message was saying:

```
Application: Gaia.Bmw.Admin.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle, Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.SockAddr ByRef, Int32)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(Microsoft.AspNetCore.Server.Kestrel.ServerAddress)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener+&lt;&gt;c.&lt;StartAsync&gt;b__6_0(System.Object)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary+&lt;StartAsync&gt;d__11.MoveNext()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(Microsoft.AspNetCore.Server.Kestrel.ServerAddress)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1&lt;Context&gt;)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost, System.Threading.CancellationToken, System.String)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost)
   at Gaia.Bmw.Admin.Program.Main(System.String[])
```

After few hours I noticed that the order on program.cs file was wrong.

`.UseIISIntegration() `must be after `.UseUrls()`

I don't know if it is my fault or not (for me the order wasn't so important, otherwise I should get a compilation error) but the error message wasn't helpful.

_Copied from original issue: aspnet/Hosting#826_

**Comment by halter73** [comment]
@imperugo @Tratcher Do you know where the error message was written to?

It's odd that the `Exception Info:` for the `UvException` didn't include the `Message`. Kestrel always sets a message for that exception type.

**Comment by imperugo** [comment]
@halter73 is what I got from `eventlog.xml` from azure web app.

**Comment by muratg** [comment]
We'll add logging: https://github.com/aspnet/KestrelHttpServer/issues/1052
