### ISSUE TITLE
NRE in AppVeyor while running tests

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1030]
https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.3307

    System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.unsafe_async_send(IntPtr handle) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Networking\Libuv.cs:line 173
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvAsyncHandle.ReleaseHandle() in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Networking\UvAsyncHandle.cs:line 62
       at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
       at System.Runtime.InteropServices.SafeHandle.Finalize()

**Comment by halter73** [comment]
I think the only thing that could be null in that line of code is the `_uv_unsafe_async_send` Func. Surprising.

**Comment by cesarbs** [comment]
Crazy. Will keep open for a while and if it turns out to have been a one-off thing I'll close.

**Comment by halter73** [comment]
Thinking it might have something to do with `_uv_unsafe_async_send` being the only libuv function declared using `DllImportAttribute.EntryPoint`. It doesn't get called much, since the `UvAsyncHandle` doesn't usually get finalized.

**Comment by halter73** [comment]
I just realized that it has to be a test using `MockLibuv`. That explains the func being null.

**Comment by cesarbs** [comment]
Reproed with a StackTrace: https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.3371

**Comment by benaadams** [comment]
"System.Exception: Why is this getting called?" :smile:

**Comment by halter73** [comment]
Could be fixed by https://github.com/aspnet/KestrelHttpServer/pull/1098. If we see this again, we can reopen with a link to the new failure.
