### ISSUE TITLE
Block being garbage collected instead of returned to pool

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1037]
Block leased in SocketOutput
```
fail: *** Block being garbage collected instead of returned to pool: .ctor, /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/
SocketOutput.cs, 79 ***
fail:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
fail:    at System.Environment.get_StackTrace()
fail:    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
fail:    at System.Diagnostics.Debug.Assert(Boolean condition, String message)
fail:    at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolBlock.Finalize() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/MemoryPoolBlock.cs:line 82
fail: Unhandled Exception: System.Diagnostics.Debug+DebugAssertException: 
fail: *** Block being garbage collected instead of returned to pool: .ctor, /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/
SocketOutput.cs, 79 ***
fail:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
fail:    at System.Environment.get_StackTrace()
fail:    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
fail:    at System.Diagnostics.Debug.Assert(Boolean condition, String message)
fail:    at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolBlock.Finalize() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/MemoryPoolBlock.cs:line 82
fail:    at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
fail:    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
fail:    at System.Diagnostics.Debug.Assert(Boolean condition, String message)
fail:    at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolBlock.Finalize()
```

**Comment by benaadams** [comment]
Have a previous exception; which this later exception is masking
