### ISSUE TITLE
Tests receiving empty responses on OSX

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1070]
System.Net.Http.HttpRequestException : An error occurred while sending the request.
    ---- System.Net.Http.CurlException : Server returned nothing (no headers, no data)
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__5.MoveNext() in /Users/asplab/Documents/buildAgent/work/d6337ac2abf63a4b/.repositories/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 76
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_IPv6_Success>d__2.MoveNext() in /Users/asplab/Documents/buildAgent/work/d6337ac2abf63a4b/.repositories/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 41
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ----- Inner Stack Trace -----
       at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
       at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)

[http://aspnetci/viewLog.html?buildId=130980&tab=buildResultsDiv&buildTypeId=Releases_Osx](http://aspnetci/viewLog.html?buildId=130980&tab=buildResultsDiv&buildTypeId=Releases_Osx)

[http://aspnetci/viewLog.html?buildId=130665&tab=buildResultsDiv&buildTypeId=Releases_Osx](http://aspnetci/viewLog.html?buildId=130665&tab=buildResultsDiv&buildTypeId=Releases_Osx)

**Comment by cesarbs** [comment]
Closing since it's mitigated by running tests sequentially (#1073, 7d1a03f51d64f09371f0ae4dbfb6bc32089f1e37).
