### ISSUE TITLE
Test failure: "Block being leased from disposed pool!"

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1078]
Got this on OS X:

    Block being leased from disposed pool!
       at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
       at System.Environment.get_StackTrace()
       at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
       at System.Diagnostics.Debug.Assert(Boolean condition, String message)
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPool.Lease(String memberName, String sourceFilePath, Int32 sourceLineNumber) in /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/MemoryPool.cs:line 74
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.SocketInput.IncomingStart() in /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/SocketInput.cs:line 64
       at Microsoft.AspNetCore.Server.Kestrel.Filter.Internal.FilteredStreamAdapter.<ReadInputAsync>d__9.MoveNext() in /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Filter/Internal/FilteredStreamAdapter.cs:line 45
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
       at Microsoft.AspNetCore.Server.Kestrel.Filter.Internal.FilteredStreamAdapter.ReadInputAsync()
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Connection.ApplyConnectionFilter() in /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Connection.cs:line 168
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Connection.<>c.<Start>b__14_0(Task task, Object state) in /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Connection.cs:line 112
       at System.Threading.Tasks.Task.Execute()
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
       at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
       at System.Threading.ThreadPoolWorkQueue.Dispatch()    Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.EmptyRequestLoggedAsInformation [FAIL]
          System.AggregateException : One or more errors occurred. (Error -16 EBUSY resource busy or locked)
          ---- Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException : Error -16 EBUSY resource busy or locked
          Stack Trace:
               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
               at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
               at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
            /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/KestrelEngine.cs(46,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
            /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/KestrelServer.cs(197,0): at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose()
               at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
               at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
            /Users/Cesar/src/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/HttpsTests.cs(41,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.<EmptyRequestLoggedAsInformation>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            ----- Inner Stack Trace -----
            /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/Libuv.cs(79,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
            /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/Libuv.cs(70,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowIfErrored(Int32 statusCode)
            /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/Libuv.cs(108,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_close(UvLoopHandle handle)
            /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/UvLoopHandle.cs(44,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.ReleaseHandle()
               at System.Runtime.InteropServices.SafeHandle.InternalDispose()
            /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs(303,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            /Users/Cesar/src/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs(147,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__43.MoveNext()

**Comment by benaadams** [comment]
Is a knock on from the first exception
```
System.AggregateException : One or more errors occurred. (Error -16 EBUSY resource busy or locked)
      ---- Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException : Error -16 EBUSY resource busy or locked
     
```

**Comment by muratg** [comment]
Fixed
