### ISSUE TITLE
AggregateException after upgrading to 1.0.1: An attempt was made to load a program with an incorrect format

### ISSUE THREAD

**Issue by mafshin** [aspnet/KestrelHttpServer#1118]
I just updated my ASP.NET Core project to `1.0.1` via Nuget and now I'm unable to run the app. 

**Exception**

```
 Exception thrown: 'System.AggregateException' in Microsoft.AspNetCore.Server.Kestrel.dll

{"An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"}
```

**StackTrace**

```
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
```

**project.json**

``` JSON
{
  "dependencies": {
    "Autofac": "4.0.0-rc3-286",
    "Autofac.Extensions.DependencyInjection": "4.0.0-rc3-280",
    "BrockAllen.MembershipReboot": "8.4.0",
    "BrockAllen.MembershipReboot.Ef": "8.0.0",
    "log4net": "2.0.5",
    "Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Hosting": "1.0.0",
    "Microsoft.AspNetCore.Identity": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.1",
    "Microsoft.AspNetCore.Owin": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Owin.Host.SystemWeb": "3.0.1",
    "Microsoft.Owin.Security": "3.0.1",
    "Microsoft.Owin.Security.Jwt": "3.0.1",
    "Microsoft.IdentityModel.Tokens": "5.0.0",
    "System.IdentityModel.Tokens.Jwt": "5.0.0",
    "StackifyMiddleware": "1.4.1",
    "EntityFramework.BulkInsert-ef6": "6.0.2.8",
    "AutoMapper": "5.0.2",
    "IdentityServer4": "1.0.0-beta4-update2",
    "IdentityServer4.AccessTokenValidation": "1.0.1-beta1",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.0.1",
    "Microsoft.AspNetCore.Mvc.WebApiCompatShim": "1.0.1",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "tools": {
  },

  "frameworks": {
    "dnx46": {
      "frameworkAssemblies": {
        "System.IdentityModel": "4.0.0.0",
        "System.Runtime.Caching": "4.0.0.0"
      }
    }
  },

  "runtimes": {
    "win7-x86": {},
    "win7-x64": {}
  },

  "buildOptions": {
    "platform": "anycpu",
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": [ "cert.pfx", "log4net.config" ]
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config",
      "log4net.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "userSecretsId": "aspnet-Api-20160702072021"
}
```

**Environment**

Visual Studio 2015 Update 3 + KB3165756
ASP.NET Core 1.0.1

**Comment by mafshin** [comment]
It seems #3103 is also related to this one.

Setting platform to `x86` works but neither `anycpu` nor `x64` works and cause exceptions

```
 "buildOptions": {  "platform": "x86" }.
```

**Comment by khellang** [comment]
`Microsoft.Owin.Host.SystemWeb` for ASP.NET Core? How's that working out for you? :stuck_out_tongue:

**Comment by mafshin** [comment]
@khellang I don't use them. They were probably mistakenly added while trying to add references to some classes. The strange point is that they even appeared in the `bin` directory. :-)

**Comment by benaadams** [comment]
Some observations:

Change `runtimeOptions`
```
  "runtimeOptions": {
    "gcServer": true
  },
```
should be
```
  "runtimeOptions": { 
    "configProperties": { 
      "System.GC.Server": true 
    } 
  },
```
Change `frameworks`
```
  "frameworks": {
    "dnx46": {
      "frameworkAssemblies": {
        "System.IdentityModel": "4.0.0.0",
        "System.Runtime.Caching": "4.0.0.0"
      }
    }
  },
```
should be
```
  "frameworks": {
    "net461": {
      "frameworkAssemblies": {
        "System.IdentityModel": "build",
        "System.Runtime.Caching": "build"
      }
    }
  },
```
Delete
```
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },
```


Delete this ( `AspNet` not `AspNetCore` )
```
"Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
```

Delete this 
```
"Microsoft.Owin.Host.SystemWeb": "3.0.1",
```

Delete your bin directories. Try again.

**Comment by cwe1ss** [comment]
@benaadams just curious - I'm using `"System.IdentityModel": ""` (without any version or `build`) for assemblies in my `frameworkAssemblies` section - do you know if there are any important differences?!

**Comment by halter73** [comment]
@mafshin Did @benaadams suggestions fix your issue?

**Comment by mafshin** [comment]
@halter73 I did some of suggestions and my new `project.json` is as follows:

```
{
  "dependencies": {
    "Autofac": "4.0.0-rc3-286",
    "Autofac.Extensions.DependencyInjection": "4.0.0-rc3-280",
    "BrockAllen.MembershipReboot": "8.4.0",
    "BrockAllen.MembershipReboot.Ef": "8.0.0",
    "log4net": "2.0.5",
    "Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Hosting": "1.0.0",
    "Microsoft.AspNetCore.Identity": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.1",
    "Microsoft.AspNetCore.Owin": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    //"Microsoft.Owin.Host.SystemWeb": "3.0.1",
    //"Microsoft.Owin.Security": "3.0.1",
    //"Microsoft.Owin.Security.Jwt": "3.0.1",
    "Microsoft.IdentityModel.Tokens": "5.0.0",
    //"System.IdentityModel.Tokens.Jwt": "5.0.0",
    "StackifyMiddleware": "1.4.1",
    "EntityFramework.BulkInsert-ef6": "6.0.2.8",
    "AutoMapper": "5.0.2",
    "IdentityServer4": "1.0.0-beta4-update2",
    "IdentityServer4.AccessTokenValidation": "1.0.1-beta1",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.0.1",
    "Microsoft.AspNetCore.Mvc.WebApiCompatShim": "1.0.1",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "tools": {
  },

  "frameworks": {
    "dnx46": {
      "frameworkAssemblies": {
        "System.IdentityModel": "4.0.0.0",
        "System.Runtime.Caching": "4.0.0.0"
      }
    }
  },

  "runtimes": {
    //"win7-x86": {},
    //"win7-x64": {}
  },

  "buildOptions": {
    "platform": "x86",
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": [ "cert.pfx", "log4net.config" ]
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config",
      "log4net.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "userSecretsId": "aspnet-App-20160702072021"
}
```

Although, now I can only get `x86` binary.

**Comment by benaadams** [comment]
You have to remove
```
"Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
```
Its not AspNetCore

**Comment by mafshin** [comment]
@benaadams , Thanks I did it.

Upon changing `frameworkAssemblies` I get this exception:

`'build' is not a valid version string.`

**Comment by khellang** [comment]
Yeah, that should be `{ "type": "build" }` :smile:

**Comment by mafshin** [comment]
Everything is fine and OK now, except that I'm locked to `x86` which is tracked by other issues (https://github.com/dotnet/cli/issues/3091 & https://github.com/dotnet/cli/issues/2668)

**Comment by benaadams** [comment]
@mafshin check your path make sure 
`C:\Program Files\dotnet` 
occurs before 
`C:\Program Files (x86)\dotnet`

**Comment by mafshin** [comment]
@benaadams yes that was the case, the `x86` version was before `x64` version.

Now, after I swapped them and restarted the machine, the output is locked to `x64`. It seems the first version (`x86` or `x64') in the PATH would only work.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
