### ISSUE TITLE
ODE on shutdown

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1200]
The ObjectDisposedException is happening on `Post(t => t.AllowStop());`, but the `UvAsyncHandle` shouldn't be disposed or finalized until AllowStop is called. Weird.

    Microsoft.AspNetCore.Server.KestrelTests.RequestTargetProcessingTests.NonPathRequestTargetSetInRawTarget(requestTarget: "../") [FAIL]
      System.AggregateException : One or more errors occurred. (Safe handle has been closed)
      ---- System.ObjectDisposedException : Safe handle has been closed
      Stack Trace:
           at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
           at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
           at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
        C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\KestrelEngine.cs(54,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
        C:\projects\kestrelhttpserver\test\shared\TestServer.cs(67,0): at Microsoft.AspNetCore.Testing.TestServer.Dispose()
        C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\RequestTargetProcessingTests.cs(129,0): at Microsoft.AspNetCore.Server.KestrelTests.RequestTargetProcessingTests.<NonPathRequestTargetSetInRawTarget>d__2.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        ----- Inner Stack Trace -----
           at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
           at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
           at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
        C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Networking\Libuv.cs(179,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle)
        C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Networking\UvAsyncHandle.cs(37,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvAsyncHandle.Send()
        C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Infrastructure\KestrelThread.cs(222,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.Post(Action`1 callback, Object state)
        C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Infrastructure\KestrelThread.cs(227,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.Post(Action`1 callback)
        C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Infrastructure\KestrelThread.cs(122,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__45.MoveNext()
    
https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.3743

**Comment by muratg** [comment]
Placing this in Backlog for now.  If we see this again, we'll investigate further.

**Comment by davidfowl** [comment]
We catch this now
