### ISSUE TITLE
Error -4091 EADDRINUSE with Kestrel 1.1.0

### ISSUE THREAD

**Issue by MichaCo** [aspnet/KestrelHttpServer#1235]
I'm having a strange issue after updating all packages to release 1.1.0 (from 1.0.0)

I have a small test project bootstrapping a service. I find an open port by testing if it is in use or not right before creating the host like:

```csharp
    var endpoint = $"http://{hostIP}:{port}";
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseUrls(endpoint)
        .UseStartup<Startup>()
        .Build();

    host.Run();
```

With version 1.1.0 I'm getting the following exception, consistently and knowing that the port is for sure NOT in use

```
Unhandled Exception: System.IO.IOException: Failed to bind to address http://192.168.178.23:5000: address already in use. 
---> System.AggregateException: One or more errors occurred. (Error -4091 EADDRINUSE address already in use) 
---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4091 EADDRINUSE address already in use
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_getsockname(UvTcpHandle handle, SockAddr& addr, Int32& namelen)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
```

Running the exact same code with version 1.0.0 of all the Microsoft.* packages and using Microsoft.NETCore.App 1.0.0 instead of 1.1.0, it just works fine.

Tests are all done on Windows 10 locally.

More interestingly, if I use the hostname instead of an IP, it works again on 1.1.0!

Is this somewhat intended that binding to an IP doesn't work but hostname or localhost or wildcards work?

Thanks,
M

**Comment by MichaCo** [comment]
Seems it was my mistake, never mind ~~

One day digging around and then figured I didn't close the TcpListener to check for open ports and that eventually might have kept the port open I guess
Sorry
