### ISSUE TITLE
ListenerPrimaryTests.NonListenerPipeConnectionsAreLoggedAndIgnored test failure on OS X on Travis

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1270]
https://travis-ci.org/aspnet/KestrelHttpServer/jobs/185896490

**Comment by halter73** [comment]
The link now points to a successful build. Any other details about the failure?

**Comment by cesarbs** [comment]
Saw it again on #1840, but I don't think it's related.

```
[xUnit.net 00:00:02.5756350]     NonListenerPipeConnectionsAreLoggedAndIgnored [FAIL]
[xUnit.net 00:00:02.5770670]       System.IO.IOException : Unable to transfer data on the transport connection: Connection reset by peer.
[xUnit.net 00:00:02.5771710]       ---- System.Net.Sockets.SocketException : Connection reset by peer
[xUnit.net 00:00:02.5783520]       Stack Trace:
[xUnit.net 00:00:02.5802200]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.5803200]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.5804090]            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
[xUnit.net 00:00:02.5804690]            at System.IO.StreamReader.<ReadBufferAsync>d__65.MoveNext()
[xUnit.net 00:00:02.5805180]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.5805840]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.5806490]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.5807130]            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
[xUnit.net 00:00:02.5807710]            at System.IO.StreamReader.<ReadToEndAsyncInternal>d__61.MoveNext()
[xUnit.net 00:00:02.5808310]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.5808880]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.5809490]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.5810110]            at Microsoft.AspNetCore.Testing.HttpClientSlim.<ReadResponse>d__4.MoveNext()
[xUnit.net 00:00:02.5810650]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.5811240]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.5811820]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.5812410]            at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__1.MoveNext()
[xUnit.net 00:00:02.5812970]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.5813550]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.5814110]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.5814810]            at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.ListenerPrimaryTests.<AssertResponseEventually>d__3.MoveNext()
[xUnit.net 00:00:02.5815300]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.5815860]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.5816420]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.5817100]            at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.ListenerPrimaryTests.<NonListenerPipeConnectionsAreLoggedAndIgnored>d__1.MoveNext()
[xUnit.net 00:00:02.5817780]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.5818490]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.5819180]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.5819750]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.5820360]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.5820930]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.5821580]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:02.5822110]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:02.5822690]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:02.5823160]         ----- Inner Stack Trace -----
[xUnit.net 00:00:02.5823640]         
Failed   NonListenerPipeConnectionsAreLoggedAndIgnored
Error Message:
 System.IO.IOException : Unable to transfer data on the transport connection: Connection reset by peer.
---- System.Net.Sockets.SocketException : Connection reset by peer
Stack Trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.IO.StreamReader.<ReadBufferAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.IO.StreamReader.<ReadToEndAsyncInternal>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<ReadResponse>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.ListenerPrimaryTests.<AssertResponseEventually>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.ListenerPrimaryTests.<NonListenerPipeConnectionsAreLoggedAndIgnored>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
```

**Comment by muratg** [comment]
@cesarbs if we haven't seen it since then, please close for now.

**Comment by muratg** [comment]
@cesarbs It looks like this is reproducing still. Please take a look.

**Comment by cesarbs** [comment]
Can someone point me to a recent failure? I haven't been able to repro it yet.
