### ISSUE TITLE
Test failure: Microsoft.AspNetCore.Server.KestrelTests.ChunkedRequestTests.ExtensionsAreIgnored

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1340]
In AppVeyor: https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.4089#L3632

```
Failed   Microsoft.AspNetCore.Server.KestrelTests.ChunkedRequestTests.ExtensionsAreIgnored(listenOptions: http://127.0.0.1:0)
Error Message:
 System.IO.IOException : Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
---- System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine
Stack Trace:
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.<FlushAsyncInternal>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Testing.TestConnection.<Send>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.KestrelTests.ChunkedRequestTests.<ExtensionsAreIgnored>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
```

**Comment by cesarbs** [comment]
More failures (other tests): https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.4095

So far unable to reproduce any of them.

**Comment by cesarbs** [comment]
Seems to be an issue with our `ConditionalTheory` attribute. If I change it to `Theory`, it doesn't repro. Moving to the Testing repo.

**Comment by cesarbs** [comment]
We haven't seen these failures in more than a month, and I can't repro any of them. Closing.
