### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error  -4082 EBUSY resource busy or locked

### ISSUE THREAD

**Issue by shravan2x** [aspnet/KestrelHttpServer#1341]
I run a Kestrel server for a website. After about a month of working fine, I got this error with the site going offline:

    info: Microsoft.AspNetCore.Server.Kestrel[14]
          Connection id "0HL1EBAIIHRF4" communication error.
    Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
    info: Microsoft.AspNetCore.Server.Kestrel[14]
          Connection id "0HL1EBAIIHRF7" communication error.
    Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
    info: Microsoft.AspNetCore.Server.Kestrel[14]
          Connection id "0HL1EBAIIHRF5" communication error.
    Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
    info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
          Request finished in 287160.2735ms 404
    Application is shutting down...
    
    Unhandled Exception: System.AggregateException: One or more errors occurred. (Error -4082 EBUSY resource busy or locked) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error
     -4082 EBUSY resource busy or locked
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_close(UvLoopHandle handle)
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.ReleaseHandle()
       at System.Runtime.InteropServices.SafeHandle.InternalDispose()
       at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__45.MoveNext()
       --- End of inner exception stack trace ---
       at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
       at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
       at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose()
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
       at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
       at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
       at <project>.Program.Main(String[] args) in <path>:line 18

Restarting the program solved the issue, so I'm confident the problem lies with Kestrel and/or Asp.NET Core.

**Comment by halter73** [comment]
Thanks for the report @shravan2x. To me it looks like you're running into the same issue described in #1231.

Are you hosting your website using Azure App Services by chance? I ask because I'm curious as to whether the shutdown is unexpected or the application is already being shut down when you see this error. App Services will shutdown/suspend/recycle apps for many reasons.

**Comment by shravan2x** [comment]
The server was hosted on AWS at the time of the crash. It's possible this happened at shutdown, but I'll note that _I was only shutting it down as it was already not working_.

I had received a few

    MySql.Data.MySqlClient.MySqlException: Fatal error encountered during command execution. ---> System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine

that day, but it had been happening for quite some time before the server stopped working.

**Comment by halter73** [comment]
@shravan2x The shutdown error you ran into seems to only happen when Kestrel starts applying TCP back pressure to clients as a result of the server application processing data more slowly than the clients attempt to send it.

Again, you would only see the error if something attempted to shutdown the server while the back pressure was being applied, but this shutdown error is consistent with the server application already behaving badly.

By default Kestrel will maintain up to a 1MB request buffer per client before applying back pressure. This kind of thing could happen if the application is reading request body data slowly because it's writing the contents of large uploads to a slow file system or database.

**Comment by shravan2x** [comment]
That's good to know, but I'm not sure why there would be much back pressure in my case. The application was one I wrote to test the ASP.NET Core waters and was barely being used at all. The server was also otherwise pretty load-free.

However, it maintained long-running websocket connections. Could this be the cause in some way?

**Comment by muratg** [comment]
@shravan2x Please re-open or file another one if you still see issues after upgrading Kestrel.

**Comment by shravan2x** [comment]
Will do, I have not had this issue since.
