### ISSUE TITLE
AppVeyor test failures

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1380]
Might be instability introduced by pipelines ¯\\_(ツ)_/¯

https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.4162

```
Failed   Microsoft.AspNetCore.Server.KestrelTests.EngineTests.Http10ContentLength(listenOptions: http://127.0.0.1:0)
  Error Message:
   TestConnection.Receive timed out.
  Expected: True
  Actual:   False
  Stack Trace:
     at Microsoft.AspNetCore.Testing.TestConnection.<Receive>d__8.MoveNext() in C:\projects\kestrelhttpserver\test\shared\TestConnection.cs:line 80
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
     at Microsoft.AspNetCore.Testing.TestConnection.<ReceiveEnd>d__9.MoveNext() in C:\projects\kestrelhttpserver\test\shared\TestConnection.cs:line 95
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
     at Microsoft.AspNetCore.Server.KestrelTests.EngineTests.<Http10ContentLength>d__8.MoveNext() in C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\EngineTests.cs:line 238
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

```
Failed   Microsoft.AspNetCore.Server.KestrelTests.RequestTargetProcessingTests.NonPathRequestTargetSetInRawTarget(requestTarget: "../..")
  Error Message:
   Assert.Equal() Failure
                     ? (pos 9)
  Expected: HTTP/1.1 200 OK\r\nDate: Tue, 21 Feb 2017 18:14:04 G···
  Actual:   HTTP/1.1 408 Request Timeout\r\nConnection: close\r\nD···
                     ? (pos 9)
  Stack Trace:
     at Microsoft.AspNetCore.Testing.TestConnection.<Receive>d__8.MoveNext() in C:\projects\kestrelhttpserver\test\shared\TestConnection.cs:line 90
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
     at Microsoft.AspNetCore.Testing.TestConnection.<ReceiveEnd>d__9.MoveNext() in C:\projects\kestrelhttpserver\test\shared\TestConnection.cs:line 95
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
     at Microsoft.AspNetCore.Server.KestrelTests.RequestTargetProcessingTests.<NonPathRequestTargetSetInRawTarget>d__2.MoveNext() in C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\RequestTargetProcessingTests.cs:line 129
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Passed
```

**Comment by muratg** [comment]
We haven't seen these failures in a while. Closing.
