### ISSUE TITLE
Failure on the CI

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1435]
Saw this on the CI:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/207261457/log.txt

```
Failed   Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted
Error Message:
 System.Diagnostics.Debug+DebugAssertException : Block being leased from disposed pool!

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPool.Lease(String memberName, String sourceFilePath, Int32 sourceLineNumber) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/MemoryPool.cs:line 74
   at Microsoft.AspNetCore.Server.Kestrel.Adapter.Internal.StreamSocketOutput.ProducingStart() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Adapter/Internal/StreamSocketOutput.cs:line 72
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.CreateResponseHeader(Byte[] statusBytes, Boolean appCompleted) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Frame.cs:line 894
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.ProduceStart(Boolean appCompleted) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Frame.cs:line 789
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.<InitializeResponseAwaited>d__187.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Frame.cs:line 775
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.InitializeResponseAwaited(Int32 firstWriteByteCount)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.<WriteAsyncAwaited>d__177.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Frame.cs:line 620
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.WriteAsyncAwaited(ArraySegment`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.WriteAsync(ArraySegment`1 data, CancellationToken cancellationToken) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Frame.cs:line 590
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/FrameResponseStream.cs:line 133
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.<>c__DisplayClass3_0.<<DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted>b__3>d.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/HttpsTests.cs:line 166
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.<>c__DisplayClass3_0.<DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted>b__3(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/FrameOfT.cs:line 138
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
   at System.IO.Pipelines.Pipe.FlushAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Adapter.Internal.AdaptedPipeline.<ReadInputAsync>d__10.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Adapter/Internal/AdaptedPipeline.cs:line 60
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security.SslStreamInternal.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.StartFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStreamInternal.ReadHeaderCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Threading.Tasks.TaskToApm.<>c__DisplayClass3_0.<InvokeCallbackWhenTaskCompletes>b__0()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.AspNetCore.Server.Kestrel.Adapter.Internal.RawStream.<ReadAsync>d__22.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Adapter/Internal/RawStream.cs:line 136
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.RunWithDefaultContext()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.LoggingThreadPool.<RunAction>b__5_0(Object o) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/LoggingThreadPool.cs:line 39
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Stack Trace:
   at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPool.Lease(String memberName, String sourceFilePath, Int32 sourceLineNumber) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/MemoryPool.cs:line 74
   at Microsoft.AspNetCore.Server.Kestrel.Adapter.Internal.StreamSocketOutput.ProducingStart() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Adapter/Internal/StreamSocketOutput.cs:line 72
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.CreateResponseHeader(Byte[] statusBytes, Boolean appCompleted) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Frame.cs:line 894
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.ProduceStart(Boolean appCompleted) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Frame.cs:line 789
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.<InitializeResponseAwaited>d__187.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Frame.cs:line 775
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.<WriteAsyncAwaited>d__177.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Frame.cs:line 620
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.<>c__DisplayClass3_0.<<DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted>b__3>d.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/HttpsTests.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.<DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted>d__3.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/HttpsTests.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

/cc @pakrym @halter73 @cesarbs

**Comment by benaadams** [comment]
Might be making a fix for this

**Comment by benaadams** [comment]
K, probably not this https://github.com/dotnet/corefxlab/pull/1266

**Comment by muratg** [comment]
Done per @davidfowl
