### ISSUE TITLE
Can't run Writing Perf tests

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1476]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame..ctor(ConnectionContext context) in D:\Work\GitHub\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Http\Frame.cs:line 81
   at Microsoft.AspNetCore.Server.Kestrel.Performance.Writing.MakeFrame() in D:\Work\GitHub\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.Performance\Writing.cs:line 111
   at Microsoft.AspNetCore.Server.Kestrel.Performance.Writing..ctor() in D:\Work\GitHub\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.Performance\Writing.cs:line 27
   at BenchmarkDotNet.Autogenerated.Runnable..ctor() in D:\Work\GitHub\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.Performance\bin\Debug\netcoreapp1.1\BDN.Generated\BDN.Generated.notcs:line 113
   at BenchmarkDotNet.Autogenerated.Runnable.Run(Boolean isDiagnoserAttached) in D:\Work\GitHub\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.Performance\bin\Debug\netcoreapp1.1\BDN.Generated\BDN.Generated.notcs:line 58
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args) in D:\Work\GitHub\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.Performance\bin\Debug\netcoreapp1.1\BDN.Generated\BDN.Generated.notcs:line 44
```
Not sure why setting a property should throw null ref; even if its being set to null?

**Comment by davidfowl** [comment]
It's because there's no parser being set. I ran into this last night. At the same time, this isn't testing anything.
