### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.ConnectionResetBetweenRequestsIsLoggedAsDebug fails randomly

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1481]
```
Failed   Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.ConnectionResetBetweenRequestsIsLoggedAsDebug
Error Message:
 Assert.Equal() Failure
Expected: Debug
Actual:   Information
Stack Trace:
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<ConnectionResetBetweenRequestsIsLoggedAsDebug>d__8.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/RequestTests.cs:line 320
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Skipped  Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.RemoteIPv6Address
[xUnit.net 00:01:04.8174406]   Finished:    Microsoft.AspNetCore.Server.Kestrel.FunctionalTests
```

**Comment by davidfowl** [comment]
Happened again

**Comment by muratg** [comment]
@cesarbs Please link to the dup and close this one :)

**Comment by cesarbs** [comment]
Tracking in https://github.com/aspnet/KestrelHttpServer/issues/1517
