### ISSUE TITLE
NonListenerPipeConnectionsAreLoggedAndIgnored fails randomly

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1486]
Substring issue in `HttpClientSlim.GetStatus`

```
[xUnit.net 00:00:29.9233847]     Microsoft.AspNetCore.Server.KestrelTests.ListenerPrimaryTests.NonListenerPipeConnectionsAreLoggedAndIgnored [FAIL]
[xUnit.net 00:00:29.9249778]       System.ArgumentOutOfRangeException : Length cannot be less than zero.
[xUnit.net 00:00:29.9250620]       Parameter name: length
[xUnit.net 00:00:29.9272464]       Stack Trace:
[xUnit.net 00:00:29.9362760]            at System.String.Substring(Int32 startIndex, Int32 length)
[xUnit.net 00:00:29.9365414]         /Users/travis/build/aspnet/KestrelHttpServer/test/shared/HttpClientSlim.cs(80,0): at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStatus(String response)
[xUnit.net 00:00:29.9366463]         /Users/travis/build/aspnet/KestrelHttpServer/test/shared/HttpClientSlim.cs(64,0): at Microsoft.AspNetCore.Testing.HttpClientSlim.<ReadResponse>d__4.MoveNext()
[xUnit.net 00:00:29.9369606]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:29.9371221]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:29.9372878]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:29.9374454]         /Users/travis/build/aspnet/KestrelHttpServer/test/shared/HttpClientSlim.cs(33,0): at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__1.MoveNext()
[xUnit.net 00:00:29.9377769]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:29.9379250]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:29.9384108]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:29.9385747]         /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.KestrelTests/ListenerPrimaryTests.cs(310,0): at Microsoft.AspNetCore.Server.KestrelTests.ListenerPrimaryTests.<AssertResponseEventually>d__3.MoveNext()
[xUnit.net 00:00:29.9390012]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:29.9391564]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:29.9393128]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:29.9394813]         /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.KestrelTests/ListenerPrimaryTests.cs(155,0): at Microsoft.AspNetCore.Server.KestrelTests.ListenerPrimaryTests.<NonListenerPipeConnectionsAreLoggedAndIgnored>d__1.MoveNext()
[xUnit.net 00:00:29.9398884]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:29.9400457]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:29.9402044]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:29.9403507]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:29.9405043]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:29.9406604]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:29.9408078]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:29.9409626]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:29.9411180]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Microsoft.AspNetCore.Server.KestrelTests.ListenerPrimaryTests.NonListenerPipeConnectionsAreLoggedAndIgnored
Error Message:
 System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length
Stack Trace:
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStatus(String response) in /Users/travis/build/aspnet/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 80
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<ReadResponse>d__4.MoveNext() in /Users/travis/build/aspnet/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__1.MoveNext() in /Users/travis/build/aspnet/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.KestrelTests.ListenerPrimaryTests.<AssertResponseEventually>d__3.MoveNext() in /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.KestrelTests/ListenerPrimaryTests.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.KestrelTests.ListenerPrimaryTests.<NonListenerPipeConnectionsAreLoggedAndIgnored>d__1.MoveNext() in /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.KestrelTests/ListenerPrimaryTests.cs:line 155
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:33.8585785]   Finished:    Microsoft.AspNetCore.Server.KestrelTests
```

**Comment by muratg** [comment]
Assigning to @cesarbs for investigation.

**Comment by cesarbs** [comment]
@benaadams Are you still seeing this test randomly fail? I ran it in a loop for several minutes and didn't catch any failures.

**Comment by benaadams** [comment]
Nope; will reopen if it occurs again
