### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.BadHttpRequestTests.TestInvalidHeaders test failed

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1513]
Saw this on travis once

```
Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.BadHttpRequestTests.TestInvalidHeaders(rawHeaders: "Header__Vector16________Vector32\r: value\r\n\r\n", expectedExceptionMessage: "Invalid request header: 'Header__Vector16________V"...) [FAIL]
[xUnit.net 00:00:11.0621621]       System.AggregateException : One or more errors occurred. (Safe handle has been closed)
[xUnit.net 00:00:11.0622780]       ---- System.ObjectDisposedException : Safe handle has been closed
[xUnit.net 00:00:11.0656605]       Stack Trace:
[xUnit.net 00:00:11.0724411]            at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
[xUnit.net 00:00:11.0725867]            at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
[xUnit.net 00:00:11.0726953]         /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/KestrelEngine.cs(68,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
[xUnit.net 00:00:11.0727835]         /home/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/BadHttpRequestTests.cs(124,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.BadHttpRequestTests.<TestBadRequest>d__8.MoveNext()
[xUnit.net 00:00:11.0728414]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0740640]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:11.0745888]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:11.0746613]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0756723]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:11.0757591]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:11.0762468]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0768200]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:11.0768921]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:11.0769446]         ----- Inner Stack Trace -----
[xUnit.net 00:00:11.0785812]            at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
[xUnit.net 00:00:11.0803991]            at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
[xUnit.net 00:00:11.0804820]            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
[xUnit.net 00:00:11.0822755]         /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/Libuv.cs(179,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle)
[xUnit.net 00:00:11.0823961]         /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs(241,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.Post[T](Action`1 callback, T state)
[xUnit.net 00:00:11.0824866]         /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs(136,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__52.MoveNext()
Failed   Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.BadHttpRequestTests.TestInvalidHeaders(rawHeaders: "Header__Vector16________Vector32\r: value\r\n\r\n", expectedExceptionMessage: "Invalid request header: 'Header__Vector16________V"...)
Error Message:
 System.AggregateException : One or more errors occurred. (Safe handle has been closed)
---- System.ObjectDisposedException : Safe handle has been closed
Stack Trace:
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/KestrelEngine.cs:line 68
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.BadHttpRequestTests.<TestBadRequest>d__8.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/BadHttpRequestTests.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/Libuv.cs:line 179
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.Post[T](Action`1 callback, T state) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs:line 241
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__52.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs:line 136
```

**Comment by davidfowl** [comment]
Seen this on another bug:

```
[xUnit.net 00:01:12.3407322]     Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.LargeDownload [FAIL]
[xUnit.net 00:01:12.3444464]       System.AggregateException : One or more errors occurred. (Safe handle has been closed)
[xUnit.net 00:01:12.3451400]       ---- System.ObjectDisposedException : Safe handle has been closed
[xUnit.net 00:01:12.3471705]       Stack Trace:
[xUnit.net 00:01:12.3494638]            at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
[xUnit.net 00:01:12.3496502]            at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
[xUnit.net 00:01:12.3498609]         /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/KestrelEngine.cs(68,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
[xUnit.net 00:01:12.3501192]         /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/KestrelServer.cs(234,0): at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose()
[xUnit.net 00:01:12.3502842]            at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
[xUnit.net 00:01:12.3503664]            at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
[xUnit.net 00:01:12.3505017]         /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/ResponseTests.cs(79,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<LargeDownload>d__0.MoveNext()
[xUnit.net 00:01:12.3506263]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:01:12.3507504]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:01:12.3508600]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:01:12.3509512]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:01:12.3510415]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:01:12.3511126]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:01:12.3511935]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:01:12.3512904]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:01:12.3513838]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:01:12.3515266]         ----- Inner Stack Trace -----
[xUnit.net 00:01:12.3516416]            at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
[xUnit.net 00:01:12.3517375]            at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
[xUnit.net 00:01:12.3519124]            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
[xUnit.net 00:01:12.3521620]         /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/Libuv.cs(179,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle)
[xUnit.net 00:01:12.3523103]         /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs(241,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.Post[T](Action`1 callback, T state)
[xUnit.net 00:01:12.3524187]         /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs(136,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__52.MoveNext()
Failed   Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.LargeDownload
Error Message:
 System.AggregateException : One or more errors occurred. (Safe handle has been closed)
---- System.ObjectDisposedException : Safe handle has been closed
Stack Trace:
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose() in /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/KestrelEngine.cs:line 68
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose() in /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/KestrelServer.cs:line 234
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<LargeDownload>d__0.MoveNext() in /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/ResponseTests.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle) in /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Networking/Libuv.cs:line 179
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.Post[T](Action`1 callback, T state) in /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs:line 241
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__52.MoveNext() in /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelThread.cs:line 136
```

**Comment by natemcmaster** [comment]
I'm seeing this too: https://travis-ci.org/aspnet/KestrelHttpServer/jobs/214788834

```
Failed   TestInvalidRequestLines(request: "/ \r\n", expectedExceptionMessage: "Invalid request line: '/ \\x0D\\x0A'")
Error Message:
 System.AggregateException : One or more errors occurred. (Safe handle has been closed)
---- System.ObjectDisposedException : Safe handle has been closed
Stack Trace:
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose() in /Users/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/KestrelEngine.cs:line 68
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.BadHttpRequestTests.<TestBadRequest>d__9.MoveNext() in /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/BadHttpRequestTests.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle) in 
```

**Comment by halter73** [comment]
This error hasn't been observed since KestrelEngine was removed. The code, particularity pertaining to shutdown has changed significantly since that time. We can reopen if we see another shutdown ODE.
