### ISSUE TITLE
Race with AddressRegistrationTests

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/KestrelHttpServer#1520]
Seeing this failure on the CI http://aspnetci/viewLog.html?buildId=189191&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest.

Not sure what which tests this race is between but it seems like some other app that is returning `hello, world` is being run in parallel with the AddressRegistrationTests and collided on the same port.
```
[05:12:36] :			 [Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_IPv6_Success(addressInput: "http://*:8004/", testUrls: Func`2 { Method = System.String[] <get_AddressRegistrationDataIPv6>b__4(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = <>c__DisplayClass27_0 { port = 8004 } })] Assert.Equal() Failure
             (pos 1)
Expected: http://127.0.0.1:8004/
Actual:   hello, world
             (pos 1)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__7.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\AddressRegistrationTests.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_IPv6_Success>d__4.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\AddressRegistrationTests.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

cc @jbagga

**Comment by jbagga** [comment]
cc @muratg

**Comment by muratg** [comment]
cc @halter73

**Comment by halter73** [comment]
Looks like the failing test is using a method in AddressRegistrationTests called GetNextPort(). If instead the test was changed to bind to port "0", that would probably fix the race.

**Comment by cesarbs** [comment]
Looking.

**Comment by cesarbs** [comment]
@halter73 We have to bind to a specific port instead of port 0 - it's part of what's being tested. The same test data contains addresses with port 0 to test dynamic binding.

**Comment by cesarbs** [comment]
This is port re-use issue, which is on by default on Windows. This repros the issue:

```csharp
[ConditionalFact]
[IPv6SupportedCondition]
public async Task RegisterAddresses_IPv6_Success_Investigation()
{
    await RegisterAddresses_Success("http://*:8004", _ => new[] { "http://127.0.0.1:8004", "http://[::1]:8004" });
}

private async Task RegisterAddresses_Success(string addressInput, Func<IServerAddressesFeature, string[]> testUrls)
{
    var hostBuilder0 = new WebHostBuilder()
        .UseKestrel()
        .UseUrls(new[] { "http://[::1]:8004" })
        .Configure(app => app.Run(async context => await context.Response.WriteAsync("hello, world")));

    var hostBuilder = new WebHostBuilder()
        .UseKestrel()
        .UseUrls(addressInput)
        .Configure(ConfigureEchoAddress);

    using (var host0 = hostBuilder0.Build())
    {
        host0.Start();

        using (var host = hostBuilder.Build())
        {
            host.Start();

            foreach (var testUrl in testUrls(host.ServerFeatures.Get<IServerAddressesFeature>()))
            {
                var response = await HttpClientSlim.GetStringAsync(testUrl, validateCertificate: false);

                // Compare the response with Uri.ToString(), rather than testUrl directly.
                // Required to handle IPv6 addresses with zone index, like "fe80::3%1"
                Assert.Equal(new Uri(testUrl).ToString(), response);
            }
        }
    }
}
```

**Comment by Drawaes** [comment]
https://github.com/Drawaes/CondenserDotNet/blob/master/src/CondenserDotNet.Client/ServiceManagerConfig.cs#L22

Borrow those few lines of code. Then you can register a specific port and not have a race. Windows and Linux issue a port and then next time you ask issue the next even if the previous port is now unused. So unless you cycle through 60k ports quickly you will be fine.

**Comment by cesarbs** [comment]
@Drawaes We do something similar in those tests: https://github.com/aspnet/KestrelHttpServer/blob/fffb823e992a90145e319eb2d5702334e2d17a64/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs#L510 But we don't leverage dynamic port binding for that. I'm going to change the tests to use it.

I am also considering changing Kestrel to set `SO_EXCLUSIVEADDRUSE` on its sockets.

**Comment by Drawaes** [comment]
Yeah iterating gives u a race. Use the OS ;)
