### ISSUE TITLE
'System.Exception : Unexpected critical error.' in Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.DoesNotSplitPathBase on Travis

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1522]
```
Failed   Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.DoesNotSplitPathBase(registerPathBase: "/base/something", requestPath: "/base/something/more/")
Error Message:
 System.Exception : Unexpected critical error.
Stack Trace:
   at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /home/travis/build/aspnet/KestrelHttpServer/test/shared/TestApplicationErrorLogger.cs:line 47
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelTrace.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelTrace.cs:line 177
   at Microsoft.Extensions.Logging.LoggerExtensions.LogCritical(ILogger logger, String message, Object[] args)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/KestrelEngine.cs:line 63
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose() in /home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/KestrelServer.cs:line 234
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<DoesNotSplitPathBase>d__13.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/RequestTests.cs:line 577
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by muratg** [comment]
Can't find this test on the codebase. Looks like it's deleted.
