### ISSUE TITLE
Test failure: macOS, RegisterAddresses_IPv6ScopeId_Success timeout 

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#1534]
https://travis-ci.org/aspnet/KestrelHttpServer/jobs/213529760#L1293

```
Failed   Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_IPv6ScopeId_Success(addressInput: "http://[fe80::88fc:3f5a:f0fb:3da1%utun0]:0/", testUrls: Func`2 { Method = System.String[] GetTestUrls(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = null })
Error Message:
 System.Net.Sockets.SocketException : Operation timed out
Stack Trace:
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetSocket>d__7.MoveNext() in /Users/travis/build/aspnet/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by halter73** [comment]
This is now failing consistently on Travis and our internal macOS CI. The utun[0-9] scopeids appear to be years old, but I still think something must have changed in a recent OS update.

**Comment by muratg** [comment]
Fixed
