### ISSUE TITLE
TypeLoadException: Method 'get_ContentLength' in type 'Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameRequestHeaders' from assembly 'Microsoft.AspNetCore.Server.Kestrel, Version=1.1.0.0" does not have an implementation.

### ISSUE THREAD

**Issue by RogovArtem** [aspnet/KestrelHttpServer#1565]
Hello. I have some problems with Kestrel after load from **MyGet** Microsoft.AspNetCore.**SignalR**.
VS 2017
**Error**
```
System.AggregateException 
  HResult=0x80131500
  Message = One or more errors occurred.
  Source = -
 Trace the stack:
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at miraArchive.Coordinator.WebApp.Program.Main(String[] args) in C:\Users\Alex\Desktop\mira\src\miraArchive.Coordinator.WebApp\Program.cs:line 17
```

TypeLoadException: Method 'get_ContentLength' in type 'Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameRequestHeaders' from assembly 'Microsoft.AspNetCore.Server.Kestrel, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

**project.json**
```json
"dependencies": {
    "miraArchive.Coordinator.WebApp.DataClasses": "1.0.0-*",
    "miraArchive.Drive.WebService.Client": "1.0.0-*",
    "miraArchive.Drive.WebService.DataClasses": "1.0.0-*",
    "miraArchive.Robot.WebService.Client": "1.0.0-*",
    "miraArchive.Robot.WebService.DataClasses": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.1.0",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.jQuery.Unobtrusive.Ajax": "3.2.3"
  },

  "tools": {
    "BundlerMinifier.Core": "2.4.337",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by davidfowl** [comment]
Yes this can happen when you update pieces of packages without updating the whole stack. What we're you trying to update?

**Comment by RogovArtem** [comment]
On Kestrel? Nothing. Update "Microsoft.AspNetCore.Routing": "1.1.0", MVC...How can i update pieces of packages?

**Comment by RogovArtem** [comment]
@davidfowl On Kestrel? Nothing. Update "Microsoft.AspNetCore.Routing": "1.1.0", MVC...How can i update pieces of packages?

**Comment by davidfowl** [comment]
Update pieces of packages l. That's usually a bad idea unless you know which ones work together. Explain to me how you got into this situation , what nuget feeds you were using?

**Comment by RogovArtem** [comment]
In the beginning I used Nuget, but after I needed SignalR. I cant find it on nuget, but found link on myget. Add dotnet.myget.org on nuget packages and...Error).

**Comment by RogovArtem** [comment]
@davidfowl In the beginning I used Nuget, but after I needed SignalR. I cant found it on nuget, but found link on myget. Add dotnet.myget.org on nuget packages and...Error).

**Comment by davidfowl** [comment]
You can't use SignalR with 1.0.0 or 1.1.0 It depends on newer versions of those packages.

**Comment by moozzyk** [comment]
Hopefully we are talking about SignalR and not SignalR-Server

**Comment by davidfowl** [comment]
Either one is the same answer.

**Comment by RogovArtem** [comment]
@davidfowl Cant use SignalR with Kestrel 1.0.0 or what?

**Comment by davidfowl** [comment]
That is correct. SignalR cannot be used with Kestrel 1.0.0 or 1.1.0. It depends on newer features in the server that aren't available in older versions.

**Comment by RogovArtem** [comment]
@davidfowl Yes. When i delete SignalR, i was able compile project. But how i can use SignalR in my project?

**Comment by RogovArtem** [comment]
@davidfowl and i found Gray.Microsoft.AspNetCore.SignalR.Server. You know something about this? What it this?

**Comment by davidfowl** [comment]
> @davidfowl Yes. When i delete SignalR, i was able compile project. But how i can use SignalR in my project?

@RogovArtem You wait until it gets released, or you update to use nightly bits for everything.

> @davidfowl and i found Gray.Microsoft.AspNetCore.SignalR.Server. You know something about this? What it this?

Something we don't support, you'll need to ask Gray what that is (whoever he/she is).

**Comment by moozzyk** [comment]
I think it was a copy of Signalr-Server (which has been deprecated for a while now). The dependencies there are a mix of 1.0.x and 1.1.x which cause issues as the one you reported.

**Comment by RogovArtem** [comment]
@davidfowl @moozzyk Thanks for reaction and answer)
