### ISSUE TITLE
Test failure: ThrowingSynchronousConnectionAdapterDoesNotCrashServer

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1571]
```
[xUnit.net 00:00:00.8671742]   Discovering: Microsoft.AspNetCore.Server.KestrelTests
[xUnit.net 00:00:07.1435665]   Discovered:  Microsoft.AspNetCore.Server.KestrelTests
[xUnit.net 00:00:08.4595131]   Starting:    Microsoft.AspNetCore.Server.KestrelTests
[xUnit.net 00:00:16.8271431]     ThrowingSynchronousConnectionAdapterDoesNotCrashServer [FAIL]
[xUnit.net 00:00:16.8273008]       System.AggregateException : One or more errors occurred. (Safe handle has been closed)
[xUnit.net 00:00:16.8273516]       ---- System.ObjectDisposedException : Safe handle has been closed
[xUnit.net 00:00:16.8283550]       Stack Trace:
[xUnit.net 00:00:16.8296173]            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[xUnit.net 00:00:16.8297103]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[xUnit.net 00:00:16.8297865]         C:\projects\kestrelhttpserver\test\shared\TestServer.cs(76,0): at Microsoft.AspNetCore.Testing.TestServer.Dispose()
[xUnit.net 00:00:16.8298555]         C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\ConnectionAdapterTests.cs(108,0): at Microsoft.AspNetCore.Server.KestrelTests.ConnectionAdapterTests.<ThrowingSynchronousConnectionAdapterDoesNotCrashServer>d__2.MoveNext()
[xUnit.net 00:00:16.8299645]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8300127]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8300611]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:16.8301020]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8301575]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8302110]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:16.8302532]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8303245]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8303773]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:16.8304174]         ----- Inner Stack Trace -----
[xUnit.net 00:00:16.8304645]            at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
[xUnit.net 00:00:16.8305137]            at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
[xUnit.net 00:00:16.8305682]            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_read_start(UvStreamHandle handle, uv_alloc_cb alloc_cb, uv_read_cb read_cb)
[xUnit.net 00:00:16.8306720]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\Libuv.cs(275,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.read_start(UvStreamHandle handle, uv_alloc_cb alloc_cb, uv_read_cb read_cb)
[xUnit.net 00:00:16.8307876]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\UvStreamHandle.cs(104,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReadStart(Func`4 allocCallback, Action`3 readCallback, Object state)
[xUnit.net 00:00:16.8309018]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Connection.cs(87,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Connection.Start()
[xUnit.net 00:00:16.8310017]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Listener.cs(138,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status)
[xUnit.net 00:00:16.8311116]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Listener.cs(123,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.ConnectionCallback(UvStreamHandle stream, Int32 status, Exception error, Object state)
[xUnit.net 00:00:16.8312270]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\UvStreamHandle.cs(140,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.UvConnectionCb(IntPtr handle, Int32 status)
[xUnit.net 00:00:16.8313407]            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)
[xUnit.net 00:00:16.8313950]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\Libuv.cs(119,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.run(UvLoopHandle handle, Int32 mode)
[xUnit.net 00:00:16.8315039]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Infrastructure\KestrelThread.cs(317,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
[xUnit.net 00:00:16.8316284]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8316833]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8317307]            at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__48.MoveNext()
[xUnit.net 00:00:16.8317856]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8318449]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8318936]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:16.8319493]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\KestrelEngine.cs(51,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.<StopAsync>d__19.MoveNext()
Failed   ThrowingSynchronousConnectionAdapterDoesNotCrashServer
Error Message:
 System.AggregateException : One or more errors occurred. (Safe handle has been closed)
---- System.ObjectDisposedException : Safe handle has been closed
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TestServer.Dispose() in C:\projects\kestrelhttpserver\test\shared\TestServer.cs:line 76
   at Microsoft.AspNetCore.Server.KestrelTests.ConnectionAdapterTests.<ThrowingSynchronousConnectionAdapterDoesNotCrashServer>d__2.MoveNext() in C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\ConnectionAdapterTests.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_read_start(UvStreamHandle handle, uv_alloc_cb alloc_cb, uv_read_cb read_cb)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.read_start(UvStreamHandle handle, uv_alloc_cb alloc_cb, uv_read_cb read_cb) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\Libuv.cs:line 275
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReadStart(Func`4 allocCallback, Action`3 readCallback, Object state) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\UvStreamHandle.cs:line 104
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Connection.Start() in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Connection.cs:line 87
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Listener.cs:line 138
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.ConnectionCallback(UvStreamHandle stream, Int32 status, Exception error, Object state) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Listener.cs:line 123
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.UvConnectionCb(IntPtr handle, Int32 status) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\UvStreamHandle.cs:line 140
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.run(UvLoopHandle handle, Int32 mode) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\Libuv.cs:line 119
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Infrastructure\KestrelThread.cs:line 317
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.<StopAsync>d__19.MoveNext() in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\KestrelEngine.cs:line 51
```

https://ci.appveyor.com/project/aspnetci/KestrelHttpServer/branch/dev

**Comment by davidfowl** [comment]
Again:

```
Starting test execution, please wait...
[xUnit.net 00:00:00.8671742]   Discovering: Microsoft.AspNetCore.Server.KestrelTests
[xUnit.net 00:00:07.1435665]   Discovered:  Microsoft.AspNetCore.Server.KestrelTests
[xUnit.net 00:00:08.4595131]   Starting:    Microsoft.AspNetCore.Server.KestrelTests
[xUnit.net 00:00:16.8271431]     ThrowingSynchronousConnectionAdapterDoesNotCrashServer [FAIL]
[xUnit.net 00:00:16.8273008]       System.AggregateException : One or more errors occurred. (Safe handle has been closed)
[xUnit.net 00:00:16.8273516]       ---- System.ObjectDisposedException : Safe handle has been closed
[xUnit.net 00:00:16.8283550]       Stack Trace:
[xUnit.net 00:00:16.8296173]            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[xUnit.net 00:00:16.8297103]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[xUnit.net 00:00:16.8297865]         C:\projects\kestrelhttpserver\test\shared\TestServer.cs(76,0): at Microsoft.AspNetCore.Testing.TestServer.Dispose()
[xUnit.net 00:00:16.8298555]         C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\ConnectionAdapterTests.cs(108,0): at Microsoft.AspNetCore.Server.KestrelTests.ConnectionAdapterTests.<ThrowingSynchronousConnectionAdapterDoesNotCrashServer>d__2.MoveNext()
[xUnit.net 00:00:16.8299645]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8300127]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8300611]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:16.8301020]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8301575]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8302110]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:16.8302532]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8303245]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8303773]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:16.8304174]         ----- Inner Stack Trace -----
[xUnit.net 00:00:16.8304645]            at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
[xUnit.net 00:00:16.8305137]            at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
[xUnit.net 00:00:16.8305682]            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_read_start(UvStreamHandle handle, uv_alloc_cb alloc_cb, uv_read_cb read_cb)
[xUnit.net 00:00:16.8306720]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\Libuv.cs(275,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.read_start(UvStreamHandle handle, uv_alloc_cb alloc_cb, uv_read_cb read_cb)
[xUnit.net 00:00:16.8307876]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\UvStreamHandle.cs(104,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReadStart(Func`4 allocCallback, Action`3 readCallback, Object state)
[xUnit.net 00:00:16.8309018]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Connection.cs(87,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Connection.Start()
[xUnit.net 00:00:16.8310017]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Listener.cs(138,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status)
[xUnit.net 00:00:16.8311116]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Listener.cs(123,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.ConnectionCallback(UvStreamHandle stream, Int32 status, Exception error, Object state)
[xUnit.net 00:00:16.8312270]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\UvStreamHandle.cs(140,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.UvConnectionCb(IntPtr handle, Int32 status)
[xUnit.net 00:00:16.8313407]            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)
[xUnit.net 00:00:16.8313950]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\Libuv.cs(119,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.run(UvLoopHandle handle, Int32 mode)
[xUnit.net 00:00:16.8315039]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Infrastructure\KestrelThread.cs(317,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
[xUnit.net 00:00:16.8316284]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8316833]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8317307]            at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__48.MoveNext()
[xUnit.net 00:00:16.8317856]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:16.8318449]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:16.8318936]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:16.8319493]         C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\KestrelEngine.cs(51,0): at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.<StopAsync>d__19.MoveNext()
Failed   ThrowingSynchronousConnectionAdapterDoesNotCrashServer
Error Message:
 System.AggregateException : One or more errors occurred. (Safe handle has been closed)
---- System.ObjectDisposedException : Safe handle has been closed
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TestServer.Dispose() in C:\projects\kestrelhttpserver\test\shared\TestServer.cs:line 76
   at Microsoft.AspNetCore.Server.KestrelTests.ConnectionAdapterTests.<ThrowingSynchronousConnectionAdapterDoesNotCrashServer>d__2.MoveNext() in C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\ConnectionAdapterTests.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_read_start(UvStreamHandle handle, uv_alloc_cb alloc_cb, uv_read_cb read_cb)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.read_start(UvStreamHandle handle, uv_alloc_cb alloc_cb, uv_read_cb read_cb) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\Libuv.cs:line 275
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReadStart(Func`4 allocCallback, Action`3 readCallback, Object state) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\UvStreamHandle.cs:line 104
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Connection.Start() in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Connection.cs:line 87
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Listener.cs:line 138
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.ConnectionCallback(UvStreamHandle stream, Int32 status, Exception error, Object state) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Http\Listener.cs:line 123
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.UvConnectionCb(IntPtr handle, Int32 status) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\UvStreamHandle.cs:line 140
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.run(UvLoopHandle handle, Int32 mode) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Networking\Libuv.cs:line 119
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter) in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\Internal\Infrastructure\KestrelThread.cs:line 317
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.<StopAsync>d__19.MoveNext() in C:\projects\kestrelhttpserver\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv\KestrelEngine.cs:line 51
The active test run was aborted. Reason: Unable to communicate with test host process.
Total tests: 4080. Passed: 4079. Failed: 1. Skipped: 0.
```

**Comment by davidfowl** [comment]
Here's the Assert

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Handle is closed



   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvMemory.Validate(Boolean closed)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.read_start(UvStreamHandle handle, uv_alloc_cb alloc_cb, uv_read_cb read_cb)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReadStart(Func`4 allocCallback, Action`3 readCallback, Object state)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Connection.Start()

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.DispatchConnection(UvStreamHandle socket)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.ConnectionCallback(UvStreamHandle stream, Int32 status, Exception error, Object state)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.UvConnectionCb(IntPtr handle, Int32 status)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.<>c.<.cctor>b__24_0(IntPtr handle, Int32 status)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.LibuvFunctions.run(UvLoopHandle handle, Int32 mode)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Run(Int32 mode)

   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart(Object obj)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by davidfowl** [comment]
This test is racy.

**Comment by davidfowl** [comment]
We used to call `socket.ReadStart()` before starting the connection filters.

https://github.com/aspnet/KestrelHttpServer/blob/feature/dev-si/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Connection.cs#L93-L103

The reason for the change is the fact that we need to set the input and output before we start the connection.

/cc @halter73
