### ISSUE TITLE
Unhandled OperationCanceledException causing TaskScheduler.UnobservedTaskException to trigger

### ISSUE THREAD

**Issue by jahmai** [aspnet/KestrelHttpServer#1597]
Seems the same as #150 which was closed for some reason.

It is quite normal for OperationCanceledException to be thrown from a controller or middleware for various scenarios. Frame<T>.RequestProcessingAsync doesn't catch/log/swallow so it gets logged as an unhandled exception:

13 Error Connection id "0HL3KRAJRPQMK": An unhandled exception was thrown by the application.

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
at Intrinsic.Messaging.Http.XHttpClient.<QueryAsync>d__10.MoveNext() in C:\Repository\Projects\criticalarc\criticalarc\Source\Libraries\Intrinsic.Messaging.Core\Messaging\Http\XHttpClient.cs:line 237
at Intrinsic.Messaging.Channels.IXQueryableExtensions.<QueryAsync>d__0.MoveNext() in C:\Repository\Projects\criticalarc\criticalarc\Source\Libraries\Intrinsic.Messaging.Core\Messaging\Channels\IXQueryableExtensions.cs:line 25
at Intrinsic.Messaging.Protocols.AdhocCommands.XAdhocCommandExecutor.<ExecuteAsyncCore>d__33.MoveNext() in C:\Repository\Projects\criticalarc\criticalarc\Source\Libraries\Intrinsic.Messaging.Core\Messaging\Protocols\AdhocCommands\XAdhocCommandExecutor.cs:line 103
at CriticalArc.Applications.Command.Areas.Command.Controllers.AdminUsersController.<RetrieveRegistrationForm>d__8.MoveNext() in C:\Repository\Projects\criticalarc\criticalarc\Source\Libraries\CriticalArc.Applications.Command\Areas\Command\Controllers\AdminUsersController.cs:line 125
at CriticalArc.Applications.Command.Areas.Command.Controllers.AdminUsersController.<RetrieveRegistrationFormForUser>d__9.MoveNext() in C:\Repository\Projects\criticalarc\criticalarc\Source\Libraries\CriticalArc.Applications.Command\Areas\Command\Controllers\AdminUsersController.cs:line 135
at CriticalArc.Applications.Command.Areas.Command.Controllers.AdminUsersController.<RetrieveUser>d__10.MoveNext() in C:\Repository\Projects\criticalarc\criticalarc\Source\Libraries\CriticalArc.Applications.Command\Areas\Command\Controllers\AdminUsersController.cs:line 161
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ExceptionContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
at Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
at Microsoft.AspNetCore.Owin.WebSocketAcceptAdapter.<>c_DisplayClass6_0.<<AdaptWebSockets>b_0>d.MoveNext()
at CriticalArc.Applications.Command.Authentication.CookiesAbsoluteUrlFixMiddleware.<Invoke>d__4.MoveNext() in C:\Repository\Projects\criticalarc\criticalarc\Source\Libraries\CriticalArc.Applications.Command\Authentication\CookiesAbsoluteUrlFixMiddleware.cs:line 35
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```
Triggering the unhandled exception handler for OperationCanceledExceptions is undesirable.

**Comment by davidfowl** [comment]
OperationCanceledExceptions shouldn't be treated specially, they *are* unhandled exceptions and should be logged as such. Why aren't you catching exceptions if you don't want them logged?

**Comment by jahmai** [comment]
They _are_ special exceptions, since they are the base class of TaskCanceledException and can result from Task cancellations of various kinds (TPL may throw it, user may throw TaskCanceledException, may await on a TaskCancellationSource after SetCanceled() is called.

I'm not catching it because I don't want to have to try/catch that specific exception in hundreds of controller actions when it's benign, since TaskCanceledException and OperationCanceledException are only to be used in state-preserving co-operative cancellation scenarios.

**Comment by benaadams** [comment]
The framework can't assume any exception thrown from user code is benign as it doesn't know what the user code is doing or why it threw the exception.

If you want to eat them all; which probablly not a good idea, you can just add some middleware
```csharp
public class ExecptionEatingMiddleware
{
    private readonly RequestDelegate _next;

    public ExecptionEatingMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext httpContext)
    {
        try
        {
            await _next(httpContext);
        }
        catch(TaskCanceledException)
        { }
        catch (OperationCanceledException)
        { }
    }
}

public static class ExecptionEatingMiddlewareExtensions
{
    public static IApplicationBuilder UseExecptionEatingMiddleware(this IApplicationBuilder builder)
    {
        return builder.UseMiddleware<ExecptionEatingMiddleware>();
    }
}
```
Then
```csharp
app.UseExecptionEatingMiddleware();
```

**Comment by davidfowl** [comment]
They're not special. Write an MVC exception filter, or do what @benaadams suggested and eat those exceptions as well as any other special exceptions in middleware.

**Comment by jahmai** [comment]
@benaadams Thanks that's a good idea, I'll do that.
