### ISSUE TITLE
RegisterAddresses_IPv4_Success fails on OSX

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1598]
```
Failed   RegisterAddresses_IPv4_Success(addressInput: "http://Davids-MacBook-Pro-3.local:0/", testUrls: Func`2 { Method = System.String[] GetTestUrls(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = null })
Error Message:
 System.Net.Sockets.SocketException : Device not configured
```

/cc @halter73

**Comment by halter73** [comment]
No stack trace? Does this fail consistently?

**Comment by davidfowl** [comment]
Every time

```
[xUnit.net 00:00:55.7797780]     RegisterAddresses_IPv4_Success(addressInput: "http://Davids-MacBook-Pro-3.local:0/", testUrls: Func`2 { Method = System.String[] GetTestUrls(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = null }) [FAIL]
[xUnit.net 00:00:55.7866230]       System.Net.Sockets.SocketException : Device not configured
[xUnit.net 00:00:55.7881750]       Stack Trace:
[xUnit.net 00:00:55.7956470]         /Users/dfowler/dev/Universe/KestrelHttpServer/test/shared/HttpClientSlim.cs(124,0): at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetSocket>d__7.MoveNext()
[xUnit.net 00:00:55.7958040]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:55.7958910]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:55.7959780]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:55.7960440]            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[xUnit.net 00:00:55.7961190]         /Users/dfowler/dev/Universe/KestrelHttpServer/test/shared/HttpClientSlim.cs(85,0): at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStream>d__6.MoveNext()
[xUnit.net 00:00:55.7962070]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:55.7962800]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:55.7963290]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:55.7963760]            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[xUnit.net 00:00:55.7964320]         /Users/dfowler/dev/Universe/KestrelHttpServer/test/shared/HttpClientSlim.cs(24,0): at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__1.MoveNext()
[xUnit.net 00:00:55.7964770]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:55.7965370]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:55.7966080]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:55.7966540]            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[xUnit.net 00:00:55.7967140]         /Users/dfowler/dev/Universe/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs(94,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__7.MoveNext()
[xUnit.net 00:00:55.7967820]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:55.7968630]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:55.7969400]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:55.7970150]         /Users/dfowler/dev/Universe/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs(33,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_IPv4_Success>d__0.MoveNext()
[xUnit.net 00:00:55.7970850]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:55.7971540]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:55.7972070]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:55.7972490]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:55.7972960]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:55.7973410]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:55.7974090]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:55.7974570]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:55.7975060]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   RegisterAddresses_IPv4_Success(addressInput: "http://Davids-MacBook-Pro-3.local:0/", testUrls: Func`2 { Method = System.String[] GetTestUrls(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = null })
Error Message:
 System.Net.Sockets.SocketException : Device not configured
Stack Trace:
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetSocket>d__7.MoveNext() in /Users/dfowler/dev/Universe/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStream>d__6.MoveNext() in /Users/dfowler/dev/Universe/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__1.MoveNext() in /Users/dfowler/dev/Universe/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__7.MoveNext() in /Users/dfowler/dev/Universe/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_IPv4_Success>d__0.MoveNext() in /Users/dfowler/dev/Universe/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by cesarbs** [comment]
That's a pretty weird "IP address" to start with 😝

**Comment by muratg** [comment]
No repro
