### ISSUE TITLE
Make UVException Serializable (like all other exceptions)

### ISSUE THREAD

**Issue by alextolp** [aspnet/KestrelHttpServer#1609]
I'm seeing the following error consistently when running unit tests against kestrel server. It seems to be benign and happens during cleanup.

```
Warning: System.Runtime.Serialization.SerializationException: Type 'Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException' in Assembly 'Microsoft.AspNetCore.Server.Kestrel, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' is not marked as serializable.
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.SerializeObject(Object obj, MemoryStream stm)
   at System.AppDomain.Serialize(Object o)
   at System.AppDomain.MarshalObject(Object o)

   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.SerializeObject(Object obj, MemoryStream stm)
   at System.AppDomain.Serialize(Object o)
   at System.AppDomain.MarshalObject(Object o)
```

**Comment by davidfowl** [comment]
What exactly are you doing?

**Comment by alextolp** [comment]
Looks like the original exception is due to this issue:

https://github.com/aspnet/KestrelHttpServer/issues/946

After disposing the DI container, I'm no longer seeing this problem.

**Comment by davidfowl** [comment]
That exception looks completely different but glad you solved it.

**Comment by alextolp** [comment]
The UvException was wrapping the ObjectDisposedException described in #946. Ideally UvException would follow the pattern for all exceptions in the base class libraries and be Serializeable.

**Comment by davidfowl** [comment]
@alextolp updated the title of the issue.

**Comment by muratg** [comment]
We may accept a PR, though closing the bug.
