### ISSUE TITLE
Flaky test: RegisterAddresses_IPv4_Success

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/KestrelHttpServer#1620]
Seems flaky with the error:
```
System.AggregateException : One or more errors occurred. (Error -16 EBUSY resource busy or locked)
---- Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException : Error -16 EBUSY resource busy or locked
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.Dispose() in /datadrive/169923259d6dcfec/Universe/.r/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel.Core/KestrelServer.cs:line 235
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__7.MoveNext() in /datadrive/169923259d6dcfec/Universe/.r/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
```
see http://aspnetci/viewLog.html?buildId=197950&tab=buildResultsDiv&buildTypeId=CoreCLR_Linux#testNameId-6881719945987632294

cc @mikeharder @cesarbs

**Comment by JunTaoLuo** [comment]
This is different from the usual EADDRINUSE it seems.

**Comment by halter73** [comment]
The EBUSY issue is indicative of a non-gracefull shutdown we shouldn't see this in our tests aver #1707. If we ever see an EBUSY in our tests again, we can reopen this issue.
