### ISSUE TITLE
ConnectionClosesWhenFinReceivedBeforeRequestCompletes failed 

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1632]
Failed https://travis-ci.org/aspnet/KestrelHttpServer/jobs/219866246

```
Failed   ConnectionClosesWhenFinReceivedBeforeRequestCompletes(listenOptions: http://127.0.0.1:0)
Error Message:
 Assert.Equal() Failure
          ↓ (pos 0)
Expected: 
Actual:   HTTP/1.1 400 Bad Request\r\nConnection: clo···
          ↑ (pos 0)
Stack Trace:
   at Microsoft.AspNetCore.Testing.TestConnection.<ReceiveForcedEnd>d__14.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/test/shared/TestConnection.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<ConnectionClosesWhenFinReceivedBeforeRequestCompletes>d__27.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/RequestTests.cs:line 946
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Skipped  RemoteIPv6Address
[xUnit.net 00:00:45.9547305]   Finished:    Microsoft.AspNetCore.Server.Kestrel.FunctionalTests
```

**Comment by davidfowl** [comment]
Here are what the logs look like when it fails:

```
Connection id "0HL3U8G4GDD9B" started.
POST / HTTP/1.1
TakeStartLine returned false
POST / HTTP/1.1
TakeStartLine returned false
POST / HTTP/1.1
TakeStartLine returned false
Connection id "0HL3U8G4GDD9B" bad request data: "Invalid request line."
Connection id "0HL3U8G4GDD9B" disconnecting.
Connection id "0HL3U8G4GDD9B" disconnecting.
Connection id "0HL3U8G4GDD9B" stopped.
```

**Comment by davidfowl** [comment]
This test is just racy in general but I'll fix it regardless.
