### ISSUE TITLE
Flaky test in the patch/1.1.3 branch (OSX)

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KestrelHttpServer#1656]
```
`System.Net.Sockets.SocketException : Operation timed out
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetSocket>d__7.MoveNext() in /Users/asplab/buildAgent/work/d6337ac2abf63a4b/.repositories/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStream>d__6.MoveNext() in /Users/asplab/buildAgent/work/d6337ac2abf63a4b/.repositories/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__1.MoveNext() in /Users/asplab/buildAgent/work/d6337ac2abf63a4b/.repositories/KestrelHttpServer/test/shared/HttpClientSlim.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__7.MoveNext() in /Users/asplab/buildAgent/work/d6337ac2abf63a4b/.repositories/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_IPv6ScopeId_Success>d__6.MoveNext() in /Users/asplab/buildAgent/work/d6337ac2abf63a4b/.repositories/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 73
```

If there were changes in the dev branch that were made to these tests in the dev branch, we need to port these over.

**Comment by pranavkm** [comment]
cc @Eilon  \ @muratg

**Comment by Eilon** [comment]
@muratg can you assign?

**Comment by muratg** [comment]
@pakrym could you take a look?

**Comment by pakrym** [comment]
Fix: https://github.com/aspnet/KestrelHttpServer/pull/1536 backporting

**Comment by pranavkm** [comment]
More tests:

```
System.AggregateException : One or more errors occurred. (Safe handle has been closed)
---- System.ObjectDisposedException : Safe handle has been closed
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose() in /datadrive/d6337ac2abf63a4b/.repositories/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel/Internal/KestrelEngine.cs:line 54
   at Microsoft.AspNetCore.Server.KestrelTests.EngineTests.<UpgradeRequestIsNotKeptAliveOrChunked>d__39.MoveNext() in /datadrive/d6337ac2abf63a4b/.repositories/KestrelHttpServer/test/Microsoft.AspNetCore.Server.KestrelTests/EngineTests.cs:line 1429
```

```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: Secondary
Actual:   Primary
          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.KestrelTests.ListenerPrimaryTests.<ConnectionsGetRoundRobinedToSecondaryListeners>d__0.MoveNext() in /datadrive/d6337ac2abf63a4b/.repositories/KestrelHttpServer/test/Microsoft.AspNetCore.Server.KestrelTests/ListenerPrimaryTests.cs:line 82
```

Let me know if you need separate issues for this or if it's covered by the backported fix.

**Comment by pakrym** [comment]
@pranavkm not the same and looks worse.

**Comment by pakrym** [comment]
Original test is fixed, I filed https://github.com/aspnet/KestrelHttpServer/issues/1681 for `Primary/Secondary` test failure, it's pretty tight race in test code that requires product code change to be fixed so we don't think we are going to fix it in patch release. Could not reproduce `UpgradeRequestIsNotKeptAliveOrChunked` failure.
