### ISSUE TITLE
Failure on local dev

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1667]
@geoffkizer saw this once on his machine.

```
[xUnit.net 00:00:00.7767929]   Discovering: Microsoft.AspNetCore.Server.Kestrel.Core.Tests
[xUnit.net 00:00:05.5619679]   Discovered:  Microsoft.AspNetCore.Server.Kestrel.Core.Tests
[xUnit.net 00:00:06.9007596]   Starting:    Microsoft.AspNetCore.Server.Kestrel.Core.Tests
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat(Object state)
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat(Object state)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat(Object state)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)   at System.Threading.TimerQueueTimer.CallCallback()
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat(Object state)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)   at System.Threading.TimerQueueTimer.CallCallback()   at System.Threading.TimerQueueTimer.Fire()
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat(Object state)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)   at System.Threading.TimerQueueTimer.CallCallback()   at System.Threading.TimerQueueTimer.Fire()   at System.Threading.TimerQueue.FireNextTimers()
The active test run was aborted. Reason: Unable to communicate with test host process.
```

**Comment by davidfowl** [comment]
Looking at the code I can't see how this can happen..
