### ISSUE TITLE
Assert: ThreadId is incorrect

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#1672]
```
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvMemory.Validate(Boolean closed)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_close(UvLoopHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```

I get at least two of these in the functional tests when running them locally.

I also get several `Log Critical[0]: LibuvThread.StopAsync failed to terminate libuv thread.`

**Comment by Tratcher** [comment]
Probobly related:
```
Failed   ThrowsAndClosesConnectionWhenAppWritesMoreThanContentLengthWrite
Error Message:
 System.AggregateException : One or more errors occurred.
---- System.Exception : Unexpected critical error.
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer.Dispose() in C:\git\Universe\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\TestServer.cs:line 89
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<ThrowsAndClosesConnectionWhenAppWritesMoreThanContentLengthWrite>d__18.MoveNext() in C:\git\Universe\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\ResponseTests.cs:line 529
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TStatestate, Exception exception, Func`3 formatter) in C:\git\Universe\KestrelHttpServer\test\shared\TestApplicationErrorLogger.cs:line 54
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvTrace.Log[TState](LogLevel logLevel, EventIdeventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogCritical(ILogger logger, String message, Object[] args)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.<StopAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<StopAsync>d__19.MoveNext()
```

**Comment by davidfowl** [comment]
@halter73 fixed it
