### ISSUE TITLE
Fix race in ListenerPrimaryTests.ConnectionsGetRoundRobinedToSecondaryListeners test

### ISSUE THREAD

**Issue by pakrym** [aspnet/KestrelHttpServer#1681]
We saw it in 1.1.3 patch builds but same can happen in dev. 
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.Equal() Failure
          ↓ (pos 0)
Expected: Secondary
Actual:   Primary
          ↑ (pos 0)) ---> Xunit.Sdk.EqualException: Assert.Equal() Failure
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences)
   at Microsoft.AspNetCore.Server.KestrelTests.ListenerPrimaryTests.<ConnectionsGetRoundRobinedToSecondaryListeners>d__0.MoveNext() in /home/pakrym/KestrelHttpServer/test/Microsoft.AspNetCore.Server.KestrelTests/ListenerPrimaryTests.cs:line 80
```

**Comment by pranavkm** [comment]
Can we skip this test if it's unfixable without feature changes?

**Comment by muratg** [comment]
Assigning to @natemcmaster  for investigation. Please ping @pakrym as he seems to have a theory.

**Comment by pranavkm** [comment]
Still seeing this in the 1.1.3 patch. Did this get skipped?

**Comment by natemcmaster** [comment]
Not yet. We can skip in 1.1.3 patch until we have a fix for dev
