### ISSUE TITLE
NullReferenceException on Travis

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1683]
This only happened once and it didn't happen in dev but it happened in the sockets branch when running the regular libuv tests

**EDIT: It happened in dev**

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection.StopAsync()
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection.StopAsync()   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnectionManager.<>c__DisplayClass7_0.<WalkConnectionsCore>b__0(IntPtr ptr)
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection.StopAsync()   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnectionManager.<>c__DisplayClass7_0.<WalkConnectionsCore>b__0(IntPtr ptr)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_walk(UvLoopHandle loop, uv_walk_cb walk_cb, IntPtr arg)
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection.StopAsync()   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnectionManager.<>c__DisplayClass7_0.<WalkConnectionsCore>b__0(IntPtr ptr)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_walk(UvLoopHandle loop, uv_walk_cb walk_cb, IntPtr arg)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnectionManager.WalkConnectionsCore(Func`2 action, TaskCompletionSource`1 tcs)
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection.StopAsync()   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnectionManager.<>c__DisplayClass7_0.<WalkConnectionsCore>b__0(IntPtr ptr)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_walk(UvLoopHandle loop, uv_walk_cb walk_cb, IntPtr arg)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnectionManager.WalkConnectionsCore(Func`2 action, TaskCompletionSource`1 tcs)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.DoPostWork()
The active test run was aborted. Reason: Unable to communicate with test host process.
```

**Comment by davidfowl** [comment]
One theory: If StopAsync happens before `_connectionContext` is assigned it can null ref.

**Comment by muratg** [comment]
Assigning to @natemcmaster for investigation.

**Comment by natemcmaster** [comment]
Closing. Can reopen if it happens again. Haven't seen this on CI in the last week and couldn't repro on my own with the latest dev branch. I think this may have been solved by the work @halter73 did to cleanup shutdown logic. #1707
