### ISSUE TITLE
Double free in BufferSegment

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1690]
```
Unhandled Exception: System.InvalidOperationException: outstanding references detected.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.Buffers.OwnedBuffer`1.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IPipeWriter.Complete(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection.<OnRead>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by dougbu** [comment]
Have now seen this in two aspnet/Performance tests using large (D15v2) Azure machines with accelerated networking. Most recent time, was running `dotnet .\bin\Release\netcoreapp2.0\LargeStaticView.dll` in the testapp\LargeStaticView folder on Windows server. Client (Ubuntu 16.04 LTS) command was `wrk -H "Host: localhost" -H "Accept: text/plain,text/html;q=0.9,application/json;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7" -H "Connection: keep-alive" --latency -d 30 -c 512 --timeout 20 -t 32 http://10.1.9.5:5000/TagHelpers`.

A few server details:
```
> dotnet --info
.NET Command Line Tools (2.0.0-preview1-005783)

Product Information:
 Version:            2.0.0-preview1-005783
 Commit SHA-1 hash:  8bd15c7ec0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\dougbu\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005783\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-001967-00
  Build    : fa25acec41a87ce36b3ea61273d4798eb0a2486f
```

**Comment by muratg** [comment]
@pakrym I was told that you already fixed this. :)

**Comment by pakrym** [comment]
Fixed by https://github.com/dotnet/corefxlab/commit/4b96e38568cffd36b2bacb8b17722348a36436ff
