### ISSUE TITLE
Failed test on CI

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1692]
```
AspNetCore.Server.Kestrel.Core.Tests.HeartbeatTests
 ExceptionFromHeartbeatHandlerIsLoggedAsError     
 System.InvalidOperationException : Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.HeartbeatTests.ExceptionFromHeartbeatHandlerIsLoggedAsError()
```

**Comment by davidfowl** [comment]
Fixed by https://github.com/aspnet/KestrelHttpServer/commit/051c251e532f41f47877474c8586f3ef2e50ef90
