### ISSUE TITLE
Test failure: LibuvOutputConsumerTests.FailedWriteCompletesOrCancelsAllPendingTasks(maxResponseBufferSize: 1048577)

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#1712]
http://aspnetci/viewLog.html?buildId=204034&tab=buildResultsDiv&buildTypeId=CoreCLR_Windows
```
System.InvalidOperationException : Can't complete writer while writing.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IPipeWriter.Complete(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.OutputProducer.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.LibuvOutputConsumerTests.<FailedWriteCompletesOrCancelsAllPendingTasks>d__14.MoveNext() in C:\BuildAgent\work\169923259d6dcfec\Universe\.r\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests\LibuvOutputConsumerTests.cs:line 387
```

**Comment by Im5tu** [comment]
Internal link only?

**Comment by pakrym** [comment]
This is fixed by https://github.com/dotnet/corefxlab/commit/1320bf2dc1ce30baea6bde5768daf11d02907f69
