### ISSUE TITLE
Flaky Test: RejectsRequestWithContentLengthAndUpgrade

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1742]
Saw this once on AppVeyor after @natemcmaster 's change.

```
[xUnit.net 00:00:00.6503592]   Discovering: Microsoft.AspNetCore.Server.Kestrel.FunctionalTests
[xUnit.net 00:00:02.0149756]   Discovered:  Microsoft.AspNetCore.Server.Kestrel.FunctionalTests
[xUnit.net 00:00:02.5873241]   Starting:    Microsoft.AspNetCore.Server.Kestrel.FunctionalTests
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: [xUnit.net 00:00:12.8264301]     RejectsRequestWithContentLengthAndUpgrade [FAIL]
```
Not sure why it failed. If it doesn't happen again we can close this.

Exception from CI build log:

```
[Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.UpgradeTests.RejectsRequestWithContentLengthAndUpgrade]
System.IO.IOException : Unable to read data from the transport connection:
An established connection was aborted by the software in your host machine.
---- System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadAsyncInternal>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TestConnection.<Receive>d__12.MoveNext() in C:\b\w\33bdfc1cae7b2a38\.r\KestrelHttpServer\test\shared\TestConnection.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TestConnection.<ReceiveForcedEnd>d__14.MoveNext() in C:\b\w\33bdfc1cae7b2a38\.r\KestrelHttpServer\test\shared\TestConnection.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.UpgradeTests.<RejectsRequestWithContentLengthAndUpgrade>d__2.MoveNext() in C:\b\w\33bdfc1cae7b2a38\.r\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\UpgradeTests.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
```

# Repros
4/26/17: http://aspnetci/viewLog.html?buildId=209002&buildTypeId=Lite_UniverseTest&tab=buildLog&filter=err
6/1/17: http://aspnetci/viewLog.html?buildId=229908&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest

**Comment by natemcmaster** [comment]
Did something write to stderr? PowerShell treats any output to stderr as a fatal issue.

**Comment by davidfowl** [comment]
That's what happened on appveyor, there was nothing else.

**Comment by davidfowl** [comment]
Failed again on appveyor

**Comment by halter73** [comment]
Failed again May 17th.

```
ResponseTests.FailedWritesResultInAbortedRequest(listenOptions: http://127.0.0.1:0) 	
The test was run 2 times in the build, 1 failure
 System.TimeoutException : The operation at /Users/asplab/Documents/buildAgent/work/33bdfc1cae7b2a38/.r/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/ResponseTests.cs:2125 timed out after reaching the limit of 15000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<FailedWritesResultInAbortedRequest>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

http://aspnetci/viewLog.html?buildId=222385&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR

**Comment by halter73** [comment]
http://aspnetci/viewLog.html?buildId=232884&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest#testNameId-8381184854596551811

**Comment by mikeharder** [comment]
Still flaky: http://aspnetci/viewLog.html?buildId=255966&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest
