### ISSUE TITLE
Flaky Test: LibuvOutputConsumerTests on Ubuntu

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#1755]
```
[Test collection for Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.LibuvOutputConsumerTests (1)] FailedWriteCompletesOrCancelsAllPendingTasks(maxResponseBufferSize: 1024)
[FailedWriteCompletesOrCancelsAllPendingTasks(maxResponseBufferSize: 1024)] Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.LibuvOutputConsumerTests.<FailedWriteCompletesOrCancelsAllPendingTasks>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

[Test collection for Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.LibuvOutputConsumerTests (1)] FailedWriteCompletesOrCancelsAllPendingTasks(maxResponseBufferSize: 1048577)
[FailedWriteCompletesOrCancelsAllPendingTasks(maxResponseBufferSize: 1048577)] Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.LibuvOutputConsumerTests.<FailedWriteCompletesOrCancelsAllPendingTasks>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task
```

4/24/17: http://aspnetci/viewLog.html?buildId=207611&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR&tab=buildLog&filter=err

**Comment by davidfowl** [comment]
@pakrym isn't this fixed?

**Comment by pakrym** [comment]
Closing, fix for this was merged `Apr 24, 2017, 5:37 PM` build with the failure ran `24 Apr 17 15:17`
