### ISSUE TITLE
EBUSY when running functional tests in a loop on linux

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1761]
I ran the functional tests on an azure machine in a tight loop and got an EBUSY. Unfortunately, I don't know what test caused it. Nor do I have any logs.

```
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -16 EBUSY resource busy or locked
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowIfErrored(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_close(UvLoopHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalDispose()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.ThreadStart(Object parameter)
```

**Comment by halter73** [comment]
Well, we *do* know how to get rid of the EBUSY 😉.

**Comment by davidfowl** [comment]
Got more info with logging:

There seems to be a rogue pipe handle still open when we get the EBUSY:

`Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvPipeHandle`

**Comment by davidfowl** [comment]
It gets better:

```
Starting thread 31
Setting up tcp listener
Creating dispatch pipe 1
Disposing the listen socket
Disposing listen pipe and 0 dispatch pipes
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvPipeHandle - OnListenPipe.dispatchPipe
Exception:
================
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -16 EBUSY resource busy or locked
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowIfErrored(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_close(UvLoopHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalDispose()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.ThreadStart(Object parameter)
================
```

> Disposing listen pipe and 0 dispatch pipes

Somehow, the list of dispatch pipes is empty...

**Comment by davidfowl** [comment]
The read callback handling in https://github.com/aspnet/KestrelHttpServer/blob/3375cf0e28c02056ccb6fa51d297971188357f0d/src/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv/Internal/ListenerPrimary.cs#L224 isn't great. It assumes the happy path (doesn't handle EOF because it assumes ReadStop will be called before that happens).

**Comment by davidfowl** [comment]
The plot thickens:

```
Starting thread 49
Setting up tcp listener
Creating dispatch pipe 1
Disposing the listen socket
Disposing listen pipe and 0 dispatch pipes
PipeReadContext.ReadCallback(16)
Got the correct message, adding dispatch pipe to list of pipes
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvPipeHandle - OnListenPipe.dispatchPipe
Exception:
================
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -16 EBUSY resource busy or locked
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowIfErrored(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_close(UvLoopHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalDispose()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.ThreadStart(Object parameter)
================
```

**Comment by davidfowl** [comment]
Finally:

```
Starting thread 45
Setting up tcp listener
Creating dispatch pipe 1
ListenerPrimary.DispatchConnection to one of 0 dispatch pipes. 55422174
Disposing the listen socket
Disposing listen pipe and 0 dispatch pipes. 55422174
PipeReadContext.ReadCallback(16)
Got the correct message, adding dispatch pipe to list of pipes
Overall we have 1 dispatch pipes. 55422174
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvPipeHandle - OnListenPipe.dispatchPipe
Exception:
================
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -16 EBUSY resource busy or locked
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowIfErrored(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_close(UvLoopHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalDispose()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.ThreadStart(Object parameter)
================
```

The problem is order of events. Disposing the pipe happens before the pipe gets added to the list of connections.
