### ISSUE TITLE
Blank Response from Kestrel for Host Header Edge Cases

### ISSUE THREAD

**Issue by rich3737** [aspnet/KestrelHttpServer#1765]
### Blank Response from Kestrel for Host Header Edge Cases
Kestrel does not return a proper HTTP response for some Host header values, as outlined in the repro steps below.

### Functional impact
No response is returned from Kestrel for this edge case. Only impacts that specific request.

### Minimal repro steps

1. Run the SampleApp from the KestrelHttpServer repo. Repro steps were tested on dev branch as of commit a053ca47.
2. Issue the following request and note that the server does not provide a response. The example request has a Host header with 64 characters, with a comma (‘,’) for one of the characters (any position).

```
GET / HTTP/1.1
Host: ,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

3. Re-issue the request while debugging Kestrel and note that an exception occurs within FrameOfT.RequestProcessingAsync() when calling the CreateContext method.
4. Note that the exception is then caught within the last catch block of the RequestProcessingAsync() method.

The exception displayed in the SampleApp console window is the following:

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.AggregateException: An error occurred while writing to logger(s). ---> System.ArgumentException: Decoded string is not a valid IDN name.
Parameter name: unicode
   at System.Globalization.IdnMapping.GetAsciiUsingOS(String unicode)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index)
   at Microsoft.AspNetCore.Http.HostString.ToUriComponent()
   at Microsoft.AspNetCore.Http.HostString.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.AspNetCore.Hosting.Internal.HostingRequestStartingLog.ToString()
   at Microsoft.AspNetCore.Hosting.Internal.HostingRequestStartingLog.<>c.<.cctor>b__11_0(Object state, Exception exception)
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.LogRequestStarting(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.CreateContext(IFeatureCollection contextFeatures)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
---> (Inner Exception #0) System.ArgumentException: Decoded string is not a valid IDN name.
Parameter name: unicode
   at System.Globalization.IdnMapping.GetAsciiUsingOS(String unicode)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index)
   at Microsoft.AspNetCore.Http.HostString.ToUriComponent()
   at Microsoft.AspNetCore.Http.HostString.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.AspNetCore.Hosting.Internal.HostingRequestStartingLog.ToString()
   at Microsoft.AspNetCore.Hosting.Internal.HostingRequestStartingLog.<>c.<.cctor>b__11_0(Object state, Exception exception)
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
```

### Further technical details
Replacing the ',' in the 64 character Host header with any of the following hex values also hits the same exception:

1,2,3,4,5,6,7,8,B,C,E,F,10,11,12,13,14,15,16,17,18,19,1A,1B,1C,1D,1E,1F,21,22,23,24,26,27,28,29,2A,2B,2C,2F,3B,3C,3D,3E,3F,40,5C,5E,5F,60,7B,7C,7D,7E,7F

**Comment by halter73** [comment]
@rich3737 Can you include the exception type and message in the issue? Right now I just see the stack trace for it.

**Comment by rich3737** [comment]
Sorry, I snipped too much. I updated the full output from the SampleApp in repro steps above. System.AggregateException with inner exception System.ArgumentException: Decoded string is not a valid IDN name.

**Comment by Tratcher** [comment]
So by blank response you mean you get a 500 response with no body? Moving this issue to Hosting. The logger should use .Value on HostString, PathString, etc.. because it's not concerned about the wire safe 
https://github.com/aspnet/Hosting/blob/6527001b3f7929806d5e4cd7f2d46448312c9fcd/src/Microsoft.AspNetCore.Hosting/Internal/HostingRequestStartingLog.cs#L67

Generating links, redirects, etc, will still fail though. Garbage in, garbage out...

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Hosting#1048
