### ISSUE TITLE
Test failure: BlockedHeartbeatDoesntCauseOverlapsAndIsLoggedAsError 

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1768]
On my dev machine:

```
[xUnit.net 00:00:09.8610412]     BlockedHeartbeatDoesntCauseOverlapsAndIsLoggedAsError [FAIL]
[xUnit.net 00:00:09.8621075]       Moq.MockException :
Expected invocation on the mock once, but was 2 times: h => h.OnHeartbeat(4/25/2017 3:35:29 PM -07:00)
[xUnit.net 00:00:09.8621946]
[xUnit.net 00:00:09.8622312]       Configured setups:
[xUnit.net 00:00:09.8622635]       h => h.OnHeartbeat(4/25/2017 3:35:29 PM -07:00), Times.Exactly(2)
[xUnit.net 00:00:09.8622922]
[xUnit.net 00:00:09.8623201]       Performed invocations:
[xUnit.net 00:00:09.8623506]       IHeartbeatHandler.OnHeartbeat(4/25/2017 3:35:29 PM -07:00)
[xUnit.net 00:00:09.8623814]       IHeartbeatHandler.OnHeartbeat(4/25/2017 3:35:29 PM -07:00)
[xUnit.net 00:00:09.8646901]       Stack Trace:
[xUnit.net 00:00:09.8658590]            at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
[xUnit.net 00:00:09.8659995]            at Moq.Mock.VerifyCalls(Interceptor targetInterceptor, MethodCall expected, Expression expression, Times times)
[xUnit.net 00:00:09.8660534]            at Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
[xUnit.net 00:00:09.8661150]            at Moq.Mock`1.Verify(Expression`1 expression, Times times)
[xUnit.net 00:00:09.8661828]            at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.HeartbeatTests.BlockedHeartbeatDoesntCauseOverlapsAndIsLoggedAsError()
Failed   BlockedHeartbeatDoesntCauseOverlapsAndIsLoggedAsError
Error Message:
 Moq.MockException :
Expected invocation on the mock once, but was 2 times: h => h.OnHeartbeat(4/25/2017 3:35:29 PM -07:00)

Configured setups:
h => h.OnHeartbeat(4/25/2017 3:35:29 PM -07:00), Times.Exactly(2)

Performed invocations:
IHeartbeatHandler.OnHeartbeat(4/25/2017 3:35:29 PM -07:00)
IHeartbeatHandler.OnHeartbeat(4/25/2017 3:35:29 PM -07:00)
Stack Trace:
   at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
   at Moq.Mock.VerifyCalls(Interceptor targetInterceptor, MethodCall expected, Expression expression, Times times)
   at Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
   at Moq.Mock`1.Verify(Expression`1 expression, Times times)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.HeartbeatTests.BlockedHeartbeatDoesntCauseOverlapsAndIsLoggedAsError()
```

**Comment by davidfowl** [comment]
This one is a bit harder to make deterministic but we can try

**Comment by ryanbrandenburg** [comment]
Doesn't seem to be fixed for all cases:
```
Moq.MockException : 
Expected invocation on the mock once, but was 0 times: h => h.OnHeartbeat(12/8/2017 10:47:18 PM +00:00)

Configured setups:
h => h.OnHeartbeat(12/8/2017 10:47:18 PM +00:00), Times.Never
No invocations performed.
   at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
   at Moq.Mock.VerifyCalls(Interceptor targetInterceptor, MethodCall expected, Expression expression, Times times)
   at Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
   at Moq.Mock`1.Verify(Expression`1 expression, Times times)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.HeartbeatTests.BlockedHeartbeatDoesntCauseOverlapsAndIsLoggedAsError() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\KestrelHttpServer\test\Kestrel.Core.Tests\HeartbeatTests.cs:line 45
```

As seen [here](http://aspnetci/viewLog.html?buildId=364749&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win8_Universe#testNameId-4122240585433300597).
