### ISSUE TITLE
Kestrel should not crash if a middleware crashes

### ISSUE THREAD

**Issue by moozzyk** [aspnet/KestrelHttpServer#180]
When running MusicStore on Kestrel try to Login using Twitter. The TwitterAuthenticationMiddlerware will crash due to https://github.com/dotnet/corefx/issues/2155 resulting and will bring Kestrel down. I would expect Kestrel to return 500 and be able to continue handling requests. 

Just in case, here is the stack trace:

```
Application started. Press Ctrl+C to shut down.
warning : [Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager] No XML encryptor configured. Key {2f3163f8-0069-f5a9-c1c3-977eef9ac21f} may be persisted to storage in unencrypted form.
warning : [Microsoft.AspNet.Authentication.Twitter.TwitterAuthenticationMiddleware] Invalid state

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'winhttp.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.WinHttp.WinHttpSetStatusCallback(SafeWinHttpHandle handle, WINHTTP_STATUS_CALLBACK callback, UInt32 notificationFlags, IntPtr reserved)
   at System.Net.Http.WinHttpHandler.SetStatusCallback(SafeWinHttpHandle requestHandle, WINHTTP_STATUS_CALLBACK callback)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__120.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
terminate called after throwing an instance of 'PAL_SEHException'
Aborted (core dumped)
```

**Comment by muratg** [comment]
@JunTaoLuo Could you try this with a middleware that just crashes?  Kestrel itself should be resilient to such issues.

**Comment by cesarbs** [comment]
Based on this:

    terminate called after throwing an instance of 'PAL_SEHException'
    Aborted (core dumped)

This looks like an exception was thrown way down in the stack, by C++ code, and then the process was terminated. This is not something we could have caught.

Kestrel **is** resilient to managed exceptions thrown by middleware.

Closing.
