### ISSUE TITLE
Write to non-body 204 response 

### ISSUE THREAD

**Issue by a764578566** [aspnet/KestrelHttpServer#1818]
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL4MKANNC7AL": An unhandled exception was thrown by the application.
System.InvalidOperationException: Write to non-body 204 response.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.HandleNonBodyResponseWrite()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.<WriteAsyncAwaited>d__183.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jazea.Logging.SessionMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 10805.1046ms 204 application/json

why have an exception was thrown?    Request finished in 204 application/json 
Help me !!!
Thanks

**Comment by Tratcher** [comment]
https://tools.ietf.org/html/rfc7231#section-6.3.5
>    The 204 (No Content) status code indicates that the server has
   successfully fulfilled the request and that there is no additional
   content to send in the response payload body
...
>   A 204 response is terminated by the first empty line after the header
   fields because it cannot contain a message body.

Why are you trying to send a response body with a 204 status code?
