### ISSUE TITLE
Flaky Test: ConnectionResetBetweenRequestsIsLoggedAsDebug

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1835]
```
Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<ConnectionResetBetweenRequestsIsLoggedAsDebug>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

http://aspnetci/viewLog.html?buildId=219517&tab=buildResultsDiv&buildTypeId=CoreCLR_Darwin

**Comment by kichalla** [comment]
01b8d5fad1753a1eda61124d1b08447a81a8f0c0
