### ISSUE TITLE
Flaky Test: CanHandleRequestsWithUrlInAbsoluteForm

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1839]
http://aspnetci/viewLog.html?buildId=220233&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe

```
System.TimeoutException : The operation at C:\BuildAgent\work\33bdfc1cae7b2a38\.r\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\RequestTests.cs:604 timed out after reaching the limit of 10000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<CanHandleRequestsWithUrlInAbsoluteForm>d__18.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\.r\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\RequestTests.cs:line 598
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by davidfowl** [comment]
Something is getting stalled, somewhere, there are a bunch of seemingly random tests that timeout like this.

**Comment by natemcmaster** [comment]
This hasn't reproduced since May. We can re-open if it begins to fail again.
