### ISSUE TITLE
Test failure on .NET 4.6.1: MaxRequestBufferSizeTests.LargeUpload

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1850]
Failing occasionally specifically with these inputs: `LargeUpload(maxRequestBufferSize: 20971519, connectionAdapter: False, expectPause: False)`:

```
[xUnit.net 00:01:14.9070146]     LargeUpload(maxRequestBufferSize: 20971519, connectionAdapter: False, expectPause: False) [FAIL]
[xUnit.net 00:01:14.9985686]       System.IO.IOException : Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
[xUnit.net 00:01:14.9986601]       ---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
[xUnit.net 00:01:15.1096310]       Stack Trace:
[xUnit.net 00:01:15.1413459]            at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
[xUnit.net 00:01:15.1691890]            at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
[xUnit.net 00:01:15.2289030]            at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
[xUnit.net 00:01:15.2290481]            at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
[xUnit.net 00:01:15.2291153]            at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
[xUnit.net 00:01:15.2291854]            at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
[xUnit.net 00:01:15.2292631]         MaxRequestBufferSizeTests.cs(111,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.MaxRequestBufferSizeTests.<>c__DisplayClass4_1.<<LargeUpload>b__0>d.MoveNext()
[xUnit.net 00:01:15.2293695]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:01:15.2294540]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:01:15.2295226]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:01:15.2295783]            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[xUnit.net 00:01:15.2296469]         MaxRequestBufferSizeTests.cs(160,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.MaxRequestBufferSizeTests.<LargeUpload>d__4.MoveNext()
[xUnit.net 00:01:15.2297393]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:01:15.2297942]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:01:15.2298507]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:01:15.2298980]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:01:15.2299516]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:01:15.2300088]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:01:15.2301120]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:01:15.2301777]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:01:15.2302358]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:01:15.2302985]         ----- Inner Stack Trace -----
[xUnit.net 00:01:15.2303598]            at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
[xUnit.net 00:01:15.2304760]            at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
Failed   LargeUpload(maxRequestBufferSize: 20971519, connectionAdapter: False, expectPause: False)
Error Message:
 System.IO.IOException : Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
Stack Trace:
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.MaxRequestBufferSizeTests.<>c__DisplayClass4_1.<<LargeUpload>b__0>d.MoveNext() in D:\src\aspnet\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\MaxRequestBufferSizeTests.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.MaxRequestBufferSizeTests.<LargeUpload>d__4.MoveNext() in D:\src\aspnet\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\MaxRequestBufferSizeTests.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
```

**Comment by muratg** [comment]
Assigning to @cesarbs for investigation in 2.0.0.

**Comment by natemcmaster** [comment]
Appears to be machine-specific. It fails consistently on my machine and @cesarbs's, but not @halter73's or CI agents. It could be something to do with the hardware (processor speeds, available memory, etc.)
