### ISSUE TITLE
Ungraceful WebSocket close

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/KestrelHttpServer#1860]
Seeing this in SignalR whenever we close a WebSocket connection.

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally.
System.InvalidOperationException: Can't complete reader while reading.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipelines
ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource, String location)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IPipeReader.Complete(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<ConsumeAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

```

**Comment by halter73** [comment]
I think this is a regression related to [this change](https://github.com/aspnet/KestrelHttpServer/commit/197eb43d8ac3264384cd895fd197d4f214669b76?diff=unified#diff-060426e10409f4964955daed781d6439L162). Prior to this, MessageBody.Consume(Async) wasn't called for upgraded requests, so it didn't matter if SignalR was still reading from the websocket after the app func completed.

**Comment by muratg** [comment]
cc @cesarbs

**Comment by muratg** [comment]
Fixed by @halter73 already.
