### ISSUE TITLE
Flaky test: ThreadCountTests.OneToTenThreads

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#1867]
```
ThreadCountTests.OneToTenThreads(threadCount: 10) 	
The test was run 2 times in the build, 1 failure
First failure:	dev	#17231 	Nate McMaster (1) 	26 May 17 14:44
 System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ThreadCountTests.<OneToTenThreads>d__0.MoveNext() in C:\b\w\1e8cd6334ef22651\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\ThreadCountTests.cs:line 51
```

http://aspnetci/viewLog.html?buildId=226952&tab=buildResultsDiv&buildTypeId=Lite_KestrelHttpServer  

Code: https://github.com/aspnet/KestrelHttpServer/commit/c343628926800a9a9668500b15fc5b2f13805241

**Comment by muratg** [comment]
We'll file another one if we see it again.
