### ISSUE TITLE
SSL connection adapter fails with Interop+AppleCrypto+SslException error on macOS

### ISSUE THREAD

**Issue by tverboon** [aspnet/KestrelHttpServer#1868]
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview1-005977/
 
We're using Kestrel in development with Https and on the Mac I periodically (after some idle time?) get the request to enter some password originating from Keychain.

![screen shot 2017-05-29 at 11 34 12](https://cloud.githubusercontent.com/assets/6871049/26544663/d55ee4fc-4462-11e7-803f-90e9ed73b5a7.png)

Not knowing the password and after cancelling, I see the following exception:

```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+AppleCrypto+SslException: Cipher Suite negotiation failure
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapter.<OnConnectionAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.FrameConnection.<ApplyConnectionAdaptersAsync>d__32.MoveNext()
```

Not sure if this is really a Kestrel issue or some issue in the new Mac native AppleCrypto.

Workaround is to kill and restart with dotnet run.

**Comment by natemcmaster** [comment]
cc @bartonjs

**Comment by bartonjs** [comment]
@tverboon Any idea what sort of timescale we're talking here? 30 seconds? 5 minutes? An hour?

**Comment by tverboon** [comment]
About 10 minutes. Reproduced it now a couple of times. Just wait ten minutes and then do a page request.

**Comment by bartonjs** [comment]
@tverboon Looks like it's about 5.  Filed https://github.com/dotnet/corefx/issues/20509 to get this fixed.

If you call cert.GetRSAPrivateKey() every 4 minutes or so and call SignData with that key, that should reset the idle timeout as a workaround.

**Comment by tverboon** [comment]
Thanks! Workaround works and you already fixed this. Good work 👍

**Comment by muratg** [comment]
Fixed (External)
