### ISSUE TITLE
Test failure on macOS: ConnectionCountingReturnsToZero 

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1871]
```
[xUnit.net 00:02:59.1255330]     ConnectionCountingReturnsToZero [FAIL]
[xUnit.net 00:02:59.1297990]       System.TimeoutException : The operation at /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/ConnectionLimitTests.cs:182 timed out after reaching the limit of 60000ms.
[xUnit.net 00:02:59.1326380]       Stack Trace:
[xUnit.net 00:02:59.1363270]            at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
[xUnit.net 00:02:59.1375630]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:02:59.1378600]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:02:59.1380610]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:02:59.1383590]         /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/ConnectionLimitTests.cs(182,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionLimitTests.<ConnectionCountingReturnsToZero>d__3.MoveNext()
[xUnit.net 00:02:59.1387530]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:02:59.1388940]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:02:59.1390480]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:02:59.1391820]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:02:59.1393440]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:02:59.1398360]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:02:59.1399210]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:02:59.1400330]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:02:59.1402160]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   ConnectionCountingReturnsToZero
Error Message:
 System.TimeoutException : The operation at /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/ConnectionLimitTests.cs:182 timed out after reaching the limit of 60000ms.
Stack Trace:
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionLimitTests.<ConnectionCountingReturnsToZero>d__3.MoveNext() in /Users/travis/build/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/ConnectionLimitTests.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

https://travis-ci.org/aspnet/KestrelHttpServer/jobs/237647756

**Comment by cesarbs** [comment]
cc @natemcmaster

**Comment by natemcmaster** [comment]
Let's lower the connection count in that test. Those agents are _really_ slow.
