### ISSUE TITLE
Finalization throw error on UvHandle.ReleaseHandle kill process

### ISSUE THREAD

**Issue by maximburyak** [aspnet/KestrelHttpServer#1890]
Just got (using 1.1.2) we just got this error.
I know that there was an issue of this being thrown during dispose, but this is raised from the finalizer.

```
Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.PostCloseHandle(Action`1 callback, IntPtr handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvHandle.ReleaseHandle()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```

**Comment by davidfowl** [comment]
This happened during shutdown right?

**Comment by maximburyak** [comment]
No, we've seen it during startup.

**Comment by halter73** [comment]
How often do you see this? Are you aware of anything unusual in your app or environment that might lead to this issue? It would also help if you could post the source for an app that you've seen crash like this in a gist or something.

**Comment by maximburyak** [comment]
@halter73 that's pretty rare, happened on my machine once, and as I understand, happens during our tests run pretty rarely.  We received the error while starting up a several servers concurrently during a test scenario , for all it's worth, here's the code of starting up a single kestrel instance: https://github.com/ravendb/ravendb/blob/v4.0/src/Raven.Server/RavenServer.cs#L140

**Comment by muratg** [comment]
@maximburyak let us know if you could get a more consistent repro that could help with our investigation.
