### ISSUE TITLE
[Patch 1.1.3] Error -16 EBUSY resource busy or locked

### ISSUE THREAD

**Issue by Jamesxql** [aspnet/KestrelHttpServer#1909]
I have seven web api applications on a same server hosted by `systemd` as a daemon . Sometimes when I stop my application, one of these applications will report this error:

```c#
Unhandled Exception: System.AggregateException: One or more errors occurred. (Error -16 EBUSY resource busy or locked) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -16 EBUSY resource busy or locked
    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_close(UvLoopHandle handle)
    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.ReleaseHandle()
    at System.Runtime.InteropServices.SafeHandle.InternalDispose()
    at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
--- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__51.MoveNext()
--- End of inner exception stack trace ---
    at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
    at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
    at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose()
    at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
    at Oathkeeper.Api.Program.Main(String[] args)
```

The Kestrel version is :  1.1.2 
The Web Server: Ubuntu 16.04.2

The error occurred randomly among these seven applications. What's the reason?

**Comment by natemcmaster** [comment]
Possible duplicate of https://github.com/aspnet/KestrelHttpServer/issues/1231?

**Comment by davidfowl** [comment]
@halter73 @muratg We should backport this fix to 1.x https://github.com/aspnet/KestrelHttpServer/pull/1798

**Comment by muratg** [comment]
cc @Eilon @shirhatti Patch candidate (1.1.3)

**Comment by muratg** [comment]
Bug for 1.0.5: https://github.com/aspnet/KestrelHttpServer/issues/1910

**Comment by Eilon** [comment]
So this is already fixed in 2.0?

**Comment by halter73** [comment]
Yes through the combination of https://github.com/aspnet/KestrelHttpServer/pull/1798 and https://github.com/aspnet/KestrelHttpServer/pull/1633.

**Comment by Eilon** [comment]
This patch is *approved* for 1.1.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.
