### ISSUE TITLE
Nginx 111: Connection refused errors.

### ISSUE THREAD

**Issue by Jamesxql** [aspnet/KestrelHttpServer#1921]
I'm running ASP.NET Core Application behind Nginx. Sometimes, nginx will be given an error: 

`5181277 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: , request: "GET /xxx/xxx?key=value HTTP/1.1", upstream: "http://xxxxx:1234/xxx/xxx?key=value", host: "xx.xxxxx.com"`

The nginx configuration like this:

```
user  nginx;
worker_processes  1;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

#    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                      '$status $body_bytes_sent "$http_referer" '
#                      '"$http_user_agent"' '$http_x_forwarded_for' '"$proxy_add_x_forwarded_for"';

log_format main '{ "@timestamp": "$time_local", '
                         '"@fields": { '
                         '"remote_addr": "$remote_addr", '
                         '"remote_user": "$remote_user", '
                         '"upstream_addr": "$upstream_addr", '
                         '"upstream_response_time": "$upstream_response_time", '
                         '"body_bytes_sent": "$body_bytes_sent", '
                         '"request_time": "$request_time", '
                         '"status": "$status", '
                         '"request": "$request", '
                         '"request_method": "$request_method", '
                         '"request_uri": "$request_uri", '
                         '"http_referer": "$http_referer", '
                         '"body_bytes_sent":"$body_bytes_sent", '
                         '"http_x_forwarded_for": "$http_x_forwarded_for", '
                         '"proxy_add_x_forwarded_for": "$proxy_add_x_forwarded_for", '
                         '"http_user_agent": "$http_user_agent" } }';



    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    gzip  on;
    gzip_comp_level    5;
    gzip_min_length    256;
    gzip_proxied       any;
    gzip_vary          on;
    gzip_types
      application/atom+xml
      application/javascript
      application/json
      application/ld+json
      application/manifest+json
      application/rss+xml
      application/vnd.geo+json
      application/vnd.ms-fontobject
      application/x-font-ttf
      application/x-web-app-manifest+json
      application/xhtml+xml
      application/xml
      font/opentype
      image/bmp
      image/svg+xml
      image/x-icon
      text/cache-manifest
      text/css
      text/plain
      text/vcard
      text/vnd.rim.location.xloc
      text/vtt
      text/x-component
      text/x-cross-domain-policy;

    #
# Wide-open CORS config for nginx
#

    include /etc/nginx/conf.d/*.conf;
}
```

```
upstream visitor {
#        server 172.31.31.228:5005;
        server 172.31.5.38:5005;
    }

location ^~ /visitor/ {
        proxy_pass http://visitor/;

        proxy_buffer_size  128k;

        proxy_buffers   32 32k;

        proxy_busy_buffers_size 128k;
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host:$server_port;
        proxy_cache_bypass $http_upgrade;
    }
```

I'm sure my ASP.NET Core WebAPI is working well, but the client received 502 error. How can I resolve this problem?

**Comment by halter73** [comment]
The 502 is coming from nginx since it cannot connect to 172.31.5.38:5005. Have you verified that you can connect to 172.31.5.38:5005 from the machine running nginx?

Do you have [ASP.NET Core's Logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging) enabled? This might not help if the dotnet process crashed or for some reason isn't running, but in that case using a watchdog process and capturing the dotnet processes's stdout/stderr to a file could help.

**Comment by Jamesxql** [comment]
`Have you verified that you can connect to 172.31.5.38:5005 from the machine running nginx?`
Yes, I can connect to 172.31.5.38:5005 from the machine running nginx.

This error occurs only when there are too many requests, so I'm wondering what will Kestrel do when requests are more than Kestrel's processing capability? Does Kestrel will immediately refuse to connect?

**Comment by halter73** [comment]
@Jamesxql Can you connect directly to Kestrel using curl or something at the time you are seeing the 502 errors? Is the CPU close to 100% when this happens. Do you need to do anything to stop the 502 responses, or does it eventually start working again when the load dies down? As mentioned before, logs might be helpful.

Kestrel does have a ListenBacklog of 128 pending unaccepted connections, but I have not seen connections get refused before as a result of that backlog filling up. This is because Kestrel accepts connections immediately when the listen callback is fired, and no application or HTTP parsing code runs on the IO threads. I'm wondering if it's a crash or a deadlock causing the connection refused errors.

**Comment by Jamesxql** [comment]
`Do you need to do anything to stop the 502 responses, or does it eventually start working again when the load dies down`
No, I don't need do anything to stop the 502 responses, it start working again when the load dies down.

And I found some information in the log file: 
```
Jun 26 17:33:32 ip-172-31-5-38 component.westeros.visitor[15817]: Hosting environment: Production
Jun 26 17:33:32 ip-172-31-5-38 component.westeros.visitor[15817]: Content root path: /opt/feiniu/Component/Westeros/visitor
Jun 26 17:33:32 ip-172-31-5-38 component.westeros.visitor[15817]: Now listening on: http://0.0.0.0:5005
Jun 26 17:33:32 ip-172-31-5-38 component.westeros.visitor[15817]: Application started. Press Ctrl+C to shut down.
Jun 26 17:33:38 ip-172-31-5-38 component.westeros.visitor[15817]: Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
Jun 26 17:33:38 ip-172-31-5-38 component.westeros.visitor[15817]:    at MySql.Data.MySqlClient.Results.Row.GetValue(Int32 ordinal)
Jun 26 17:33:38 ip-172-31-5-38 component.westeros.visitor[15817]:    at MySql.Data.MySqlClient.MySqlDataReader.GetString(Int32 ordinal)
Jun 26 17:33:38 ip-172-31-5-38 component.westeros.visitor[15817]:    at Westeros.Controllers.PassengerController.<>c__DisplayClass9_0.<<PassengerList>b__0>d.MoveNext()
Jun 26 17:33:38 ip-172-31-5-38 component.westeros.visitor[15817]: --- End of stack trace from previous location where exception was thrown ---
Jun 26 17:33:38 ip-172-31-5-38 component.westeros.visitor[15817]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Jun 26 17:33:38 ip-172-31-5-38 component.westeros.visitor[15817]:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Jun 26 17:33:38 ip-172-31-5-38 component.westeros.visitor[15817]:    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
Jun 26 17:33:38 ip-172-31-5-38 component.westeros.visitor[15817]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Jun 26 17:33:38 ip-172-31-5-38 systemd[1]: feiniu.component.westeros.visitor.service: Main process exited, code=killed, status=6/ABRT
Jun 26 17:33:38 ip-172-31-5-38 systemd[1]: feiniu.component.westeros.visitor.service: Unit entered failed state.
Jun 26 17:33:38 ip-172-31-5-38 systemd[1]: feiniu.component.westeros.visitor.service: Failed with result 'signal'.
Jun 26 17:33:48 ip-172-31-5-38 systemd[1]: feiniu.component.westeros.visitor.service: Service hold-off time over, scheduling restart.
Jun 26 17:33:48 ip-172-31-5-38 systemd[1]: Stopped Feiniubus API Visitor.
Jun 26 17:33:48 ip-172-31-5-38 systemd[1]: Started Feiniubus API Visitor.
Jun 26 17:33:49 ip-172-31-5-38 component.westeros.visitor[15856]: Hosting environment: Production
Jun 26 17:33:49 ip-172-31-5-38 component.westeros.visitor[15856]: Content root path: /opt/feiniu/Component/Westeros/visitor
Jun 26 17:33:49 ip-172-31-5-38 component.westeros.visitor[15856]: Now listening on: http://0.0.0.0:5005
Jun 26 17:33:49 ip-172-31-5-38 component.westeros.visitor[15856]: Application started. Press Ctrl+C to shut down.
```

But, why the program exception will cause Kestrel to restart?

**Comment by muratg** [comment]
The exceptions seems to be coming from MySql through a ThreadPool thread.  Most likely a bug in PassengerController.

If you're still having issues, please file another bug with details.  Thanks.
