### ISSUE TITLE
NullReferenceException in UvWriteCb

### ISSUE THREAD

**Issue by romans01** [aspnet/KestrelHttpServer#1981]
We are randomly getting NRE in UvWriteCb in Core 2.

Here are the logs:

dbug: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[2]
      Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
      Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
fail: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[0]
      UvWriteCb
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvWriteReq.UvWriteCb(IntPtr ptr, Int32 status)
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[5]
      Hosting shutdown
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL6RCR8F3VN8" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[7]
      Connection id "0HL6RCR8F3VN8" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL6RCR8F3VN9" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL6RCR8F3VNB" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL6RCR8F3VNC" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL6RCR8F3VND" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[8]
      Connection id "0HL6RCR8F3VN8" sent FIN with status "0".
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HL6RCR8F3VN8" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[7]
      Connection id "0HL6RCR8F3VNB" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[7]
      Connection id "0HL6RCR8F3VND" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[8]
      Connection id "0HL6RCR8F3VND" sent FIN with status "0".
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HL6RCR8F3VND" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[8]
      Connection id "0HL6RCR8F3VNB" sent FIN with status "0".
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HL6RCR8F3VNB" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[16]
      Some connections failed to close gracefully during server shutdown.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL6RCR8F3VN9" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL6RCR8F3VNA" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL6RCR8F3VNC" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[21]
      Some connections failed to abort during server shutdown.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvWriteReq.UvWriteCb(IntPtr ptr, Int32 status)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvWriteReq.<>c.<.cctor>b__19_0(IntPtr ptr, Int32 status)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.run(UvLoopHandle handle, Int32 mode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.ThreadStart(Object parameter)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.<StopAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<StopAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StopAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StopAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at RestApi.Program.Main(String[] args) in C:\Projects**********************************

Any idea how to fix it?

I am new to Kestrel but [0] in Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[0] gave me idea that something wrong with thread handling in the server.

**Comment by Eilon** [comment]
@halter73 - please take a look. Others - please discuss with me directly.

**Comment by halter73** [comment]
Hi @romans01, can you please email me at the email address listed on my GitHub profile? We might want to keep some of the details of this issue private until we get a fix.

I mostly interested in whether you can provide me with the source for your app or a similar app that fails in the same way. It would also be good to know how frequent this kind of crash is, if you can reproduce it reliably, and whether it only happens after you start shutting down the server.

If you can, please email these details instead of putting it in the GitHub issue for now.

**Comment by muratg** [comment]
No repro. Closing this one. Please ping us/file another one if you're still seeing problems.
