### ISSUE TITLE
[Patch 1.1.3] Flaky test ListenerPrimaryTests.NonListenerPipeConnectionsAreLoggedAndIgnored

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KestrelHttpServer#2055]
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNetCore.Server.KestrelTests.ListenerPrimaryTests.<NonListenerPipeConnectionsAreLoggedAndIgnored>d__1.MoveNext() in C:\b\w\d6337ac2abf63a4b\.repositories\KestrelHttpServer\test\Microsoft.AspNetCore.Server.KestrelTests\ListenerPrimaryTests.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

We could fix this in the next patch seeing that we're nearly done with this one.

**Comment by pranavkm** [comment]
cc @muratg

**Comment by muratg** [comment]
@halter73 Could you take a look please? (Hopefully it's just test flakiness.)
