### ISSUE TITLE
HTTP/2: log errors for HTTP/2 connection errors

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#2080]
Currently we only send GOAWAY frames with the proper error code, but there's no user-visible message about what went wrong except that an `Http2ConnectionErrorException` was thrown. We should log more specific information about each error (and consider putting a message in the frame's payload as well, since the spec allows that).

**Comment by JunTaoLuo** [comment]
Actually I think this is already done in https://github.com/aspnet/KestrelHttpServer/commit/deed6c9780964bf5ec96ed6a77bedd1bd4e6d239. For example, when I trigger an connection exception, I see the following logs:
```
Connection id "0HLF7GERT8DSP": HTTP/2 connection error.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): The client sent trailers containing one or more pseudo-header fields.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ValidateHeader(Span`1 name, Span`1 value) in C:\gh\KestrelHttpServer\src\Kestrel.Core\Internal\Http2\Http2Connection.cs:line 828
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.OnHeader(Span`1 name, Span`1 value) in C:\gh\KestrelHttpServer\src\Kestrel.Core\Internal\Http2\Http2Connection.cs:line 817
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.OnIndexedHeaderField(Int32 index, IHttpHeadersHandler handler) in C:\gh\KestrelHttpServer\src\Kestrel.Core\Internal\Http2\HPack\HPackDecoder.cs:line 333
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.OnByte(Byte b, IHttpHeadersHandler handler) in C:\gh\KestrelHttpServer\src\Kestrel.Core\Internal\Http2\HPack\HPackDecoder.cs:line 135
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.Decode(Span`1 data, Boolean endHeaders, IHttpHeadersHandler handler) in C:\gh\KestrelHttpServer\src\Kestrel.Core\Internal\Http2\HPack\HPackDecoder.cs:line 115
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.DecodeHeadersAsync[TContext](IHttpApplication`1 application, Boolean endHeaders, Span`1 payload) in C:\gh\KestrelHttpServer\src\Kestrel.Core\Internal\Http2\Http2Connection.cs:line 719
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessHeadersFrameAsync[TContext](IHttpApplication`1 application) in C:\gh\KestrelHttpServer\src\Kestrel.Core\Internal\Http2\Http2Connection.cs:line 473
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in C:\gh\KestrelHttpServer\src\Kestrel.Core\Internal\Http2\Http2Connection.cs:line 147
```
The logging available for these exceptions look sufficient.
