### ISSUE TITLE
Connection processing ending abnormally - Cursor is out of bounds

### ISSUE THREAD

**Issue by bradmarder** [aspnet/KestrelHttpServer#2138]
Using microsoft azure and Kestrel 2.1.0-preview1-27377

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally.
System.InvalidOperationException: Cursor is out of bounds
   at System.IO.Pipelines.ReadCursor.ThrowOutOfBoundsException()
   at System.IO.Pipelines.ReadableBuffer.Slice(ReadCursor start, ReadCursor end)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.<ParseRequestAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__186.MoveNext()
info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
      Connection id "0HL8SQGDSL981" communication error.
Microsoft.AspNetCore.Protocols.ConnectionAbortedException: The connection was aborted
```

I've also been getting other "random" errors I can't make sense of.

```
nfo: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://127.0.0.1:6480/iisintegration  0
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.0661ms 202 
info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
      Connection id "0HL8SJKHG7VHR" communication error.
Microsoft.AspNetCore.Protocols.ConnectionAbortedException: The connection was aborted
Application is shutting down..
```

And this one about malformed headers... even though subsequent requests with the exact same headers work fine.

```
info: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HL8SJKHG7VE7" bad request data: "Malformed request: invalid headers."
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Malformed request: invalid headers.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.<ParseRequestAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__186.MoveNext()
info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
      Connection id "0HL8SJKHG7VE7" communication error.
Microsoft.AspNetCore.Protocols.ConnectionAbortedException: The connection was aborted
```

**Comment by halter73** [comment]
Thank you. It's awesome to have people trying out the nightlies and reporting bugs.

I think you've run into dotnet/corefxlab#1855. While the change has been fixed, we still need to update the Kestrel dependency. We'll close #2116 once the dependency is updated, and the issue is fully fixed.
