### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request timed out.

### ISSUE THREAD

**Issue by timminata** [aspnet/KestrelHttpServer#2143]
Hi,
We are currently getting a 500 from Kestrel on our net core 2.0 application when a client tries to upload a file and the connection between client and server is terminated (by the client) prematurely. Is this the expected behaviour? Is there a way to prevent it from coming up as a 500 since it is affecting our telemetry/uptime stats. From what I understand it is failing since Kestrel negotiates the file upload (we are using IFormFile) and since the client is disconnecting while the transfer is in progress, it is throwing an error before we hit our controller.

Thanks for any info, I have looked at manually streaming the file (https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads) but was wondering if it was necessary to go down this route or if I can rather just handle the Kestrel error myself.
Thanks

**Comment by timminata** [comment]
This is the full error:
```
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request timed out.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.ReadableBufferAwaitable.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<ConsumeAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

**Comment by Tratcher** [comment]
MVC is the one reading the IFormFile, not Kestrel.  If the upload is substantial then I would recommend the more hands on approach.

It's interesting the client disconnect was reported as a timeout, that implies the connection was kept alive by some intermediary. Are there proxies or load ballancers in the system?

**Comment by timminata** [comment]
Apologies for not replying, our issue was that we were using the Developer Exception Page which was elevating the timeout from a 408 to a 500 (and the timeout was due to poor connectivity client side). Will mark as closed, you can remove if necessary since it was unrelated. Thanks!
