### ISSUE TITLE
h2spec failures

### ISSUE THREAD

**Issue by anurse** [aspnet/KestrelHttpServer#2154]
After running [h2spec](https://github.com/summerwind/h2spec) on Kestrel's HTTP/2 implementation, I encountered the following failures. This issue tracks fixing those failures and then enabling automated h2spec testing:

```
  * http2/6.5.3 Sends multiple values of SETTINGS_INITIAL_WINDOW_SIZE (duration: 0.01s)
    DATA Frame (length:1, flags:0x00, stream_id:1)
    DATA Frame (length:12, flags:0x00, stream_id:1)
  * http2/6.9.1 Sends SETTINGS frame to set the initial window size to 1 and sends HEADERS frame (duration: 0.01s)
    DATA Frame (length:1, flags:0x00, stream_id:1)
    DATA Frame (length:12, flags:0x00, stream_id:1)
  * http2/6.9.1 Sends multiple WINDOW_UPDATE frames increasing the flow control window to above 2^31-1 (duration: 2.00s)
    GOAWAY Frame (Error Code: FLOW_CONTROL_ERROR)
    SETTINGS Frame (length:0, flags:0x01, stream_id:0)
  * http2/6.9.1 Sends multiple WINDOW_UPDATE frames increasing the flow control window to above 2^31-1 on a stream (duration: 2.00s)
    RST_STREAM Frame (Error Code: FLOW_CONTROL_ERROR)
    DATA Frame (length:0, flags:0x01, stream_id:1)
  * http2/6.9.2 Changes SETTINGS_INITIAL_WINDOW_SIZE after sending HEADERS frame (duration: 0.01s)
    DATA Frame (length:1, flags:0x00, stream_id:1)
    DATA Frame (length:12, flags:0x00, stream_id:1)
  * http2/6.9.2 Sends a SETTINGS frame for window size to be negative (duration: 2.01s)
    DATA Frame (length:1, flags:0x00, stream_id:1)
    Timeout
  * hpack/4.2 Sends a dynamic table size update at the end of header block (duration: 2.01s)
    GOAWAY Frame (Error Code: COMPRESSION_ERROR)
    Connection closed
    DATA Frame (length:0, flags:0x01, stream_id:1)
```

**Comment by anurse** [comment]
Also this one is flaky:

```
  * generic/3.1 Sends a DATA frame with padding (duration: 0.01s)
    HEADERS Frame (stream_id:1)
    Connection closed
```

**Comment by Tratcher** [comment]
Also http2/5.4.1/2
```
2: Sends an invalid PING frame to receive GOAWAY frame
          -> An endpoint that encounters a connection error SHOULD first send a GOAWAY frame
             Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
               Actual: Connection closed
```

**Comment by Tratcher** [comment]
Also http2/8.1.2.3/1
```
          ├ù 1: Sends a HEADERS frame with empty ":path" pseudo-header field
            -> The endpoint MUST respond with a stream error of type PROTOCOL_ERROR.
               Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                         RST_STREAM Frame (Error Code: PROTOCOL_ERROR)
                         Connection closed
                 Actual: DATA Frame (length:0, flags:0x01, stream_id:1)
```

**Comment by Tratcher** [comment]
I realized several of the H2spec tests don't expect an immediate response (e.g. Hello World), they want you to consume the request body first, or at least echo it. Otherwise there are a number of race conditions you could hit like on http2/8.1.2.6/1.

**Comment by Tratcher** [comment]
http2/5.1/8
```
| [15.286s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.H2SpecTests Debug: Hypertext Transfer Protocol Version 2 (HTTP/2)
  5. Streams and Multiplexing
    5.1. Stream States
        8: closed: Sends a DATA frame after sending RST_STREAM frame
      ├ù 8: closed: Sends a DATA frame after sending RST_STREAM frame
        -> The endpoint MUST treat this as a stream error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: SETTINGS Frame (length:0, flags:0x01, stream_id:0)

Failures: 

Hypertext Transfer Protocol Version 2 (HTTP/2)
  5. Streams and Multiplexing
    5.1. Stream States
      ├ù 8: closed: Sends a DATA frame after sending RST_STREAM frame
        -> The endpoint MUST treat this as a stream error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: SETTINGS Frame (length:0, flags:0x01, stream_id:0)

Finished in 15.0066 seconds
1 tests, 0 passed, 0 skipped, 1 failed
```

**Comment by Tratcher** [comment]
2 Tests remaining: "hpack/4.2/1", "http2/5.1/8"

hpack/4.2/1:
```
Test Name:	RunIndividualTestCase(testCase: hpack/4.2/1, HTTPS:False, Sends a dynamic table size update at the end of header block)
Test Outcome:	Failed
Result Message:	System.Exception : Test failed: hpack/4.2; 4.2. Maximum Table Size
Result StandardOutput:	
| [0.001s] TestLifetime Information: Starting test RunIndividualTestCase-hpack/4.2/1, HTTPS:False, Sends a dynamic table size update at the end of header block at 2018-08-10T18:26:23
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests
| [0.056s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFUTQNGA7LA" started.
| [0.057s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7LA" sending SETTINGS frame for stream ID 0 with length 0 and flags NONE
| [0.057s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7LA" received SETTINGS frame for stream ID 0 with length 6 and flags NONE
| [0.057s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7LA" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
| [0.057s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7LA" received SETTINGS frame for stream ID 0 with length 0 and flags ACK
| [0.057s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7LA" received HEADERS frame for stream ID 1 with length 16 and flags END_STREAM, END_HEADERS
| [0.057s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/2 GET http://127.0.0.1:2639/  
| [0.057s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7LA" sending HEADERS frame for stream ID 1 with length 53 and flags END_HEADERS
| [0.058s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7LA" sending DATA frame for stream ID 1 with length 11 and flags NONE
| [0.058s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7LA" sending DATA frame for stream ID 1 with length 0 and flags END_STREAM
| [0.058s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.3859ms 200 
| [15.059s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLFUTQNGA7LA" received FIN.
| [15.059s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7LA" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0
| [15.059s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFUTQNGA7LA" is closed. The last processed stream ID was 1.
| [15.060s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLFUTQNGA7LA" sending FIN.
| [15.060s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFUTQNGA7LA" stopped.
| [15.077s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.H2SpecTests Debug: HPACK: Header Compression for HTTP/2
  4. Dynamic Table Management
    4.2. Maximum Table Size
        1: Sends a dynamic table size update at the end of header block
      ├ù 1: Sends a dynamic table size update at the end of header block
        -> The endpoint MUST treat this as a decoding error.
           Expected: GOAWAY Frame (Error Code: COMPRESSION_ERROR)
                     Connection closed
             Actual: DATA Frame (length:0, flags:0x01, stream_id:1)

Failures: 

HPACK: Header Compression for HTTP/2
  4. Dynamic Table Management
    4.2. Maximum Table Size
      ├ù 1: Sends a dynamic table size update at the end of header block
        -> The endpoint MUST treat this as a decoding error.
           Expected: GOAWAY Frame (Error Code: COMPRESSION_ERROR)
                     Connection closed
             Actual: DATA Frame (length:0, flags:0x01, stream_id:1)

Finished in 15.0050 seconds
1 tests, 0 passed, 0 skipped, 1 failed

| [15.080s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [15.082s] TestLifetime Information: Finished test RunIndividualTestCase-hpack/4.2/1, HTTPS:False, Sends a dynamic table size update at the end of header block in 15.0806218s
```

http2/5.1/8:
```
Test Name:	RunIndividualTestCase(testCase: http2/5.1/8, HTTPS:False, closed: Sends a DATA frame after sending RST_STREAM frame)
Test Outcome:	Failed
Result Message:	System.Exception : Test failed: http2/5.1; 5.1. Stream States
Result StandardOutput:	
| [0.001s] TestLifetime Information: Starting test RunIndividualTestCase-http2/5.1/8, HTTPS:False, closed: Sends a DATA frame after sending RST_STREAM frame at 2018-08-10T18:25:49
| [0.001s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests
| [0.068s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFUTQNGA7K8" started.
| [0.069s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7K8" sending SETTINGS frame for stream ID 0 with length 0 and flags NONE
| [0.069s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7K8" received SETTINGS frame for stream ID 0 with length 6 and flags NONE
| [0.070s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7K8" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
| [0.070s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7K8" received SETTINGS frame for stream ID 0 with length 0 and flags ACK
| [0.070s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7K8" received HEADERS frame for stream ID 1 with length 15 and flags END_HEADERS
| [0.070s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7K8" received RST_STREAM frame for stream ID 1 with length 4 and flags 0x0
| [0.070s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/2 GET http://127.0.0.1:2555/  
| [0.070s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7K8" received DATA frame for stream ID 1 with length 4 and flags END_STREAM
| [0.070s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLFUTQNGA7K8", Request id "0HLFUTQNGA7K8:00000001": An unhandled exception was thrown by the application.
| Microsoft.AspNetCore.Connections.ConnectionAbortedException: The client reset the request stream.
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ValidateState(CancellationToken cancellationToken) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Core\Internal\Http\HttpRequestStream.cs:line 210
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Core\Internal\Http\HttpRequestStream.cs:line 148
|    at System.IO.Stream.CopyToAsync(Stream destination)
|    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.H2SpecTests.<>c.<<ConfigureHelloWorld>b__4_0>d.MoveNext() in D:\github\AspNet\KestrelHttpServer\test\Kestrel.Transport.FunctionalTests\Http2\H2SpecTests.cs:line 128
| --- End of stack trace from previous location where exception was thrown ---
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Core\Internal\Http\HttpProtocol.cs:line 552
| [0.072s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.3826ms 0 
| [15.070s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLFUTQNGA7K8" received FIN.
| [15.071s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLFUTQNGA7K8" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0
| [15.071s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFUTQNGA7K8" is closed. The last processed stream ID was 1.
| [15.071s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLFUTQNGA7K8" sending FIN.
| [15.072s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFUTQNGA7K8" stopped.
| [15.089s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.H2SpecTests Debug: Hypertext Transfer Protocol Version 2 (HTTP/2)
  5. Streams and Multiplexing
    5.1. Stream States
        8: closed: Sends a DATA frame after sending RST_STREAM frame
      ├ù 8: closed: Sends a DATA frame after sending RST_STREAM frame
        -> The endpoint MUST treat this as a stream error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: Timeout

Failures: 

Hypertext Transfer Protocol Version 2 (HTTP/2)
  5. Streams and Multiplexing
    5.1. Stream States
      ├ù 8: closed: Sends a DATA frame after sending RST_STREAM frame
        -> The endpoint MUST treat this as a stream error of type STREAM_CLOSED.
           Expected: GOAWAY Frame (Error Code: STREAM_CLOSED)
                     RST_STREAM Frame (Error Code: STREAM_CLOSED)
                     Connection closed
             Actual: Timeout

Finished in 15.0050 seconds
1 tests, 0 passed, 0 skipped, 1 failed

| [15.092s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [15.094s] TestLifetime Information: Finished test RunIndividualTestCase-http2/5.1/8, HTTPS:False, closed: Sends a DATA frame after sending RST_STREAM frame in 15.093576s
```

**Comment by Tratcher** [comment]
@JunTaoLuo please take a look at hpack/4.2/1

**Comment by JunTaoLuo** [comment]
http2/5.1/8 depends on https://github.com/aspnet/KestrelHttpServer/issues/2832
