### ISSUE TITLE
Specifying RuntimeFrameworkVersion cause an exception in VS 2017

### ISSUE THREAD

**Issue by Pilchie** [aspnet/KestrelHttpServer#2183]
_From @xakep139 on November 19, 2017 7:20_

### Steps to reproduce
Simply create new ASP.NET Core app with `dotnet new web`, include `RuntimeFrameworkVersion` and replace `Microsoft.AspNetCore.All` (2.0.3) with `Microsoft.AspNetCore` (2.0.1):
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.1" />
  </ItemGroup>

</Project>
```

Running this project with Visual Studio I got an exception:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.Internal.HostingEnvironmentExtensions.Initialize(IHostingEnvironment hostingEnvironment, String applicationName, String contentRootPath, WebHostOptions options)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at test.Program.BuildWebHost(String[] args)
   at test.Program.Main(String[] args)
```
Removing `RuntimeFrameworkVersion` section from .csproj fixes the problem.
I don't have such problem with JetBrains Rider 2017.2.1 or with simple `dotnet run`.

### System configuration
Visual Studio Professional 2017 Version 15.4.4.

`dotnet --info` output:
```
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

_Copied from original issue: dotnet/project-system#2975_

**Comment by Pilchie** [comment]
@BillHiebert - Do you know where this should go?

**Comment by Pilchie** [comment]
Ping @BillHiebert?

**Comment by Pilchie** [comment]
_From @BillHiebert on November 27, 2017 19:9_

@Pilchie - I would move it to https://github.com/aspnet/KestrelHttpServer since it could be hosting related.  Not sure why this only reproduces in VS since it basically just uses donet.exe to run the app.

**Comment by davidfowl** [comment]
@JunTaoLuo can you move this issue to the appropriate repository?

**Comment by JunTaoLuo** [comment]
This issue was moved to aspnet/Universe#693
