### ISSUE TITLE
Flaky test: HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2197]
http://aspnetci/viewLog.html?buildId=360375&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId4971464264492862489

```
Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate>d__66.MoveNext() in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\test\Kestrel.FunctionalTests\ResponseTests.cs:line 2611
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
```

It would be nice if we could add descriptive error messages to Assert.Trues going forward too.

**Comment by ryanbrandenburg** [comment]
I thinks [this](http://aspnetci/viewLog.html?buildId=370080&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId8801805959029034956) failure is related.

**Comment by JunTaoLuo** [comment]
I went through the test history and I don't see this test failure mode. The only times that this test failed were recorded in http://aspnetci/project.html?tab=testDetails&projectId=XPlat&testNameId=-6045451249543164306. However, these test failures were cause by other issues such as auth so I'm going to close this as no repro until we see this failure again.

**Comment by mikeharder** [comment]
Reopening since test failed on Mac Jenkins:

```
15:35:04   Starting test group: Libuv.FunctionalTests/netcoreapp2.2

15:38:17   [xUnit.net 00:03:15.2244390]     HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate [FAIL]
15:38:17   Failed   HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate
15:38:17    System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
15:38:17   Stack Trace:
15:38:17      at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
15:38:17      at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
15:38:17   --- End of stack trace from previous location where exception was thrown ---
15:38:17      at System.Net.Security.SslState.ThrowIfExceptional()
15:38:17      at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
15:38:17      at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
15:38:17      at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
15:38:17      at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
15:38:17      at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
15:38:17   --- End of stack trace from previous location where exception was thrown ---
15:38:17      at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate() in /_/test/Kestrel.FunctionalTests/ResponseTests.cs:line 2970
15:38:17   --- End of stack trace from previous location where exception was thrown ---
```

https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/dev/job/osx-Configuration_Debug_prtest/131/console
