### ISSUE TITLE
Error on production server. Website is dead

### ISSUE THREAD

**Issue by pantonis** [aspnet/KestrelHttpServer#2199]
Suddenly one of our production enterprise apps stopped working. I restarted AppPool, IIS and VPS but still the site is dead. Does not come back.

I checked the Windows Event log error and I see the following error:

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean ByRef)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(System.Runtime.InteropServices.SafeHandle, Boolean ByRef)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv+NativeMethods.uv_async_send(Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvAsyncHandle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvAsyncHandle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.PostCloseHandle(System.Action`1<IntPtr>, IntPtr)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvHandle.ReleaseHandle()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```

**Comment by davidfowl** [comment]
@pantonis What version of Kestrel? It also seems like you're using .NET Framework. Is that right?

**Comment by pantonis** [comment]
@davidfowl Thanks for your reply

Yes it is strange and I am running .NET Framework. 

Since it was a prod environment I reverted to an old snapshot of VPS it fixed the problem. Didn't have time to investigate further. 

Kestrel Version is 1.1.2

**Comment by pantonis** [comment]
Will close this issue and re-open it if this happens again and will collect some data next time.

Thanks
