### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake.

### ISSUE THREAD

**Issue by NPSF3000** [aspnet/KestrelHttpServer#2200]
**Background:**  

We've built and deployed a web-socket application in production, however it's been incredibly unstable even with a relatively small number of connections (~4000).  Typical symptoms is dropping all connections and becoming completely unresponsive every few hours.  Investigating.

**Test:**

Simple Echo code, echoing a ~8MB text message per second per connection.  A small number of connections are added.  Client and Server exist in same VM, both running from VS.  8 Cores, 30GB of RAM.  Win 10 Pro 10.0.16299

**Result:**

Clients quickly start being disconnected.  Server error as follows:

```
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ReadInt32(Byte[] value, Int32 startIndex)
   at System.Net.WebSockets.ManagedWebSocket.TryParseMessageHeaderFromReceiveBuffer(MessageHeader& resultHeader)
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
...
```

**Comment by davidfowl** [comment]
@NPSF3000 Can you share the code for your websocket server?

/cc @stephentoub

**Comment by NPSF3000** [comment]
The server is pretty basic:

```
    public class EchoConn
    {
        WebSocket websocket;
        public EchoConn(WebSocket websocket)
        {
            this.websocket = websocket;
        }
        public async Task Run()
        {
            while (websocket.State == WebSocketState.Open)
            {
                var bigBuffer = new List<byte>();
                WebSocketReceiveResult received;
                do
                {
                    var buffer = new ArraySegment<byte>(new byte[1024*1024]);
                    received = await websocket.ReceiveAsync(buffer, CancellationToken.None);
                    bigBuffer.AddRange(buffer.Take(received.Count));
                    if (bigBuffer.Count > 1024 * 1024 * 16) throw new Exception("Message too large!");
                } while (!received.EndOfMessage);
                
                switch (received.MessageType)
                {
                    case WebSocketMessageType.Text:
                        await websocket.SendAsync(new ArraySegment<byte>(bigBuffer.ToArray()), messageType: WebSocketMessageType.Text, endOfMessage: true, cancellationToken: CancellationToken.None);
                        break;
                    case WebSocketMessageType.Close: break;
                    default: throw new Exception($"Unhandled Websocket MessageType {received.MessageType}!");
                }
            }
        }
    }
```

```
            app.Use(async (context, next) =>
            {
                //Handle non web-socket requests.
                if (context.Request.Path != "/ws/echo/v1")
                {
                    await next();
                    return;
                }

                //Handle invalid protocol.
                if (!context.WebSockets.IsWebSocketRequest)
                {
                    context.Response.StatusCode = 400;
                    return;
                }

                var remoteIp = context.GetRequestIP();
                LogTo.Information("{remoteIp} connected to {url}", remoteIp, context.Request.Path);

                WebSocket websocket = await context.WebSockets.AcceptWebSocketAsync();
                await new EchoConn(websocket).Run();
            });
```

**Comment by davidfowl** [comment]
That logic doesn’t look right. You’re supposed to handle the close message by sending a close back to the client.

**Comment by NPSF3000** [comment]
@davidfowl I'll make that change to my system.  Either way, it doesn't explain why perfectly solid connections (with no closes going on at all) are being dropped.

**Comment by NPSF3000** [comment]
As per my recent comments we now have close logic built:

Server:
```
public async Task Run()
{
    while (websocket.State == WebSocketState.Open)
    {
        var bigBuffer = new List<byte>();
        WebSocketReceiveResult received;
        do
        {
            var buffer = new ArraySegment<byte>(new byte[1024 * 1024]);
            received = await websocket.ReceiveAsync(buffer, CancellationToken.None);
            bigBuffer.AddRange(buffer.Take(received.Count));
            //if (bigBuffer.Count > 1024 * 1024 * 16) throw new Exception("Message too large!");
        } while (!received.EndOfMessage);

        switch (received.MessageType)
        {
            case WebSocketMessageType.Text:
                await websocket.SendAsync(new ArraySegment<byte>(bigBuffer.ToArray()), messageType: WebSocketMessageType.Text, endOfMessage: true, cancellationToken: CancellationToken.None);
                break;
            case WebSocketMessageType.Close:
                await websocket.CloseAsync(WebSocketCloseStatus.NormalClosure, "Close received, closing", CancellationToken.None);
                break;

            default: throw new Exception($"Unhandled Websocket MessageType {received.MessageType}!");
        }
    }
}
```

Client:

```
var jo = new JObject();
jo["Type"] = "Echo";
jo["Payload"] = new string(Enumerable.Repeat('a', 4 * 1024 * 1024).ToArray());
byte[] payload = Encoding.UTF8.GetBytes(jo.ToString());
...
 while (socket.State == WebSocketState.Open)
 {
    // await Task.Delay(rnd.Next(1000, 1000));
     var prob = rnd.NextDouble();
     await Send(payload);
 }
...
protected async Task Receive()
{
    while (socket.State == WebSocketState.Open)
    {
        try
        {
            var bigBuffer = new List<byte>();
            WebSocketReceiveResult received;
            do
            {
                var buffer = new ArraySegment<byte>(new byte[1024 * 1024]);
                received = await socket.ReceiveAsync(buffer, CancellationToken.None);
                bigBuffer.AddRange(buffer.Take(received.Count));
                //if (bigBuffer.Count > 1024 * 1024 * 16) throw new Exception("Message too large!");
            } while (!received.EndOfMessage);


            string recievedText;
            switch (received.MessageType)
            {
                case WebSocketMessageType.Text:
                    recievedText = Encoding.UTF8.GetString(bigBuffer.ToArray(), 0, bigBuffer.Count);
                    break;
                case WebSocketMessageType.Close:
                    await socket.CloseAsync(WebSocketCloseStatus.NormalClosure, "Close received, closing", CancellationToken.None);
                    Console.WriteLine("Close Message Recieved");
                    continue;
                default: throw new Exception($"Unhandled MessageType: {received.MessageType}!");
            }

            // Console.WriteLine($"Received Message: {recievedText}");

            var jObject = JObject.Parse(recievedText);
            Console.WriteLine(Name + " recieved " + jObject["Type"]);
        }
        catch (Exception e)
        {
            Console.WriteLine(Name + " had error handling recieve! " + e);
        }
    }
}
```

However, even a single open connection simply echoing a message is highly unstable.  For example:

Server:

```System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.<CloseWithReceiveErrorAndThrowAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Client:

```
System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.Http.WinHttpException (0x80072EE2): The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by davidfowl** [comment]
Is the client dying first?

**Comment by litszh** [comment]
Meet the same issue.
Opened an issue here
https://github.com/dotnet/corefx/issues/30375

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
