### ISSUE TITLE
Flaky test with https connection adapter on netcoreapp2.1

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2204]
This seems to happen sometimes.

```
[xUnit.net 00:00:11.0117324]     LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter [FAIL]
[xUnit.net 00:00:11.0136737]       System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
[xUnit.net 00:00:11.0221650]       Stack Trace:
[xUnit.net 00:00:11.0246083]            at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
[xUnit.net 00:00:11.0254635]            at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
[xUnit.net 00:00:11.0262545]            at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
[xUnit.net 00:00:11.0269883]            at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
[xUnit.net 00:00:11.0276394]            at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
[xUnit.net 00:00:11.0282423]            at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
[xUnit.net 00:00:11.0289708]            at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
[xUnit.net 00:00:11.0299736]            at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
[xUnit.net 00:00:11.0310319]            at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__43_1(String arg1, X509CertificateCollection arg2, SslProtocols arg3, AsyncCallback callback, Object state)
[xUnit.net 00:00:11.0319608]            at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
[xUnit.net 00:00:11.0327557]            at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
[xUnit.net 00:00:11.0335382]            at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
[xUnit.net 00:00:11.0343717]            at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStream>d__6.MoveNext()
[xUnit.net 00:00:11.0350481]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0356950]            at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__1.MoveNext()
[xUnit.net 00:00:11.0363280]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0369080]            at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__0.MoveNext()
[xUnit.net 00:00:11.0376952]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0385458]            at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
[xUnit.net 00:00:11.0391374]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0398812]         /home/travis/build/aspnet/KestrelHttpServer/test/Kestrel.FunctionalTests/LoggingConnectionAdapterTests.cs(58,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.LoggingConnectionAdapterTests.<LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter>d__2.MoveNext()
[xUnit.net 00:00:11.0427785]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0436328]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0441748]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:11.0461548]       Output:
[xUnit.net 00:00:11.0469409]         | Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
[xUnit.net 00:00:11.0504471]         | Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
[xUnit.net 00:00:11.0511750]         | Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.FunctionalTests
[xUnit.net 00:00:11.0519317]         | Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HL9QRIKNPLUF" started.
```

**Comment by halter73** [comment]
Yes. I was able to reproduce this once yesterday. Unfortunately, currently there are other test failures that are far more frequent.

**Comment by natemcmaster** [comment]
Failed again in release/2.1: https://travis-ci.org/aspnet/KestrelHttpServer/jobs/339566950#L1328

**Comment by ryanbrandenburg** [comment]
I'm starting to track this in [this](http://aspnetci/httpAuth/app/rest/builds?locator=tag:StreamClosed,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)) list.

**Comment by ryanbrandenburg** [comment]
This still [fails](http://aspnetci/viewLog.html?buildId=469291&buildTypeId=Releases_21Public_UbuntuUniverse).

**Comment by halter73** [comment]
@ryanbrandenburg I don't see LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter as a failed test. I assume that your grouping all "Authentication failed" errors from SslStream together? If so, that sounds reasonable to me.

@muratg @Tratcher This "System.IO.IOException : Authentication failed because the remote party has closed the transport stream" is how [this bug](https://github.com/dotnet/corefx/issues/29746) which I reported to corefx yesterday surfaces itself. My current theory is it might be triggered by us hitting a file descriptor limit due to the new file logging not cleaning up properly, but there are some other theories as well if you follow that thread and the thread [for a similar (possibly the same) bug](https://github.com/dotnet/corefx/issues/28819) I filed last month.

The proximate cause of these errors are SslStream not being able to open certificate files on Linux.

**Comment by ryanbrandenburg** [comment]
Yes, that's what I mean. I figure nobody wants me creating tons of issues that are identical except a test name 😄.

**Comment by mikeharder** [comment]
Another repro on Mac Jenkins:

```
15:35:04   Starting test group: Libuv.FunctionalTests/netcoreapp2.2

15:38:17   [xUnit.net 00:03:15.2244390]     HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate [FAIL]
15:38:17   Failed   HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate
15:38:17    System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
15:38:17   Stack Trace:
15:38:17      at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
15:38:17      at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
15:38:17   --- End of stack trace from previous location where exception was thrown ---
15:38:17      at System.Net.Security.SslState.ThrowIfExceptional()
15:38:17      at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
15:38:17      at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
15:38:17      at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
15:38:17      at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
15:38:17      at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
15:38:17   --- End of stack trace from previous location where exception was thrown ---
15:38:17      at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate() in /_/test/Kestrel.FunctionalTests/ResponseTests.cs:line 2970
15:38:17   --- End of stack trace from previous location where exception was thrown ---
```

https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/dev/job/osx-Configuration_Debug_prtest/131/console

**Comment by JunTaoLuo** [comment]
Dup of https://github.com/aspnet/KestrelHttpServer/issues/2748.
