### ISSUE TITLE
ConnectionResetException -4077 ECONNRESET connection reset by peer

### ISSUE THREAD

**Issue by NVentimiglia** [aspnet/KestrelHttpServer#2236]
I see a number of related issues. These issues are closed with the understanding that this is the normal behavior when a connection dies. I am opening this issue because this exception is killing my web server. Please advise how I can catch and handle this exception.

### Stack Trace

```
Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ConnectionResetException occurred
  HResult=0x80131620
  Message=Error -4077 ECONNRESET connection reset by peer
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.ReadableBufferAwaitable.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<ReadAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.<ReadAsyncInternal>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<EnsureDataAvailableOrReadAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<ReadNextFrameAsync>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<ReceiveAsync>d__36.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foundation.Net.Transports.WSHostConnection.<UpdateAsync>d__7.MoveNext() in F:\Projects\Foundation\Foundation.Core\Foundation.Net\Transports\WSHostConnection.cs:line 46
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<EnsureDataAvailableOrReadAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<ReadNextFrameAsync>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<ReceiveAsync>d__36.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<CloseAsync>d__41.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foundation.Net.Transports.WSHostConnection.<DisconnectInternal>d__8.MoveNext() in F:\Projects\Foundation\Foundation.Core\Foundation.Net\Transports\WSHostConnection.cs:line 81
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Inner Exception 1:
UvException: Error -4077 ECONNRESET connection reset by peer
```

## My Code

```

public async Task UpdateAsync()
        {
            try
            {
                while (Socket != null && Socket.State == WebSocketState.Open)
                {
                    ReadSerializer.Reset();
                    ReadSerializer.IsWriting = false;

                    var segment = new ArraySegment<byte>(ReadSerializer.Data);

                    //Stack Trace points to this line
                    var received = await Socket.ReceiveAsync(segment, CancellationToken.None);

                    if (!received.EndOfMessage)
                        continue;

                    if (Socket == null || Socket.State != WebSocketState.Open)
                        return;

                    if (received.MessageType == WebSocketMessageType.Binary)
                    {
                        RaiseMessage(ReadSerializer);
                    }
                    else if (received.MessageType == WebSocketMessageType.Close)
                    {
#if VERBOSE
                        Logger.Info("Received Closed " + ConnectionId);
#endif
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.Exception(ex);
            }
        }
```
Notice that I am catching the exception, what else can I do ?

Microsoft.AspNetCore 2.01
Microsoft.AspNetCore.Http.Abstractions 2.01
Microsoft.AspNetCore.Websockets.Server 0.1.0

**Comment by Tratcher** [comment]
> killing my web server

Can you clarify? Is the process shutting down due to an unhandled exception?

Note `Microsoft.AspNetCore.Websockets.Server 0.1.0` is obsolete, you can remove it.

**Comment by NVentimiglia** [comment]
@Tratcher yes, server is shutting down

**Comment by Tratcher** [comment]
Start by moving from Microsoft.AspNetCore.WebSockets.Server 0.1 to Microsoft.AspNetCore.WebSockets 2.0.

**Comment by NVentimiglia** [comment]
@Tratcher That did it, thanks.
