### ISSUE TITLE
MemoryPool2 OverflowException on x64

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#227]
CLR or CoreCLR. Happens on the first request. All Kestrel x64 tests in ServerTests are failing.
@lodejard @halter73 
error   : [Microsoft.AspNet.Server.Kestrel] UvAllocCb
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at Microsoft.AspNet.Server.Kestrel.Infrastructure.MemoryPool2.AllocateSlab() in C:\git\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Infrastructure\MemoryPool2.cs:line 100
   at Microsoft.AspNet.Server.Kestrel.Infrastructure.MemoryPool2.Lease(Int32 minimumSize) in C:\git\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Infrastructure\MemoryPool2.cs:line 86
   at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.IncomingStart(Int32 minimumSize) in C:\git\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\SocketInput.cs:line 76
   at Microsoft.AspNet.Server.Kestrel.Http.Connection.OnAlloc(UvStreamHandle handle, Int32 suggestedSize) in C:\git\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\Connection.cs:line 53
   at Microsoft.AspNet.Server.Kestrel.Http.Connection.AllocCallback(UvStreamHandle handle, Int32 suggestedSize, Object state) in C:\git\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\Connection.cs:line 48
   at Microsoft.AspNet.Server.Kestrel.Networking.UvStreamHandle.UvAllocCb(IntPtr handle, Int32 suggested_size, uv_buf_t& buf) in C:\git\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Networking\UvStreamHandle.cs:line 146

**Comment by davidfowl** [comment]
Nice! I found this one last night
