### ISSUE TITLE
Flaky test in 2.1: DoesNotRejectBodylessGetRequestWithZeroMaxRequestBodySize

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#2307]
Failure: https://travis-ci.org/aspnet/KestrelHttpServer/jobs/339539942#L949
```
[xUnit.net 00:00:13.6888179]     DoesNotRejectBodylessGetRequestWithZeroMaxRequestBodySize [FAIL]
[xUnit.net 00:00:13.6942699]       Assert.Equal() Failure
[xUnit.net 00:00:13.6954764]                                            ↓ (pos 75)
[xUnit.net 00:00:13.6960931]       Expected: ···ontent-Length: 0\r\n\r\nHTTP/1.1 413 Payload Too Large\r\nConnectio···
[xUnit.net 00:00:13.6966598]       Actual:   ···ontent-Length: 0\r\n\r\n
[xUnit.net 00:00:13.6977996]                                            ↑ (pos 75)
[xUnit.net 00:00:13.7009179]       Stack Trace:
[xUnit.net 00:00:13.7054926]         /_/test/shared/TestConnection.cs(147,0): at Microsoft.AspNetCore.Testing.TestConnection.<Receive>d__21.MoveNext()
[xUnit.net 00:00:13.7059497]         /_/test/shared/TestConnection.cs(162,0): at Microsoft.AspNetCore.Testing.TestConnection.<ReceiveForcedEnd>d__23.MoveNext()
[xUnit.net 00:00:13.7068429]         /_/test/Kestrel.FunctionalTests/MaxRequestBodySizeTests.cs(158,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.MaxRequestBodySizeTests.<DoesNotRejectBodylessGetRequestWithZeroMaxRequestBodySize>d__3.MoveNext()
```
cc @muratg for triage

**Comment by muratg** [comment]
Historical results: http://aspnetci/project.html?projectId=XPlat&testNameId=-8133551501687332782&tab=testDetails

**Comment by JunTaoLuo** [comment]
Haven't seen this test fail in this way since February and the test has always passed on 2.1/2.2/master. I'll close this now and if the test fails again, a new issue will be open by RaaS.
