### ISSUE TITLE
Random spike in exceptions which look to maybe be coming from kestrel

### ISSUE THREAD

**Issue by xt0rted** [aspnet/KestrelHttpServer#2320]
Last week I had an instance where app services restarted my site and it never came up for some reason. I didn't see anything in the logs for it and nothing in application insights. While just reviewing what's in application insights I noticed a massive spike in logged exceptions a day or two later but I'm not sure if it's related.

![image](https://user-images.githubusercontent.com/831974/36230381-4768499a-11a8-11e8-9584-45d555ffcd58.png)

There was just shy of 2k instances of the same exception logged over the span of about a half hour. There was also a debug snapshot taken of this exception. The stack trace that was logged is:
```
Connection processing ended abnormally.
System.ArgumentException:
   at Microsoft.ApplicationInsights.AspNetCore.Extensions.HttpRequestExtensions.GetUri (Microsoft.ApplicationInsights.AspNetCore, Version=2.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.ApplicationInsights.AspNetCore.DiagnosticListeners.HostingDiagnosticListener.EndRequest (Microsoft.ApplicationInsights.AspNetCore, Version=2.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Proxy_Method_From_<>f__AnonymousType2`1_To_Void OnHttpRequestInStop(Microsoft.AspNetCore.Http.HttpContext) (Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter+<>c__DisplayClass1_0.<Adapt>b__0 (Microsoft.Extensions.DiagnosticAdapter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write (Microsoft.Extensions.DiagnosticAdapter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext (Microsoft.Extensions.DiagnosticAdapter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Diagnostics.DiagnosticListener.Write (System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at System.Diagnostics.DiagnosticSource.StopActivity (System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.StopActivity (Microsoft.AspNetCore.Hosting, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.DisposeContext (Microsoft.AspNetCore.Hosting, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1+<ProcessRequestsAsync>d__2.MoveNext (Microsoft.AspNetCore.Server.Kestrel.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

If it'd help I can either give you the account info so you can look into the logs and grab a copy of the snapshot, or I could send a copy to someone for review. I'm not seeing anything in it that's related to application code, it's all inside asp.net core by the looks of it.

**Comment by xt0rted** [comment]
While looking through my application logs I found some more information that wasn't logged to application insights. Here's what's showing in there.

```
2018-02-10 04:26:02.601 +00:00 [Information] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLBEUE908OI7" bad request data: "Invalid request line."
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-02-10 04:26:02.605 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.0 OPTIONS http:///  
2018-02-10 04:26:02.610 +00:00 [Error] Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware: 'MS-ASPNETCORE-TOKEN' does not match the expected pairing token '98f9f98b-f0e8-43ec-8b20-3287e4954f00', request rejected.
2018-02-10 04:26:02.627 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 21.8655ms 400 
2018-02-10 04:26:02.674 +00:00 [Warning] Microsoft.AspNetCore.Server.Kestrel: Connection processing ended abnormally.
System.ArgumentException: Http request Host is not specified
   at Microsoft.ApplicationInsights.AspNetCore.Extensions.HttpRequestExtensions.GetUri(HttpRequest request)
   at Microsoft.ApplicationInsights.AspNetCore.DiagnosticListeners.HostingDiagnosticListener.EndRequest(HttpContext httpContext, Int64 timestamp)
   at Proxy_Method_From_<>f__AnonymousType2`1_To_Void OnHttpRequestInStop(Microsoft.AspNetCore.Http.HttpContext)(Object , Object , IProxyFactory )
   at Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.<>c__DisplayClass1_0.<Adapt>b__0(Object listener, Object data)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write(String diagnosticName, Object parameters)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Diagnostics.DiagnosticSource.StopActivity(Activity activity, Object args)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.StopActivity(HttpContext httpContext, Activity activity)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.DisposeContext(Context context, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-02-10 04:26:13.750 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.1 POST http://127.0.0.1:5315/sdk/vimService  450
2018-02-10 04:26:13.751 +00:00 [Error] Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware: 'MS-ASPNETCORE-TOKEN' does not match the expected pairing token '98f9f98b-f0e8-43ec-8b20-3287e4954f00', request rejected.
2018-02-10 04:26:13.903 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 152.9144ms 400 
2018-02-10 04:26:14.413 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.0 GET http:///scripts/..%c0%259v..%c0%259v..%c0%259v..%c0%259v..%c0%259v..%c0%259v..%c0%259v..%c0%259v/winnt/system32/cmd.exe?/c%20dir  
2018-02-10 04:26:14.493 +00:00 [Error] Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware: 'MS-ASPNETCORE-TOKEN' does not match the expected pairing token '98f9f98b-f0e8-43ec-8b20-3287e4954f00', request rejected.
2018-02-10 04:26:14.493 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 80.7039ms 400 
2018-02-10 04:26:14.507 +00:00 [Information] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HLBEUE908OIB" bad request data: "Invalid request target: 'HTTP://www.google.com'"
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request target: 'HTTP://www.google.com'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.ThrowRequestTargetRejected(Span`1 target)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.OnAuthorityFormTarget(HttpMethod method, Span`1 target)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.OnStartLine(HttpMethod method, HttpVersion version, Span`1 target, Span`1 path, Span`1 query, Span`1 customMethod, Boolean pathEncoded)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.ParseRequest(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-02-10 04:26:14.638 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.0 GET http:///scripts/..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af..%c0%af/winnt/system32/cmd.exe?/c%20dir  
2018-02-10 04:26:14.638 +00:00 [Error] Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware: 'MS-ASPNETCORE-TOKEN' does not match the expected pairing token '98f9f98b-f0e8-43ec-8b20-3287e4954f00', request rejected.
2018-02-10 04:26:14.638 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 0.2946ms 400 
2018-02-10 04:26:14.655 +00:00 [Warning] Microsoft.AspNetCore.Server.Kestrel: Connection processing ended abnormally.
System.ArgumentException: Http request Host is not specified
   at Microsoft.ApplicationInsights.AspNetCore.Extensions.HttpRequestExtensions.GetUri(HttpRequest request)
   at Microsoft.ApplicationInsights.AspNetCore.DiagnosticListeners.HostingDiagnosticListener.EndRequest(HttpContext httpContext, Int64 timestamp)
   at Proxy_Method_From_<>f__AnonymousType2`1_To_Void OnHttpRequestInStop(Microsoft.AspNetCore.Http.HttpContext)(Object , Object , IProxyFactory )
   at Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.<>c__DisplayClass1_0.<Adapt>b__0(Object listener, Object data)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write(String diagnosticName, Object parameters)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Diagnostics.DiagnosticSource.StopActivity(Activity activity, Object args)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.StopActivity(HttpContext httpContext, Activity activity)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.DisposeContext(Context context, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-02-10 04:26:15.394 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.0 GET http:///scripts/..%c0%25qf..%c0%25qf..%c0%25qf..%c0%25qf..%c0%25qf..%c0%25qf..%c0%25qf..%c0%25qf/winnt/system32/cmd.exe?/c%20dir  
2018-02-10 04:26:15.394 +00:00 [Error] Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware: 'MS-ASPNETCORE-TOKEN' does not match the expected pairing token '98f9f98b-f0e8-43ec-8b20-3287e4954f00', request rejected.
2018-02-10 04:26:15.475 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 81.259ms 400 
2018-02-10 04:26:15.415 +00:00 [Warning] Microsoft.AspNetCore.Server.Kestrel: Connection processing ended abnormally.
System.ArgumentException: Http request Host is not specified
   at Microsoft.ApplicationInsights.AspNetCore.Extensions.HttpRequestExtensions.GetUri(HttpRequest request)
   at Microsoft.ApplicationInsights.AspNetCore.DiagnosticListeners.HostingDiagnosticListener.EndRequest(HttpContext httpContext, Int64 timestamp)
   at Proxy_Method_From_<>f__AnonymousType2`1_To_Void OnHttpRequestInStop(Microsoft.AspNetCore.Http.HttpContext)(Object , Object , IProxyFactory )
   at Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.<>c__DisplayClass1_0.<Adapt>b__0(Object listener, Object data)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write(String diagnosticName, Object parameters)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Diagnostics.DiagnosticSource.StopActivity(Activity activity, Object args)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.StopActivity(HttpContext httpContext, Activity activity)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.DisposeContext(Context context, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-02-10 04:26:16.201 +00:00 [Warning] Microsoft.AspNetCore.Server.Kestrel: Connection processing ended abnormally.
System.ArgumentException: Http request Host is not specified
   at Microsoft.ApplicationInsights.AspNetCore.Extensions.HttpRequestExtensions.GetUri(HttpRequest request)
   at Microsoft.ApplicationInsights.AspNetCore.DiagnosticListeners.HostingDiagnosticListener.EndRequest(HttpContext httpContext, Int64 timestamp)
   at Proxy_Method_From_<>f__AnonymousType2`1_To_Void OnHttpRequestInStop(Microsoft.AspNetCore.Http.HttpContext)(Object , Object , IProxyFactory )
   at Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.<>c__DisplayClass1_0.<Adapt>b__0(Object listener, Object data)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write(String diagnosticName, Object parameters)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Diagnostics.DiagnosticSource.StopActivity(Activity activity, Object args)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.StopActivity(HttpContext httpContext, Activity activity)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.DisposeContext(Context context, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
2018-02-10 04:26:16.324 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.0 GET http:///scripts/..%c1%258s..%c1%258s..%c1%258s..%c1%258s..%c1%258s..%c1%258s..%c1%258s..%c1%258s/winnt/system32/cmd.exe?/c%20dir  
2018-02-10 04:26:16.324 +00:00 [Error] Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware: 'MS-ASPNETCORE-TOKEN' does not match the expected pairing token '98f9f98b-f0e8-43ec-8b20-3287e4954f00', request rejected.
2018-02-10 04:26:16.331 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 7.7719ms 400 
2018-02-10 04:26:16.443 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.0 GET http://127.0.0.1/twiki/bin/configure  
2018-02-10 04:26:16.459 +00:00 [Error] Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware: 'MS-ASPNETCORE-TOKEN' does not match the expected pairing token '98f9f98b-f0e8-43ec-8b20-3287e4954f00', request rejected.
2018-02-10 04:26:16.470 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 27.6613ms 400 
2018-02-10 04:26:16.541 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting HTTP/1.0 GET http:///scripts/..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c..%c1%9c/winnt/system32/cmd.exe?/c%20dir  
2018-02-10 04:26:16.556 +00:00 [Error] Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware: 'MS-ASPNETCORE-TOKEN' does not match the expected pairing token '98f9f98b-f0e8-43ec-8b20-3287e4954f00', request rejected.
2018-02-10 04:26:16.561 +00:00 [Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 20.1917ms 400 
```

**Comment by Tratcher** [comment]
What's sending you HTTP/1.0 requests? There's a known issue with ApplicationInsights where it fails for 1.0 request due to a missing Host header.

It also looks like you have something sending requests directly to Kestrel and bypassing the IIS front-end. IISIntegration blocks these requests.

**Comment by Tratcher** [comment]
See https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/278

**Comment by Tratcher** [comment]
Request starting HTTP/1.0 GET http:///scripts/..%c1%258s..%c1%258s..%c1%258s..%c1%258s..%c1%258s..%c1%258s..%c1%258s..%c1%258s/winnt/system32/cmd.exe?/c%20dir  looks extremely fishy. This looks like a malicious port scanner on your local machine.

**Comment by xt0rted** [comment]
I'm not sure where the requests came from. The site's on app services, has the https only option enabled, always on enabled, and a couple app insights availability tests that hit a few of our primary pages.

**Comment by xt0rted** [comment]
By the looks of it there's been no recent deployments or changes to the site. The most recent deployment was January 29th.

**Comment by blowdart** [comment]
Could you email your subscription ID and the site details, I'm going to ask Azure to take a look at this. barry.dorrans@microsoft.com

**Comment by petrpod** [comment]
The requests are caused by an internal scanner in Azure App Service and there is no malicious intent. We are actively working to remove this behavior, so customers (you) don't see these suspicious requests anymore. Again, there is nothing to worry about and we should be able to fix it soon. Apologies for the inconvenience and confusion.

**Comment by xt0rted** [comment]
Thanks @blowdart and @petrpod for the followup on this. I'm glad to hear it was just an internal scan and that Kestrel has some features to help stop these.

**Comment by PureKrome** [comment]
![](https://media.giphy.com/media/xT5LMyQOkWhX4HEvm0/giphy.gif)
