### ISSUE TITLE
FrameRequestStream/HttpRequestStream is not compatible with CryptoStream

### ISSUE THREAD

**Issue by kekekeks** [aspnet/KestrelHttpServer#2341]
```
System.NotSupportedException: Specified method is not supported.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.Flush()
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
```

`CryptoStream.Dispose` is calling `Flush` on the underlying stream even if said stream is read only - https://github.com/dotnet/corefx/issues/27326

Apparently this is intended behavior of `CryptoStream` and `Flush` shouldn't ever throw exceptions: https://github.com/dotnet/corefx/pull/27327#pullrequestreview-98384813

**Comment by davidfowl** [comment]
Fixed by #2342
