### ISSUE TITLE
Broken tests:  ResponseFormats_Kestrel_ContentLength etc

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2373]
A bunch of these tests were broken by the new runtime [on High Sierra](http://aspnetci/viewLog.html?buildId=418684&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId-1295381151259444512).

```
Assert.Null() Failure
Expected: (null)
Actual:   True
   at ServerComparison.FunctionalTests.ResponseTests.CheckContentLengthAsync(HttpClient client, ILogger logger)
   at ServerComparison.FunctionalTests.ResponseTests.ResponseFormats(ServerType serverType, RuntimeFlavor runtimeFlavor, RuntimeArchitecture architecture, Func`3 scenario, ApplicationType applicationType, String testName) in /_/test/ServerComparison.FunctionalTests/ResponseTests.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| TestLifetime Information: Starting test ResponseFormats_Kestrel_ContentLength_Kestrel_CoreClr_x64_Portable
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet run --no-restore --framework netcoreapp2.1 -- --server.urls http://localhost:56915/  --server Microsoft.AspNetCore.Server.Kestrel
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=Responses
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 82402
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using launch settings from /Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/ServerTests/test/ServerComparison.TestSites/Properties/launchSettings.json...
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: dotnet stderr: The launch profile "(Default)" could not be applied.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: dotnet stderr: A usable launch profile could not be located.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: Responses
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: /Users/aspnetci/Documents/buildAgent/work/33bdfc1cae7b2a38/modules/ServerTests/test/ServerComparison.TestSites/bin/Release/netcoreapp2.1/
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://localhost:56915
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://localhost:56915/
| ResponseFormats Warning: Retry count 1..
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request starting HTTP/1.1 GET http://localhost:56915/  
| ResponseFormats Information: Testing ContentLength
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request finished in 114.76ms 200 
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request starting HTTP/1.1 GET http://localhost:56915/contentlength  
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request finished in 5.546ms 200 
| ResponseFormats Warning: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
|                          {
|                            Connection: close
|                            Date: Sat, 10 Mar 2018 00:53:40 GMT
|                            Server: Kestrel
|                            Content-Length: 14
|                          }
| ResponseFormats Warning: Content Length
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Attempting to cancel process 82402
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application is shutting down...
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Unable to terminate the host process with process Id '82402
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: [Time]: Total time taken for this test variation '5.350861' seconds
| TestLifetime Information: Finished test ResponseFormats_Kestrel_ContentLength_Kestrel_CoreClr_x64_Portable in 5.351803s
```

**Comment by ryanbrandenburg** [comment]
Did #104 fix this?

**Comment by Tratcher** [comment]
Yes
