### ISSUE TITLE
Transient: "Unable to start Kestrel"

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2384]
http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=419928&_focus=125891

```
| Microsoft.AspNetCore.Server.Kestrel Critical: Unable to start Kestrel.
|    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
|    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
|    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync() in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\src\Kestrel.Transport.Sockets\SocketTransport.cs:line 93
|    --- End of inner exception stack trace ---
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync() in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\src\Kestrel.Transport.Sockets\SocketTransport.cs:line 97
|    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\src\Kestrel.Core\KestrelServer.cs:line 155
| --- End of stack trace from previous location where exception was thrown ---
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context) in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\src\Kestrel.Core\Internal\AddressBinder.cs:line 104
|    --- End of inner exception stack trace ---
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context) in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\src\Kestrel.Core\Internal\AddressBinder.cs:line 108
|    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context) in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\src\Kestrel.Core\ListenOptions.cs:line 207
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context) in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\src\Kestrel.Core\Internal\AddressBinder.cs:line 252
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding) in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\src\Kestrel.Core\Internal\AddressBinder.cs:line 46
|    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in C:\b\w\33bdfc1cae7b2a38\modules\KestrelHttpServer\src\Kestrel.Core\KestrelServer.cs:line 158
```

We don't know for sure what exception caused this message because Logging doesn't use the exception by default for extensions like "LogCritical". I think step one here would be to make sure that the exception gets logged (either by including it in the message we log, or by changing https://github.com/aspnet/Logging/blob/fb0103e6b7cc7987dbfc1cc91f7a20b14eaa4937/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L511 to include it by default).

**Comment by ryanbrandenburg** [comment]
Here's a list that I will be using to track this as it continues.

**Comment by ryanbrandenburg** [comment]
I agree. I see this a lot, people see that we take an exception in those and just assume we'll do something useful with it. I filed aspnet/Logging#776 about it.

**Comment by halter73** [comment]
@davidfowl and I spoke about this during Kestrel triage. It's not up to the default formatter to include exception details. That's up to the logging provider itself.

You'll notice at least part of the exception's stack trace is included in the log output, so it's not being completely ignored. Instead it appears that something in our test logging infrastructure is truncating the beginning of Exception.ToString().

**Comment by shirhatti** [comment]
This will be made easier by #2390

**Comment by muratg** [comment]
@mikeharder is this related to what you're currently looking at?

**Comment by mikeharder** [comment]
@muratg: It's likely caused by a port being in use (the issue I'm investigation), but I can't be certain from the error message.

**Comment by shirhatti** [comment]
Closing due to inactivity.
