### ISSUE TITLE
Handle posting to the LibuvThread after shutdown

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2386]
Since doing https://github.com/aspnet/KestrelHttpServer/commit/e7d3b0c5f971d6367ccec438407e91807a31447c, it exposed a crash we have on shutdown where we're posting to the libuv thread after it's disposed.

```
The active test run was aborted. Reason: Unhandled Exception: System.AggregateException: One or more errors occurred. (Safe handle has been closed) ---> System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.async_send(UvAsyncHandle handle) in /_/src/Kestrel.Transport.Libuv/Internal/Networking/LibuvFunctions.cs:line 179
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.Post[T](Action`1 callback, T state) in /_/src/Kestrel.Transport.Libuv/Internal/LibuvThread.cs:line 193
   at System.IO.Pipelines.Pipe.CancelPendingRead()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.Abort(Exception error) in /_/src/Kestrel.Core/Internal/Http/Http1OutputProducer.cs:line 157
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Abort(Exception error) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 420
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.Abort(Exception ex) in /_/src/Kestrel.Core/Internal/HttpConnection.cs:line 285
   at System.IO.Pipelines.PipeCompletionCallbacks.Execute()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletionCallbacks.Execute()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by halter73** [comment]
You thinking we should just try/catch in Post?
