### ISSUE TITLE
Flaky tests in Kestrel 

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2387]
http://aspnetci/viewLog.html?buildId=420183&buildTypeId=Lite_KestrelStressTest
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<ResponseStatusCodeSetBeforeHttpContextDispose>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
[This list](http://aspnetci/httpAuth/app/rest/builds?locator=tag:CollectionDiff,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)) should contain almost all instances of this failure.

**Comment by shirhatti** [comment]
Fixed
