### ISSUE TITLE
Flaky test: TestInvalidRequestLines

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2404]
[This](http://aspnetci/viewLog.html?buildId=423203&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) test failed with the following error:

```
System.AggregateException : An error occurred while writing to logger(s). (Unexpected critical error. Log Critical[0]: Failed to gracefully close Kestrel. )
---- System.Exception : Unexpected critical error. Log Critical[0]: Failed to gracefully close Kestrel. 
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvTrace.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/src/Kestrel.Transport.Libuv/Internal/LibuvTrace.cs:line 103
   at Microsoft.Extensions.Logging.LoggerExtensions.LogCritical(ILogger logger, String message, Object[] args)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.StopAsync() in /_/src/Kestrel.Transport.Libuv/LibuvTransport.cs:line 56
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 202
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 173
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.Dispose() in /_/src/Kestrel.Core/KestrelServer.cs:line 219
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.BadHttpRequestTests.TestBadRequest(String request, String expectedResponseStatusCode, String expectedExceptionMessage, String expectedAllowHeader) in /_/test/Kestrel.FunctionalTests/BadHttpRequestTests.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 61
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
```

Instances of this failure will show up [here](aspnetci/httpAuth/app/rest/builds?locator=tag:KestrelGraceful,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by shirhatti** [comment]
Closing due to inactivity.
