### ISSUE TITLE
 Error -107 ENOTCONN socket is not connected

### ISSUE THREAD

**Issue by dexterhussain** [aspnet/KestrelHttpServer#2410]
I am having a strange issue, the Same application is running fine on one ubuntu 16.04 Server with Dotnet core 2.0
I installed new Ubuntu and tried to deploy the application as soon as clients connect it gives this error

elsteppgc@elbystep:~/stepel$ sudo su
[sudo] password for elsteppgc:
root@elbystep:/home/elsteppgc/stepel# dotnet Elp.dll
Hosting environment: Production
Content root path: /home/elsteppgc/stepel
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[0]
      ListenerSecondary.OnConnection
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -107 ENOTCONN socket is not connected
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.tcp_getpeername(UvTcpHandle handle, SockAddr& addr, Int32& namelen)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.GetPeerIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection..ctor(ListenerContext context, UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerSecondary.ReadStartCallback(UvStreamHandle handle, Int32 status)

https://github.com/dexterhussain/KestrelWebTest

**Comment by dexterhussain** [comment]
Somehow I managed to fix the error 
the issue is in the Asp.netcore all nugget upgrade it to latest one. and the issue just goes

**Comment by dexterhussain** [comment]
The Asp.NetCore.All 2.0 version has this error.

**Comment by muratg** [comment]
@dexterhussain Closing, as it looks like you resolved your issue with the latest version of the package.

**Comment by halter73** [comment]
Do you want to cal in to triage @muratg?

**Comment by dexterhussain** [comment]
@muratg  but I have a question here that why Kestrel Web Server doesn't show an error? and neither the application runs. I figured out when I sent a map query. Kestrel should show an error

**Comment by dexterhussain** [comment]
@halter73 there should be logging in kestrel

**Comment by muratg** [comment]
You probably got a client disconnect.  Check your INFO level logs.

**Comment by dexterhussain** [comment]
@muratg @halter73  this is the same thing which I am saying. Kestrel opens port runs the application but doesn't give any errors. it should say that some assembly cannot be loaded. How can a client disconnect when kestrel is serving nothing? I tried nmap and it showed error

**Comment by halter73** [comment]
@dexterhussain What makes you think there was an assembly load error?

It seems more like there's a connection that was closed by the client right as it was starting. These sorts of early client disconnects can cause tcp_getpeername to fail with ENOTCONN, but based on the number of bug reports, this seems pretty rare.

I've considered of lowering the log level for tcp_getpeername failing with ENOTCONN in the hopes of avoiding wild goose chases. There error should be completely benign. Other than the error log, do you see anything else wrong? Like @muratg mentioned INFO level logs might help you better diagnose your problem.

**Comment by zicjin** [comment]
i have the same problem。
![tim 20180522195552](https://user-images.githubusercontent.com/199482/40360944-4f98d2f8-5dfa-11e8-9ba4-74c78b5b56aa.png)
One day my asp.net core process suddenly encountered this problem. During this time I did not redeploy the application and did not restart the system.

I use docker to deploy applications in Ubuntu. the image version:
Microsoft/aspnetcore:2.0 AS base
Microsoft/aspnetcore-build:2.0 AS build

**Comment by sichbo** [comment]
We're getting this nuisance log flooding as well. Basically any bots spamming an end point like this raise the stack trace when running at LogLevel 'Warning'.

Hundreds of garbage requests like this
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.0 POST http://{server-ip}/xmlrpc.php text/xml 281
info: Microsoft.AspNetCore.Server.Kestrel[32]
      Connection id "0HLE5CSQGB9O0", Request id "0HLE5CSQGB9O0:00000001": the application completed without reading the entire request body.
```
yield a similar number of these:
```
fail: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[0]
      Listener.OnConnection
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -107 ENOTCONN socket is not connected
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.tcp_getpeername(UvTcpHandle handle, SockAddr& addr, Int32& namelen)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.GetPeerIPEndPoint()
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection..ctor(ListenerContext context, UvStreamHandle socket)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.DispatchConnection(UvStreamHandle socket)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status)

```

Another recent 2.1 kestrel fix https://github.com/aspnet/KestrelHttpServer/issues/2605 lowered log levels. You should be able to safely do it in this instance as well.
