### ISSUE TITLE
Windows 7: Client Certificate is not accepted

### ISSUE THREAD

**Issue by StefanoD** [aspnet/KestrelHttpServer#2438]
Hi,
I'm using client authentification by an TLS certificate. The validation of the client certificate is done by a custom validation handler. See:

```C#
public static IWebHost BuildWebHost(string[] args)
{
	return WebHost.CreateDefaultBuilder(args)
		.UseStartup<Startup>()
		.UseSetting("detailedErrors", "true")
		.CaptureStartupErrors(true)
		.UseKestrel(options =>
		{
			options.Listen(IPAddress.Any, 55555, listenOptions =>
			{
				listenOptions.UseHttps(new HttpsConnectionAdapterOptions
				{
					ServerCertificate = new X509Certificate2(GetQlcClientServerCertificate(), "mypass"),
					SslProtocols = SslProtocols.Tls11 |
						       SslProtocols.Tls12,
					ClientCertificateMode = ClientCertificateMode.RequireCertificate,
					ClientCertificateValidation = new KestrelISWCertificateValidator("PCClientCertificateValidation").ValidateClientCertificate
				});
			});
		})
		.UseNLog()  // NLog: setup NLog for Dependency injection
		.Build();
}
```
This works fine on my Windows 10 workstation. But when I install my server and my client app on a Windows 7 machine, I get following error:

```XML
2018-03-28 16:22:56.4119||ERROR|Microsoft.AspNetCore.Server.Kestrel|Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter. System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.FrameConnection.<ApplyConnectionAdaptersAsync>d__50.MoveNext()
```
My validation class is never touched. Instead Kestrel denies the client certificate from its own.
What can I do?
These are the relevant package versions which I use.
```XML
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.2" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Https" Version="2.0.2" />
```

Further infos: The client certificate is a self-signed certificate which has not been signed by any CA. The same is true for the server certificate.

**Comment by blowdart** [comment]
What's inside the validator?

It's odd to see one that's new-ed up, generally they're static; e.g.

```c#
    public static class CertificateValidator
    {
        /// <summary>
        /// Disables connection based client certificate validation so the middleware can handle it instead.
        /// </summary>
        /// <param name="certificate">The certificate used to authenticate the remote party.</param>
        /// <param name="chain">The chain of certificate authorities associated with the remote certificate.</param>
        /// <param name="errors">One or more errors associated with the remote certificate.</param>
        /// <returns>A Boolean value that determines whether the specified certificate is accepted for authentication.</returns>
        public static bool DisableChannelValidation(X509Certificate2 certificate, X509Chain chain, SslPolicyErrors errors)
        {
            return true;
        }
    }
```

**Comment by StefanoD** [comment]
@blowdart It maybe odd, but it's still valid code, isn't it?

```C#
public class KestrelISWCertificateValidator
    {
        private readonly CertificateValidationConfig _config;
        private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();

        public KestrelISWCertificateValidator(string configSection)
        {
            var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json");

            var config = builder.Build();

            _config = new CertificateValidationConfig();
            config.GetSection(configSection).Bind(_config);

        }
        public bool ValidateClientCertificate(X509Certificate2 certificate, X509Chain certChain, SslPolicyErrors sslPolicyErrors)
        {
            return IsValidClientCertificate(certificate);
        }

        private bool IsValidClientCertificate(X509Certificate2 certificate)
        {
            // Checks...
	    // ...
            return true;
        }
    }
}
```

**Comment by StefanoD** [comment]
I'm using the simplest possible example now and nothing changes:

```C#
public static IWebHost BuildWebHost(string[] args)
{
	return WebHost.CreateDefaultBuilder(args)
		.UseStartup<Startup>()
		.UseKestrel(options =>
		{
			options.Listen(IPAddress.Any, pcClientPort, listenOptions =>
			{
				listenOptions.UseHttps(new HttpsConnectionAdapterOptions
				{
					ServerCertificate = new X509Certificate2(GetQlcClientServerCertificate(), "myPass"),
					CheckCertificateRevocation = false,
					ClientCertificateMode = ClientCertificateMode.RequireCertificate,
					ClientCertificateValidation = DisableChannelValidation
				});
			});
		})
		.Build();
}

public static bool DisableChannelValidation(X509Certificate2 certificate, X509Chain chain, SslPolicyErrors errors)
{
	return true;
}
```

**Comment by blowdart** [comment]
Odd. OK, I'm tapping out in favour of the devs :) Hey @halter73  ...

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
