### ISSUE TITLE
Flaky test: RejectsConnectionsWhenLimitReached

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2469]
This test fails with the following error:
```
System.TimeoutException : The operation at /_/test/shared/TestConnection.cs:129 timed out after reaching the limit of 60000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TestConnection.<Receive>d__21.MoveNext() in /_/test/shared/TestConnection.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionLimitTests.<RejectsConnectionsWhenLimitReached>d__2.MoveNext() in /_/test/Kestrel.FunctionalTests/ConnectionLimitTests.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

This is part of an overall issue whose members can all be viewed [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:timeout,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by halter73** [comment]
@ryanbrandenburg I think your "here" link is bad. It links to some XML, and when I follow the urls in the XML, it points to a bunch of tests runs that have timed out but not with this error. This particular test timing out after 60 seconds should prevent those kind of test run timeouts.

I saw a failure UpgradedConnectionsCountsAgainstDifferentLimit that might be related to this. I used @JunTaoLuo new file logging to see why it failed and it appears that our TestConnection client sent a FIN for no apparent reason prior to the test making the 3rd connection that should have been rejected. Since the previous connection had been closed by the client, the connection limit was never actually hit.

Here's the failure I saw:

```
  Failed   UpgradedConnectionsCountsAgainstDifferentLimit
   System.IO.IOException : Expected connection close, received data instead: "HTTP/1.1 200 OK
  Date: Tue, 17 Apr 2018 17:47:33 GMT
  Content-Length: 0
  
  "
  Stack Trace:
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__1.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionLimitTests.<UpgradedConnectionsCountsAgainstDifferentLimit>d__1.MoveNext() in /home/shalter/aspnet/KestrelHttpServer/test/Kestrel.FunctionalTests/ConnectionLimitTest
s.cs:line 89
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Here's the log from the failed run:
```
$ cat "Libuv.FunctionalTests/NET Core 4.6.0.0/ConnectionLimitTests/UpgradedConnectionsCountsAgainstDifferentLimit.log"
17:47:33.083 [TestLifetime] [Information] Starting test "UpgradedConnectionsCountsAgainstDifferentLimit"
17:47:33.099 [Hosting.Internal.WebHost] [Debug] Hosting starting
17:47:33.113 [Hosting.Internal.WebHost] [Debug] Hosting started
17:47:33.113 [Hosting.Internal.WebHost] [Debug] Loaded hosting startup assembly "Libuv.FunctionalTests, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
17:47:33.120 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJBN"" started.
17:47:33.614 [Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
17:47:36.464 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJCG"" started.
17:47:36.468 [Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
17:47:36.468 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJCG"" completed keep alive response.
17:47:36.469 [Hosting.Internal.WebHost] [Information] Request finished in 0.9949ms 200 
17:47:36.769 [Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLD4HD64NJCG"" received FIN.
17:47:36.775 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJCG"" disconnecting.
17:47:36.776 [Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLD4HD64NJCG"" sending FIN.
17:47:41.050 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJCG"" stopped.
17:47:41.272 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJCH"" started.
17:47:41.286 [Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
17:47:41.286 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJCH"" completed keep alive response.
17:47:41.286 [Hosting.Internal.WebHost] [Information] Request finished in 1.1209ms 200 
17:47:41.560 [Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLD4HD64NJCH"" received FIN.
17:47:41.560 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJCH"" disconnecting.
17:47:41.561 [Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLD4HD64NJCH"" sending FIN.
17:47:41.563 [Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLD4HD64NJBN"" received FIN.
17:47:41.563 [Hosting.Internal.WebHost] [Debug] Hosting shutdown
17:47:41.563 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJCH"" stopped.
17:47:41.580 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJBN"" disconnecting.
17:47:41.585 [Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLD4HD64NJBN"" sending FIN.
17:47:41.612 [Hosting.Internal.WebHost] [Information] Request finished in 7998.0153ms 101 
17:47:41.613 [Server.Kestrel] [Debug] Connection id ""0HLD4HD64NJBN"" stopped.
```

Here's what a log from a successful run of the same test looks like:
```
shalter@f4-linux-server:~/aspnet/KestrelHttpServer/artifacts/logs$ cat "Sockets.FunctionalTests/NET Core 4.6.0.0/ConnectionLimitTests/UpgradedConnectionsCountsAgainstDifferentLimit.log"
17:43:26.806 [TestLifetime] [Information] Starting test "UpgradedConnectionsCountsAgainstDifferentLimit"
17:43:27.140 [Hosting.Internal.WebHost] [Debug] Hosting starting
17:43:27.345 [Hosting.Internal.WebHost] [Debug] Hosting started
17:43:27.346 [Hosting.Internal.WebHost] [Debug] Loaded hosting startup assembly "Sockets.FunctionalTests, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
17:43:27.529 [Server.Kestrel] [Debug] Connection id ""0HLD4HASUF2S3"" started.
17:43:28.740 [Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
17:43:30.784 [Server.Kestrel] [Debug] Connection id ""0HLD4HASUF2T0"" started.
17:43:30.878 [Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
17:43:30.878 [Server.Kestrel] [Debug] Connection id ""0HLD4HASUF2T0"" completed keep alive response.
17:43:30.878 [Hosting.Internal.WebHost] [Information] Request finished in 0.9105ms 200 
17:43:31.247 [Server.Kestrel] [Debug] Connection id ""0HLD4HASUF2T7"" started.
17:43:31.248 [Server.Kestrel] [Warning] Connection id ""0HLD4HASUF2T7"" rejected because the maximum number of concurrent connections has been reached.
17:43:31.248 [Server.Kestrel] [Debug] Connection id ""0HLD4HASUF2T7"" stopped.
17:43:31.248 [Server.Kestrel.Transport.Sockets] [Debug] Connection id ""0HLD4HASUF2T7"" sending FIN.
17:43:31.445 [Hosting.Internal.WebHost] [Debug] Hosting shutdown
17:43:31.445 [Server.Kestrel.Transport.Sockets] [Debug] Connection id ""0HLD4HASUF2S3"" received FIN.
17:43:31.479 [Server.Kestrel.Transport.Sockets] [Debug] Connection id ""0HLD4HASUF2T0"" received FIN.
17:43:31.479 [Server.Kestrel] [Debug] Connection id ""0HLD4HASUF2T0"" disconnecting.
17:43:31.480 [Server.Kestrel] [Debug] Connection id ""0HLD4HASUF2S3"" disconnecting.
17:43:31.480 [Server.Kestrel.Transport.Sockets] [Debug] Connection id ""0HLD4HASUF2T0"" sending FIN.
17:43:31.480 [Server.Kestrel.Transport.Sockets] [Debug] Connection id ""0HLD4HASUF2S3"" sending FIN.
17:43:31.480 [Server.Kestrel] [Debug] Connection id ""0HLD4HASUF2T0"" stopped.
17:43:31.577 [Hosting.Internal.WebHost] [Information] Request finished in 2911.8372ms 101 
17:43:31.578 [Server.Kestrel] [Debug] Connection id ""0HLD4HASUF2S3"" stopped.
```

**Comment by ryanbrandenburg** [comment]
The 'here' like was for the larger list of general timeouts that I made when I was hoping it could all be fixed from a single place. I no longer believe that to be the case.

**Comment by Tratcher** [comment]
17 CI Failures between Jan 28 and Apr 5. It includes Ubuntu, OSX, and High Sierra (No Windows).

6 are the missing response issue logged at https://github.com/aspnet/KestrelHttpServer/issues/2635
@halter73  one of these happened on Ubuntu which I think is new for us
http://aspnetci/viewLog.html?buildId=428500&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR#testNameId-2603845343937552310

4 are the timeout listed above. 2 more look timeout related but failed with Connection reset by peer.

3 are failing with Invalid Argument
http://aspnetci/viewLog.html?buildId=407883&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR#testNameId-2603845343937552310
```
System.IO.IOException : Unable to transfer data on the transport connection: Invalid argument.
---- System.Net.Sockets.SocketException : Invalid argument
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamWriter.<FlushAsyncInternal>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TestConnection.<Send>d__20.MoveNext() in /mnt/work/33bdfc1cae7b2a38/modules/KestrelHttpServer/test/shared/TestConnection.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionLimitTests.<RejectsConnectionsWhenLimitReached>d__2.MoveNext() in /mnt/work/33bdfc1cae7b2a38/modules/KestrelHttpServer/test/Kestrel.FunctionalTests/ConnectionLimitTests.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
```

**Comment by JunTaoLuo** [comment]
We have not seen these tests fail since April. Closing until we see failures again.
