### ISSUE TITLE
Flaky test: CriticalErrorLoggedIfApplicationDoesntComplete

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2475]
This test [fails](http://aspnetci/viewLog.html?buildId=444631&buildTypeId=Releases_21Public_UbuntuUniverse) occasionally with the following error:

```
Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpConnectionManagerTests.<CriticalErrorLoggedIfApplicationDoesntComplete>d__0.MoveNext() in /_/test/Kestrel.FunctionalTests/HttpConnectionManagerTests.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Future instances of this failure can be found [here](http://aspnetci/project.html?projectId=Releases_21Public&testNameId=4494644039974195093&tab=testDetails).

**Comment by Tratcher** [comment]
http://aspnetci/project.html?projectId=Releases_21Public&buildTypeId=&tab=testDetails&testNameId=4494644039974195093&order=TEST_STATUS_DESC&branch_Releases_21Public=__all_branches__&itemsCount=50
While this test does have a colorful CI history, the bulk of them were due to catastrophic build failures like `System.TypeLoadException : Method 'Pin' in type 'System.Buffers.MemoryPoolBlock'`

The linked build was the only instance of the reported error. Closing.
