### ISSUE TITLE
Test failures on Ubuntu Jenkins

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2506]
Several tests failed on a recent Ubuntu Jenkins run.  I'm not sure if they're flaky or fail consistently on Jenkins.

# RegisterAddresses_HostName_Success
```
16:54:35    [xUnit.net 00:00:03.7981166]     RegisterAddresses_HostName_Success [FAIL]
16:54:35    Failed   RegisterAddresses_HostName_Success
16:54:35  RUNDOTNET : error Message:  [/home/dotnet-bot/.dotnet/buildtools/korebuild/2.1.0-preview3-17018/KoreBuild.proj]
16:54:35     System.Net.Sockets.SocketException : No such device or address
16:54:35    Stack Trace:
16:54:35       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri)
16:54:35       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
16:54:35       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
16:54:35       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
16:54:35       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 170
16:54:35       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success() in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 39
16:54:35    --- End of stack trace from previous location where exception was thrown ---
```

# ListenAnyIP_HostName_Success
```
16:54:37    [xUnit.net 00:00:05.9554544]     ListenAnyIP_HostName_Success [FAIL]
16:54:37    Log Critical[0]: Unable to start Kestrel. System.IO.IOException: Failed to bind to address http://[::1]:46742: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
16:54:37       at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
16:54:37       at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
16:54:37       at System.Net.Sockets.Socket.Bind(EndPoint localEP)
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync() in /_/src/Kestrel.Transport.Sockets/SocketTransport.cs:line 93
16:54:37       --- End of inner exception stack trace ---
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync() in /_/src/Kestrel.Transport.Sockets/SocketTransport.cs:line 97
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in /_/src/Kestrel.Core/KestrelServer.cs:line 155
16:54:37    --- End of stack trace from previous location where exception was thrown ---
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 104
16:54:37       --- End of inner exception stack trace ---
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 108
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context) in /_/src/Kestrel.Core/ListenOptions.cs:line 190
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 252
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 46
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 158
16:54:37    Failed   ListenAnyIP_HostName_Success
16:54:37  RUNDOTNET : error Message:  [/home/dotnet-bot/.dotnet/buildtools/korebuild/2.1.0-preview3-17018/KoreBuild.proj]
16:54:37     System.Net.Sockets.SocketException : No such device or address
16:54:37    Stack Trace:
16:54:37       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri)
16:54:37       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
16:54:37       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
16:54:37       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_Success(String[] testUrls, Int32 testPort) in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 326
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_HostName_Success() in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 307
16:54:37    --- End of stack trace from previous location where exception was thrown ---
16:54:37    Log Critical[0]: Unable to start Kestrel. System.InvalidOperationException: Dynamic port binding is not supported when binding to localhost. You must either bind to 127.0.0.1:0 or [::1]:0, or both.
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions..ctor(Int32 port) in /_/src/Kestrel.Core/LocalhostListenOptions.cs:line 22
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 141
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 252
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 46
16:54:37       at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 158
```

# Sending100ContinueDoesNotStartResponse
```
16:54:41    [xUnit.net 00:00:09.3892916]     Sending100ContinueDoesNotStartResponse [FAIL]
16:54:42    Failed   Sending100ContinueDoesNotStartResponse
16:54:42  RUNDOTNET : error Message:  [/home/dotnet-bot/.dotnet/buildtools/korebuild/2.1.0-preview3-17018/KoreBuild.proj]
16:54:42     Assert.Contains() Failure
16:54:42    Not found: (filter expression)
16:54:42    In value:  ConcurrentQueue<LogMessage> [LogMessage { EventId = 3, Exception = null, LogLevel = Debug, Message = "Hosting starting" }, LogMessage { EventId = 4, Exception = null, LogLevel = Debug, Message = "Hosting started" }, LogMessage { EventId = 0, Exception = null, LogLevel = Debug, Message = "Loaded hosting startup assembly Sockets.Functional"... }, LogMessage { EventId = ConnectionStart, Exception = null, LogLevel = Debug, Message = "Connection id \"0HLD5GUTSSB33\" started." }, LogMessage { EventId = 1, Exception = null, LogLevel = Information, Message = "Request starting HTTP/1.1 POST http:///  " }, ...]
16:54:42    Stack Trace:
16:54:42       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.Sending100ContinueDoesNotStartResponse() in /_/test/Kestrel.FunctionalTests/ResponseTests.cs:line 1685
16:54:42    --- End of stack trace from previous location where exception was thrown ---
```

# UpgradedConnectionsCountsAgainstDifferentLimit
```
16:57:17    [xUnit.net 00:00:04.4029017]     UpgradedConnectionsCountsAgainstDifferentLimit [FAIL]
16:57:17    Failed   UpgradedConnectionsCountsAgainstDifferentLimit
16:57:17  RUNDOTNET : error Message:  [/home/dotnet-bot/.dotnet/buildtools/korebuild/2.1.0-preview3-17018/KoreBuild.proj]
16:57:17     System.IO.IOException : Expected connection close, received data instead: "HTTP/1.1 200 OK
16:57:17    Date: Wed, 18 Apr 2018 23:57:14 GMT
16:57:17    Content-Length: 0
16:57:17    
16:57:17    "
16:57:17    Stack Trace:
16:57:17       at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
16:57:17       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionLimitTests.UpgradedConnectionsCountsAgainstDifferentLimit() in /_/test/Kestrel.FunctionalTests/ConnectionLimitTests.cs:line 89
16:57:17    --- End of stack trace from previous location where exception was thrown ---
```

# UsesProvidedServerCertificateSelectorEachTime 
```
16:57:17    [xUnit.net 00:00:04.4106802]     UsesProvidedServerCertificateSelectorEachTime [FAIL]
16:57:17    Failed   UsesProvidedServerCertificateSelectorEachTime
16:57:17  RUNDOTNET : error Message:  [/home/dotnet-bot/.dotnet/buildtools/korebuild/2.1.0-preview3-17018/KoreBuild.proj]
16:57:17     System.IO.IOException : Unable to read data from the transport connection: Invalid argument.
16:57:17    ---- System.Net.Sockets.SocketException : Invalid argument
16:57:17    Stack Trace:
16:57:17       at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
16:57:17       at System.Net.Security.SslState.ThrowIfExceptional()
16:57:17       at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
16:57:17       at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
16:57:17       at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
16:57:17       at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
16:57:17       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
16:57:17    --- End of stack trace from previous location where exception was thrown ---
16:57:17       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsConnectionAdapterTests.UsesProvidedServerCertificateSelectorEachTime() in /_/test/Kestrel.FunctionalTests/HttpsConnectionAdapterTests.cs:line 229
16:57:17    --- End of stack trace from previous location where exception was thrown ---
16:57:17    ----- Inner Stack Trace -----
```

# AcceptsRequestWithNoContentLengthAndUpgrade 
```
16:58:34    [xUnit.net 00:01:14.3683030]     AcceptsRequestWithNoContentLengthAndUpgrade [FAIL]
16:58:34    Failed   AcceptsRequestWithNoContentLengthAndUpgrade
16:58:34  RUNDOTNET : error Message:  [/home/dotnet-bot/.dotnet/buildtools/korebuild/2.1.0-preview3-17018/KoreBuild.proj]
16:58:34     System.TimeoutException : The operation at /_/test/shared/TestConnection.cs:129 timed out after reaching the limit of 60000ms.
16:58:34    Stack Trace:
16:58:34       at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
16:58:34       at Microsoft.AspNetCore.Testing.TestConnection.Receive(String[] lines) in /_/test/shared/TestConnection.cs:line 131
16:58:34       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.UpgradeTests.AcceptsRequestWithNoContentLengthAndUpgrade() in /_/test/Kestrel.FunctionalTests/UpgradeTests.cs:line 190
16:58:34    --- End of stack trace from previous location where exception was thrown ---
```

https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/dev/job/linux-Configuration_Release_prtest/111/timestamps/?time=HH:mm:ss&appendLog&locale=en_US

**Comment by ryanbrandenburg** [comment]
Saw one of these failures [again](http://aspnetci/viewLog.html?buildId=469291&buildTypeId=Releases_21Public_UbuntuUniverse).

**Comment by JunTaoLuo** [comment]
I'll close this issue for now. This is tracking multiple issues and I'd like to see issues filed for each individual test failure by the automation so it's easier to track the investigation.
