### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.IgnoreNullHeaderValues

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2517]
9/10 of the theories for this test fail sporadically.

The failures are limited to MacOS & High Sierra.

This started on 4/13 and is still failing today on 4/23.

There were no test changes then, but there was a product change https://github.com/aspnet/KestrelHttpServer/commit/e30a02cee5ff4919a3be82bf53bab6bb5146e7de that suspicously related.

```
System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<IgnoreNullHeaderValues>d__3.MoveNext() in /_/test/Kestrel.FunctionalTests/ResponseTests.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Tratcher** [comment]
The failures are primarily in the Libuv.FunctionalTests/netcoreapp2.0 test group, which is the last to run, and there are several other tests failing with the same HttpClient stack trace.
OnStartingThrowsWhenSetAfterResponseHasAlreadyStarted 
OnCompletedExceptionShouldNotPreventAResponse
LargeDownload 

This looks like a resource exhaustion issue specific to Mac on netcoreapp2.0. In this environment HttpClient is using libcurl, which is known to have exhaustion issues. It's possible we've just added too many tests and run into this.

**Comment by Tratcher** [comment]
How to change file handle limits: https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c

**Comment by ryanbrandenburg** [comment]
@muratg this issue fails OSX tests [most of the time](http://aspnetci/project.html?tab=testDetails&testNameId=-4942304050891655961&projectId=XPlat&buildTypeId=XPlat_Mac_MacUniverseCoreCLR), can we get someone on this (I think @Tratcher is already working on a couple flaky items)?

**Comment by Tratcher** [comment]
Stephen as taken over.
