### ISSUE TITLE
Http Status Code 204 failing with empty content

### ISSUE THREAD

**Issue by srinigithub2016** [aspnet/KestrelHttpServer#2530]
Service A calls Service B => Service B returns 204. On the Service A when EnsureSucessStatusCode is invoked it adds empty Content which then fails from Kestrel.
Writing to the response body is invalid for responses with status code 204.

 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.HandleNonBodyResponseWrite()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.<WriteAsyncAwaited>d__199.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.ResponseCompression.BodyWrapperStream.<WriteAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Sy

To have a workaround we need to explicitly add the following where the Content is null and it works fine.

 if( response.StatusCode.Equals(HttpStatusCode.NoContent))
                    {
                        var response =new HttpResponseMessage(HttpStatusCode.NoContent);
                        return response;
                    }

Ask for Kestrel to ignore the Conent if the status code is 204. Or dotnet services should not add the content by default on 204 status code.

**Comment by Tratcher** [comment]
We're going to need a little more context to make sense out of this. Where did you add this workaround code? Can you share more of that code?
