### ISSUE TITLE
Flaky test: RequestTests.ServerCanAbortConnectionAfterUnobservedClose

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#2582]
Logs: http://aspnetci/viewLog.html?buildId=469789&tab=buildResultsDiv&buildTypeId=Releases_21Public_Win2012
```
System.TimeoutException : The operation at /_/test/Kestrel.FunctionalTests/RequestTests.cs:1296 timed out after reaching the limit of 30000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<ServerCanAbortConnectionAfterUnobservedClose>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by natemcmaster** [comment]
Fixed in dev with https://github.com/aspnet/KestrelHttpServer/pull/2567. Let's consider back-porting this test-only change to release/2.1.1 to improve reliability of our patches.

**Comment by Eilon** [comment]
@halter73 - is this something we can/should get into 2.1.3?

**Comment by halter73** [comment]
These test changes were already made in 2.1.1 by #2618. Closing.
