### ISSUE TITLE
Flaky Test: BlockedHeartbeat*

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2587]
```
  [xUnit.net 00:00:15.0820201]     BlockedHeartbeatDoesntCauseOverlapsAndIsLoggedAsError [FAIL]
  Failed   BlockedHeartbeatDoesntCauseOverlapsAndIsLoggedAsError
RUNDOTNET : error Message:  [/home/travis/.dotnet/buildtools/korebuild/2.2.0-preview1-17051/KoreBuild.proj]
   Assert.True() Failure
  Expected: True
  Actual:   False
  Stack Trace:
     at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.HeartbeatTests.BlockedHeartbeatDoesntCauseOverlapsAndIsLoggedAsError() in /_/test/Kestrel.Core.Tests/HeartbeatTests.cs:line 43
```

```
  Failed   BlockedHeartbeatIsNotLoggedAsErrorIfDebuggerAttached
RUNDOTNET : error Message:  [/home/travis/.dotnet/buildtools/korebuild/2.2.0-preview1-17051/KoreBuild.proj]
   Moq.MockException : 
  Expected invocation on the mock once, but was 2 times: h => h.OnHeartbeat(5/17/18 9:18:41 PM +00:00)
  
  Configured setups:
  h => h.OnHeartbeat(5/17/18 9:18:41 PM +00:00), Times.Exactly(2)
  
  Performed invocations:
  IHeartbeatHandler.OnHeartbeat(5/17/18 9:18:41 PM +00:00)
  IHeartbeatHandler.OnHeartbeat(5/17/18 9:18:41 PM +00:00)
  Stack Trace:
     at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
     at Moq.Mock.VerifyCalls(Interceptor targetInterceptor, MethodCall expected, Expression expression, Times times)
     at Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
     at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.HeartbeatTests.BlockedHeartbeatIsNotLoggedAsErrorIfDebuggerAttached() in /_/test/Kestrel.Core.Tests/HeartbeatTests.cs:line 76
  [xUnit.net 00:00:17.1678332]     BlockedHeartbeatIsNotLoggedAsErrorIfDebuggerAttached [FAIL]
```

https://travis-ci.org/aspnet/KestrelHttpServer/jobs/380397601

**Comment by Tratcher** [comment]
No failures on the main CI. Re-open if you have additional hits for this on travis.

**Comment by halter73** [comment]
#2609
