### ISSUE TITLE
Flaky Test: ResponseTests.TransferEncodingNotSetOnHeadResponse

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2601]
# Failure
```
System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 127.0.0.1:51918
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Microsoft.AspNetCore.Testing.TestConnection.CreateConnectedLoopbackSocket(Int32 port, AddressFamily addressFamily)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer.CreateConnection()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<TransferEncodingNotSetOnHeadResponse>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
http://aspnetci/viewLog.html?buildId=471692&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest

# History
http://aspnetci/viewLog.html?buildId=471692&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest

**Comment by ryanbrandenburg** [comment]
This problem also happened [here](http://aspnetci/viewLog.html?buildId=483448&buildTypeId=Lite_KestrelStressTest).

**Comment by ryanbrandenburg** [comment]
TestInvalidHeaders [failed again](http://aspnetci/viewLog.html?buildId=514780&buildTypeId=Lite_KestrelStressTest).

**Comment by ryanbrandenburg** [comment]
RegisterIPEndPoint_DynamicPort_Success [failed with about the same error](http://aspnetci/viewLog.html?buildId=520519&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by JunTaoLuo** [comment]
The original test has not failed since May and the latest test RegisterIPEndPoint_DynamicPort_Success should be more reliable after 0e99235 moved the binding tests to their own test group.
