### ISSUE TITLE
SSL error after long time running

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [aspnet/KestrelHttpServer#2605]
I'm currently using Let's Encrypt as SSL provider on my AWS EC2 server. I found that after a few hours or days, the server starts to throwing the following exception.

    fail: Microsoft.AspNetCore.Server.Kestrel[0]
          Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
    System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
       --- End of inner exception stack trace ---
       at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
       at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
       --- End of inner exception stack trace ---
       at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
       at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Net.Security.SslState.ThrowIfExceptional()
       at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
       at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
       at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
       at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context)
       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ApplyConnectionAdaptersAsync()

How do I deal with this situation?

Environment: microsoft/dotnet:2.1.0-rc1-aspnetcore-runtime-stretch-slim (docker)

**Comment by halter73** [comment]
> error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol

@ClassicDarkChocolate Are you saying once you see this error once, every subsequent attempt to connect to the server fails with this exact error until you restart the server?

@stephentoub Should I move this issue over to the corefx repo?

**Comment by stephentoub** [comment]
@bartonjs?

**Comment by bartonjs** [comment]
The fact that the exception was thrown should mean the error queue is clear after that point.  So if it keeps happening my first guess is some buffering misalignment between the network stream and the TLS stream. (Maybe one or both objects is holding data that didn't get flushed?)

**Comment by halter73** [comment]
AuthenticateAsServerAsync is only called at the very start of the connection. No data is read from or written to network streams established over HTTPS endpoints prior to calling AuthenticateAsServerAsync. I can't think of anything that could possibly cause repeated misalignment at the start of every new connection.

**Comment by ClassicDarkChocolate** [comment]
@halter73 I just checked the logs again. There are total 10 same ssl errors in 29 hours, and one weird SPA error in the middle:

    fail: Microsoft.AspNetCore.Server.Kestrel[13]
          Connection id "0HLDVUEGSPHHS", Request id "0HLDVUEGSPHHS:00000002": An unhandled exception was thrown by the application.
    System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
    Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.
    
       at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
       at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
       at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
       at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by bartonjs** [comment]
@ClassicDarkChocolate Do you see the "SSL23_GET_CLIENT_HELLO:unknown protocol" exception intermittently, or once it happens does it happen forever?

If a client walks up to an OpenSSL-hosted TLS Server endpoint and asserts that it has a major version other than 2 (SSLv2) or 3 (SSLv3, TLS1.0, TLS1.1, TLS1.2, TLS1.3) then this exception will be raised.  So if it is intermittent, and recovers, then it's probably just someone probing the Internet looking for TLS protocol conformance.

(Asserting Major 3, Minor 5 (unassigned) will just naturally fall back to TLS 1.2 (3, 3), but if the major version is out of range it reports it doesn't know what to do about that)

**Comment by ClassicDarkChocolate** [comment]
@bartonjs Yes, it happens intermittently. And the user currently using the site might be me only.

**Comment by georgiosd** [comment]
Is this closed because it's going to be fixed in 2.1.1?
Is there an ETA for this release? I get an application insights alert every 5 minutes :)
