### ISSUE TITLE
Kestrel 2.1 ListenUnixSocket() throws 'Only ListenType.IPEndPoint is supported'

### ISSUE THREAD

**Issue by samsosa** [aspnet/KestrelHttpServer#2634]
The old version works just fine but after update 2.1 an exception is thrown when setting `ListenUnixSocket`.

Using the following config:
`ListenUnixSocket("/var/sockets/kestrel.sock")`

Leads to:
```
System.ArgumentException: Only ListenType.IPEndPoint is supported.
Parameter name: endPointInformation
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.Create(IEndPointInformation endPointInformation, IConnectionDispatcher dispatcher)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at HttpServer.StartAsync() in C:\RefSource\Base\HttpServer\HttpServer.cs:line 266
```

**Comment by Tratcher** [comment]
Duplicate https://github.com/aspnet/KestrelHttpServer/issues/2616
