### ISSUE TITLE
Failing test AddressRegistrationTests.RegisterAddresses_IPv6ScopeId_Success

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2637]
http://aspnetci/viewLog.html?buildId=479149&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3749291059822545939

This is a recent regression on netcoreapp2.2. net461 is not affected. .NET Core likely changed something with System.URI and IPv6 ScopeIds

Possibly picked up by https://github.com/aspnet/Universe/pull/1184#issuecomment-393931025.

```
======= Failed test run #1 ==========
System.Net.Http.HttpRequestException : Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Testing.HttpClientSlim.ReadResponse(Stream stream)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 170
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_IPv6ScopeId_Success(String addressInput, String testUrl) in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test RegisterAddresses_IPv6ScopeId_Success-http://[fe80::9dee:e4c1:f54b:bf7f%14]:0/-http://[fe80::9dee:e4c1:f54b:bf7f%14] at 2018-06-01T05:13:25
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests
| [0.006s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE7FPI6L76O" started.
| [0.007s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLE7FPI6L76O" bad request data: "Invalid Host header: '[fe80::9dee:e4c1:f54b:bf7f%14]:58197'"
| Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid Host header: '[fe80::9dee:e4c1:f54b:bf7f%14]:58197'
|    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason, String detail) in /_/src/Kestrel.Core/BadHttpRequestException.cs:line 129
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.HttpUtilities.ValidateIPv6Host(String hostText) in /_/src/Kestrel.Core/Internal/Infrastructure/HttpUtilities.cs:line 488
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.EnsureHostHeaderExists() in /_/src/Kestrel.Core/Internal/Http/Http1Connection.cs:line 394
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection) in /_/src/Kestrel.Core/Internal/Http/Http1Connection.cs:line 520
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 519
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 455
| [0.011s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE7FPI6L76O" disconnecting.
| [0.011s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLE7FPI6L76O" sending FIN.
| [0.012s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLE7FPI6L76O" stopped.
| [0.012s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.016s] TestLifetime Information: Finished test RegisterAddresses_IPv6ScopeId_Success-http://[fe80::9dee:e4c1:f54b:bf7f%14]:0/-http://[fe80::9dee:e4c1:f54b:bf7f%14] in 0.0147831s
```

**Comment by Tratcher** [comment]
https://github.com/dotnet/corefx/commit/f7a8cf12a89dafccbc98cff160346c2ff3e15ba0

**Comment by halter73** [comment]
@Tratcher Should we file an issue against corefx or do we need to react somehow?

**Comment by Tratcher** [comment]
Debating that now.. We're not using the real HttpClient in these tests, we're using our own HttpClientSlim. The specs are also super ambiguous about if scope IDs should be allowed.

**Comment by halter73** [comment]
So it's a breaking change to Uri then?

**Comment by Tratcher** [comment]
Yes.
