### ISSUE TITLE
BadHttpRequestException: Invalid request target: '/?key=\xD6\xD0\xCE\xC4'

### ISSUE THREAD

**Issue by smokedog2** [aspnet/KestrelHttpServer#2647]
`[09:10:02 INF] Connection id "0HLEAFUMLUVR5" bad request data: "Invalid request target: '/?key=\xD6\xD0\xCE\xC4'"
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request target: '/?key=\xD6\xD0\xCE\xC4'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.ThrowRequestTargetRejected(Span`1 target)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.OnOriginFormTarget(HttpMethod method, HttpVersion version, Span`1 target, Span`1 path, Span`1 query, Span`1 customMethod, Boolean pathEncoded)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.OnStartLine(HttpMethod method, HttpVersion version, Span`1 target, Span`1 path, Span`1 query, Span`1 customMethod, Boolean pathEncoded)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.ParseRequest(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()`

An error occurred If the url contains Chinese in IE

**Comment by Tratcher** [comment]
That url is supposed to be % encoded. Kestrel doesn't support raw unicode.

**Comment by Tratcher** [comment]
No, see: https://github.com/aspnet/KestrelHttpServer/issues/1144

**Comment by benaadams** [comment]
> I can‘t guarantee that users will not enter Chinese directly on url

If via the a browser the browser would automatically url encode it?

**Comment by smokedog2** [comment]
Chrome, Firefox will be encoded, IE can not.

**Comment by mchenx** [comment]
encountered same issue, my fix is to urlencode the url before sending the request
