### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'MemoryPoolBlock'

### ISSUE THREAD

**Issue by qqbuby** [aspnet/KestrelHttpServer#2652]
```txt
2018/06/07 04:47:53 +00:00 [Error].[Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets].[].[]
Unexpected exception in SocketConnection.StartAsync. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MemoryPoolBlock'.
   at System.Buffers.ThrowHelper.ThrowObjectDisposedException(ExceptionArgument argument)
   at System.Buffers.MemoryPoolBlock.Dispose()
   at System.IO.Pipelines.BufferSegment.ResetMemory()
   at System.IO.Pipelines.Pipe.CompletePipe()
   at System.IO.Pipelines.Pipe.CompleteWriter(Exception exception)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.Complete(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.StartAsync(IConnectionDispatcher connectionDispatcher)
```

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/2638
