### ISSUE TITLE
Microsoft.AspNet.Server.KestrelTests failures on CoreCLR on Linux

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#266]
Microsoft.AspNet.Server.KestrelTests.EngineTests.DisconnectingClient(testContext: TestServiceContext { AppLifetime = LifetimeNotImplemented { ApplicationStarted = (throws NotImplementedException), ApplicationStopped = (throws NotImplementedException), ApplicationStopping = (throws NotImplementedException) }, ConnectionFilter = null, DateHeaderValueManager = TestDateHeaderValueManager { }, Log = TestKestrelTrace { }, Memory = MemoryPool { Empty = [...] } }) [FAIL]
      System.PlatformNotSupportedException : Operation is not supported on this platform.
      Stack Trace:
           at System.Net.Sockets.SocketPal.Disconnect(Socket socket, SafeCloseSocket handle, Boolean reuseSocket)
           at System.Net.Sockets.Socket.Disconnect(Boolean reuseSocket)
           at Microsoft.AspNet.Server.KestrelTests.EngineTests.<DisconnectingClient>d__19.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNet.Server.KestrelTests.EngineTests.DisconnectingClient(testContext: TestServiceContext { AppLifetime = LifetimeNotImplemented { ApplicationStarted = (throws NotImplementedException), ApplicationStopped = (throws NotImplementedException), ApplicationStopping = (throws NotImplementedException) }, ConnectionFilter = NoOpConnectionFilter { }, DateHeaderValueManager = TestDateHeaderValueManager { }, Log = TestKestrelTrace { }, Memory = MemoryPool { Empty = [...] } }) [FAIL]
      System.PlatformNotSupportedException : Operation is not supported on this platform.
      Stack Trace:
           at System.Net.Sockets.SocketPal.Disconnect(Socket socket, SafeCloseSocket handle, Boolean reuseSocket)
           at System.Net.Sockets.Socket.Disconnect(Boolean reuseSocket)
           at Microsoft.AspNet.Server.KestrelTests.EngineTests.<DisconnectingClient>d__19.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by cesarbs** [comment]
This affects https://github.com/aspnet/Universe/issues/304.

**Comment by muratg** [comment]
@halter73 This is weird. Do we have another API that we should be using instead? (To make this work on CoreCLR as well?)

**Comment by halter73** [comment]
This is the only place we call Socket.Disconnect: https://github.com/aspnet/KestrelHttpServer/blob/8f0d1179ab8cc636febd8a319ba14008d96d037d/test/Microsoft.AspNet.Server.KestrelTests/EngineTests.cs#L398

By simply removing the call, and letting Dispose disconnect the socket, the test passes on both Windows and Linux.

**Comment by muratg** [comment]
:+1: Let's get that in :)

**Comment by muratg** [comment]
@halter73 will you be able to check this in with any other PR going in soon?
