### ISSUE TITLE
Libuv.Internal.Networking.UvException: Error -4095 EOF end of file 

### ISSUE THREAD

**Issue by rahul24** [aspnet/KestrelHttpServer#2695]
The following exception is being logged by Kestrel when performing HTTP requests to our application hosted in an Azure Web App. All requests were returning 400 HTTP status. The service was running without any problem from quite a while but all of sudden throwing 400 status and after restarting it all resolved. Do we have anywhere the description of error code published (4095)? 

Version: 2.0.8

StackTrace:
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4095 EOF end of file
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerPrimary.PipeReadContext.ReadCallback(UvStreamHandle dispatchPipe, Int32 status)
fail: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[0]
      ListenerPrimary.ReadCallback

**Comment by halter73** [comment]
The EOF UvException log is expected unfortunately in the Azure Web App environment about once every 24 hours, but it's benign.

You can find more details in [this discussion](https://github.com/aspnet/KestrelHttpServer/issues/1965#issuecomment-317120993). In that thread, you'll see most commenters who see this log don't report any other issues. One commenter says they saw nothing but *500* responses after seeing this log, but we weren't able to get enough details to really figure out the root cause. I think since this is the one error that is fairly consistently logged, it gets the blame for some bugs that occur without causing any unusual exceptions to be logged.

A 400 status indicates that invalid requests were received. Do you have any more logs related to the requests that receive the 400 responses? If so, do the logs indicate that Kestrel is responding with a 400 status? It could be IIS that's setting the response status as described [here](https://github.com/aspnet/AspNetCoreModule/issues/189).

**Comment by muratg** [comment]
In this case we can 
- Increase the verbosity level
- Not log the exception itself, just a note

**Comment by mohan513** [comment]
I have been seeing this Exception once a day,@halter73 I have read your comment on the other thread and wondering whether there is fix for  this exception?

**Comment by muratg** [comment]
@mohan513 like mentioned above, this log is benign. We'll be doing what I said above in 3.0.0. For 2.x, you can just ignore this.

**Comment by muratg** [comment]
@mohan513 Not in a supported way.
