### ISSUE TITLE
After implementing DB on EF, Kestrel doesn't start

### ISSUE THREAD

**Issue by tdalia** [aspnet/KestrelHttpServer#2696]
Hello, 
    I am new to ASP.NET Core. Working on a tutorial project where I migrated DB to SQL Express successfully. Now, I am some how not able to start the app at all - even on commenting the Server usage also I get error
```
Using launch settings from C:\Users\tdalia\Documents\CoreTutorial\OdeToFood2\Properties\launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\tdalia\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: HTTPS endpoints can only be configured using KestrelServerOptions.Listen().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAddressAsync(String address, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, List`1 listenOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

Unhandled Exception: System.InvalidOperationException: HTTPS endpoints can only be configured using KestrelServerOptions.Listen().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAddressAsync(String address, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, List`1 listenOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at OdeToFood2.Program.Main(String[] args) in C:\Users\tdalia\Documents\CoreTutorial\OdeToFood2\Program.cs:line 15
Application is shutting down...
```

ConfigureServices method in Startup.cs
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IGreeter, Greeter>();

            // Use of DB
            //services.AddDbContext<OdeToFood2DbContext>(
            //    options => options.UseSqlServer(_configuration.GetConnectionString("OdeToFood2")));
            //services.AddScoped<IRestaurantData, SqlRestaurantData>();

            // Without DB
            services.AddScoped<IRestaurantData, InMemoryRestaurantData>();
            services.AddMvc();

           // A try to overcome the ILogger error
            services.AddHttpsRedirection(options =>
            {
                options.RedirectStatusCode = StatusCodes.Status307TemporaryRedirect;
                options.HttpsPort = 5001;
            });
        }
```
``
appsettings.json  / appsettings.Development.json
{
    "Greeting": "Hello Developer !!", 
    "ConnectionStrings": {
        "OdeToFood2": "Server=localhost\\SQLEXPRESS;Database=OdeToFood2;Trusted_Connection=True;MultipleActiveResultSets=true;"
    }
}
``
.csproj
```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0"></DotNetCliToolReference>
  </ItemGroup>
```

I can't figure how to get rid of the `HTTPS endpoints can only be configured using KestrelServerOptions.Listen().` error that I am facing. I saw couple of settings that can be configured, but don't know which one do I need to configure !!!
FYI, IIS is also installed, but not configured.

Can you please help me resolve this problem. Have been trying since hours.

Thank You,

**Comment by Tratcher** [comment]
Do not mix 2.0 and 2.1, move everything to 2.1.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
