### ISSUE TITLE
Need a better error message when kestrel cannot get the requested port

### ISSUE THREAD

**Issue by Eilon** [aspnet/KestrelHttpServer#2723]
_From @richlander on May 4, 2018 0:14_

#This is what I see when Kestrel cannot get the port I asked for. This is on .NET Core 2.1 RC1 (with a 2.0 app).

```console
pi@raspberrypi:~/dotnet-docker/samples/aspnetapp/aspnetapp $ export ASPNETCORE_URLS=http://+:80
pi@raspberrypi:~/dotnet-docker/samples/aspnetapp/aspnetapp $ dotnet run
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -13 EACCES permission denied
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowIfErrored(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.tcp_bind(UvTcpHandle handle, SockAddr
```

_Copied from original issue: aspnet/Home#3114_

**Comment by muratg** [comment]
The experience has been improved in 2.1.

**Comment by abatishchev** [comment]
Not really. As I mentioned in the initial issue, right now I'm getting the following errors when try to hit locally running Kestrel on port 8020 without admin:

```
System.IO.IOException: 'Authentication failed because the remote party has closed the transport stream.'

System.ComponentModel.Win32Exception: 'The credentials supplied to the package were not recognized'

System.Net.Sockets.SocketException: 'The I/O operation has been aborted because of either a thread exit or an application request'
```

What basically makes no sense. So please open it back.

**Comment by muratg** [comment]
@abatishchev Could you file another issue please? Thanks.

**Comment by abatishchev** [comment]
@Tratcher hi Chris, I have Runtime 2.12 and SDK 2.1.302 installed. However might console app target net462. Does this matter?

I'm getting same exceptions as in https://github.com/aspnet/KestrelHttpServer/issues/2723#issuecomment-412199688.

**Comment by Tratcher** [comment]
If you're using net462 then you need to check your actual package dependencies for the Kestrel package version.

**Comment by abatishchev** [comment]
```
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.1.2" />
<PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="3.2.162" />
```

**Comment by Tratcher** [comment]
2.2.0 preview1
Libuv on port 5000 conflicting with a second Kestrel endpoint:
```
Microsoft.AspNetCore.Connections.AddressInUseException
  HResult=0x80131509
  Message=Error -4091 EADDRINUSE address already in use
  Source=Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv
  StackTrace:
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvTransport.<BindAsync>d__20.MoveNext() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\LibuvTransport.cs:line 116
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Core\KestrelServer.cs:line 160

Inner Exception 1:
UvException: Error -4091 EADDRINUSE address already in use
```
Or Libuv on port 80 conflicting with IIS:
```
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException
  HResult=0x80131500
  Message=Error -4092 EACCES permission denied
  Source=Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv
  StackTrace:
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\Networking\LibuvFunctions.cs:line 83
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowIfErrored(Int32 statusCode) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\Networking\LibuvFunctions.cs:line 74
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\Networking\LibuvFunctions.cs:line 201
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.Bind(IPEndPoint endPoint) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\Networking\UvTcpHandle.cs:line 54
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.ListenTcp(Boolean useFileHandle) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\Listener.cs:line 70
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.CreateListenSocket() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\Listener.cs:line 49
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.<>c.<StartAsync>b__8_0(Listener listener) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\Listener.cs:line 36
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.CallbackAdapter`1.<>c.<.cctor>b__3_1(Object callback, Object state) in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\LibuvThread.cs:line 459
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.DoPostWork() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\LibuvThread.cs:line 383
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerPrimary.<StartAsync>d__15.MoveNext() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\ListenerPrimary.cs:line 62
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvTransport.<BindAsync>d__20.MoveNext() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\LibuvTransport.cs:line 100
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvTransport.<BindAsync>d__20.MoveNext() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Internal\LibuvTransport.cs:line 118
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Core\KestrelServer.cs:line 160
```

Sockets on 5000 conflicting with a second Kestrel endpoint:
```
System.IO.IOException
  HResult=0x80131620
  Message=Failed to bind to address http://127.0.0.1:5000: address already in use.
  Source=Microsoft.AspNetCore.Server.Kestrel.Core
  StackTrace:
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpointAsync>d__3.MoveNext() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Core\Internal\AddressBinder.cs:line 108
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.<BindAsync>d__43.MoveNext() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Core\ListenOptions.cs:line 195
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.<BindAsync>d__2.MoveNext() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Core\Internal\AddressBinder.cs:line 236

Inner Exception 1:
AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted.

Inner Exception 2:
SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```
Sockets on 80 conflicting with IIS:
```
System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=An attempt was made to access a socket in a way forbidden by its access permissions.
  Source=System.Net.Sockets
  StackTrace:
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync() in D:\github\AspNet\KestrelHttpServer\src\Kestrel.Transport.Sockets\SocketTransport.cs:line 95
```

So it depends on the reason for your conflict.

That said, none of these match your last error message which looks to be more about TLS. Is that for a TLS connection?

**Comment by abatishchev** [comment]
I'm getting mine when run Kestrel (on Windows 10 x64) under regular user, not admin.
