### ISSUE TITLE
Flaky test: LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2748]
This test [fails](http://aspnetci/viewLog.html?buildId=514007&buildTypeId=Lite_KestrelStressTest) occasionally with the following error:
```
System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStream>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStringAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.LoggingConnectionAdapterTests.<LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [0.014s] TestLifetime Information: Starting test LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter at 2018-07-24T22:59:13
| [0.138s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [16.079s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [16.079s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests
| [17.132s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFHN4EFEI6B" started.
| [17.141s] LoggingConnectionAdapter Debug: ReadAsync[5] 16 03 03 00 C8 
|                                           \x16\x03\x03\0È
| [17.143s] LoggingConnectionAdapter Debug: ReadAsync[200] 01 00 00 C4 03 03 5B 57 AF 53 A0 07 5D DC BE E1 C6 BD 40 0E F8 00 29 3F 00 79 51 F6 49 CC BA 7B CE 48 3E 6D BF C8 20 38 20 00 00 C3 7B 2C F9 7D C1 97 E4 C3 77 D9 C4 3C 91 49 6F AE A8 5C 8E C3 EE 29 62 CD 60 35 FC 00 34 C0 28 C0 27 C0 14 C0 13 00 9F 00 9E 00 9D 00 9C 00 3D 00 3C 00 35 00 2F C0 2C C0 2B C0 24 C0 23 C0 0A C0 09 00 6A 00 40 00 38 00 32 00 0A 00 13 00 05 00 04 01 00 00 47 00 00 00 0E 00 0C 00 00 09 6C 6F 63 61 6C 68 6F 73 74 00 0A 00 06 00 04 00 17 00 18 00 0B 00 02 01 00 00 0D 00 14 00 12 06 01 06 03 04 01 05 01 02 01 04 03 05 03 02 03 02 02 00 23 00 00 00 17 00 00 FF 01 00 01 00 
|                                           \x01\0\0Ä\x03\x03[W¯S \x07]Ü¾áÆ½@\x0eø\0)?\0yQöIÌº{ÎH>m¿È 8 \0\0Ã{,ù}ÁäÃwÙÄ<Io®¨\Ãî)bÍ`5ü\04À(À'À\x14À\x13\0\0\0\0\0=\0<\05\0/À,À+À$À#À
À    \0j\0@\08\02\0
\0\x13\0\x05\0\x04\x01\0\0G\0\0\0\x0e\0\u000c\0\0    localhost\0
\0\x06\0\x04\0\x17\0\x18\0\u000b\0\x02\x01\0\0
\0\x14\0\x12\x06\x01\x06\x03\x04\x01\x05\x01\x02\x01\x04\x03\x05\x03\x02\x03\x02\x02\0#\0\0\0\x17\0\0ÿ\x01\0\x01\0
| [17.144s] Microsoft.AspNetCore.Server.Kestrel Error: Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
| System.AggregateException: One or more errors occurred. ---> System.AggregateException: An error occurred while writing to logger(s). ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
|    at Serilog.Parsing.MessageTemplateParser.ParsePropertyToken(Int32 startAt, String messageTemplate, Int32& next)
|    at Serilog.Parsing.MessageTemplateParser.<Tokenize>d__1.MoveNext()
|    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
|    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
|    at Serilog.Events.MessageTemplate..ctor(String text, IEnumerable`1 tokens)
|    at Serilog.Parsing.MessageTemplateParser.Parse(String messageTemplate)
|    at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exce
...
```

**Comment by JunTaoLuo** [comment]
I haven't seen this failure for a month and it's now run as an InMemory functional test which should have improved reliability.
