### ISSUE TITLE
Flaky test: ClosingConnectionMidChunkPrefixThrows

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2752]
This test [fails](http://aspnetci/viewLog.html?buildId=514205&buildTypeId=Releases_21Public_Win2012) occasionally with the following error:
```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: 
Actual:   HTTP/1.1 200 OK\r\nDate: Wed, 25 Jul 2018 0···
          ↑ (pos 0)
   at Microsoft.AspNetCore.Testing.TestConnection.<ReceiveEnd>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ChunkedRequestTests.<ClosingConnectionMidChunkPrefixThrows>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by Tratcher** [comment]
@halter73 this should have been fixed by https://github.com/aspnet/KestrelHttpServer/pull/2734 right?

**Comment by halter73** [comment]
Correct. It looks like the failed test was from [this commit](https://github.com/aspnet/KestrelHttpServer/commits/85bf01da82a2e6fd20c7dd3b9693468fcb2552e2) which predates [the fix](https://github.com/aspnet/KestrelHttpServer/commits/603cd03bfa7f8efeeb747e926cee1658be12004b).
