### ISSUE TITLE
Flaky test: CanRebindToMultipleEndPoints

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2754]
This test [fails](http://aspnetci/viewLog.html?buildId=515652&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
System.IO.IOException : Failed to bind to address http://127.0.0.1:63406: address already in use.
---- Microsoft.AspNetCore.Connections.AddressInUseException : Only one usage of each socket address (protocol/network address/port) is normally permitted.
-------- System.Net.Sockets.SocketException : Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 108
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context) in /_/src/Kestrel.Core/ListenOptions.cs:line 196
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 234
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 46
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 162
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.CanRebindToMultipleEndPoints() in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 768
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync() in /_/src/Kestrel.Transport.Sockets/SocketTransport.cs:line 99
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in /_/src/Kestrel.Core/KestrelServer.cs:line 159
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context) in /_/src/Kestrel.Core/Internal/AddressBinder.cs:line 104
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync() in /_/src/Kestrel.Transport.Sockets/SocketTransport.cs:line 95
------- Stdout: -------
| [0.002s] TestLifetime Information: Starting test CanRebindToMultipleEndPoints at 2018-07-26T01:53:08
| [0.010s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.012s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.012s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests
| [0.016s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJA3FAJCN" started.
| [0.016s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.0 GET http://127.0.0.1:63406/  
| [0.017s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.6529ms 200 
| [0.017s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJA3FAJCN" disconnecting.
| [0.017s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLFIJA3FAJCN" sending FIN.
| [0.017s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJA3FAJCN" stopped.
| [0.020s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJA3FAJCO" started.
| [0.020s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.0 GET http://[::1]:63406/  
| [0.021s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.2822ms 200 
| [0.021s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJA3FAJCO" disconnecting.
| [0.021s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLFIJA3FAJCO" sending FIN.
| [0.021s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.021s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJA3FAJCO" stopped.
| [0.026s] TestLifetime Information: Finished test CanRebindToMultipleEndPoints in 0.0243292s
```

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@halter73 - please take a look at this flaky test ASAP (or re-assign).

**Comment by ryanbrandenburg** [comment]
CanRebindToMultipleEndPoints [failed again](http://aspnetci/viewLog.html?buildId=516243&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by halter73** [comment]
I just finished talking to @natemcmaster about this. The current plan of action is to move AddressRegistrationTests into their own test assembly and to not run them in parallel with any other tests.

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed again](http://aspnetci/viewLog.html?buildId=516438&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanRebindToMultipleEndPoints [failed again](http://aspnetci/viewLog.html?buildId=516729&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@halter73 thanks that sounds like a reasonable plan.

**Comment by ryanbrandenburg** [comment]
CanRebindToMultipleEndPoints [failed again](http://aspnetci/viewLog.html?buildId=517539&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed again](http://aspnetci/viewLog.html?buildId=518373&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanRebindToMultipleEndPoints [failed again](http://aspnetci/viewLog.html?buildId=519473&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanRebindToMultipleEndPoints [failed again](http://aspnetci/viewLog.html?buildId=519454&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanRebindToMultipleEndPoints [failed with about the same error](http://aspnetci/viewLog.html?buildId=522255&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by fpiazza99** [comment]
Just upgraded to .netcore 2.1.2 and now getting this error. I have three test classes [TestFixtures] and each one starts a webhost. The first fixture runs fine, but all subsequent fixtures fail. I suspect because each start a separate webhost and all have the same connection binding 127.0.0.1:5000

**Comment by ryanbrandenburg** [comment]
CanRebindToMultipleEndPoints [failed with about the same error](http://aspnetci/viewLog.html?buildId=523259&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanRebindToMultipleEndPoints [failed with about the same error](http://aspnetci/viewLog.html?buildId=524842&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed with about the same error](http://aspnetci/viewLog.html?buildId=524909&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.
