### ISSUE TITLE
Flaky test: DoesNotThrowOnFin

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2757]
This test [fails](http://aspnetci/viewLog.html?buildId=516438&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
Microsoft.AspNetCore.Connections.ConnectionResetException : Error -4077 ECONNRESET connection reset by peer
---- Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException : Error -4077 ECONNRESET connection reset by peer
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.CopyToAsync(Stream destination, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 157
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.UpgradeTests.<>c__DisplayClass8_0.<<DoesNotThrowOnFin>b__0>d.MoveNext() in /_/test/Kestrel.FunctionalTests/UpgradeTests.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.UpgradeTests.DoesNotThrowOnFin() in /_/test/Kestrel.FunctionalTests/UpgradeTests.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test DoesNotThrowOnFin at 2018-07-27T00:15:06
| [0.009s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.018s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.018s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [0.020s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFJAO0AVU8J" started.
| [0.020s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  
| [0.140s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFJAO0AVU8J" reset.
| [0.140s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFJAO0AVU8J" disconnecting.
| [0.141s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFJAO0AVU8J" sending FIN.
| [0.144s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.144s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLFJAO0AVU8J", Request id "0HLFJAO0AVU8J:00000001": An unhandled exception was thrown by the application.
| Microsoft.AspNetCore.Connections.ConnectionResetException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
|    --- End of inner exception stack trace ---
|    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
|    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.CopyToAsync(Stream destination, CancellationToken cancellationToken)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 157
|    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.UpgradeTests.<>c__DisplayClass8_0.<<DoesNotThrowOnFin>b__0>d.MoveNext() in /_/test/Kestrel.FunctionalTests/UpgradeTests.cs:line 314
| --- End of stack trace from previous location where exception was thrown ---
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 555
| [0.149s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 128.7423ms 101 
| [0.149s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFJAO0AVU8J" stopped.
| [0.165s] TestLifetime Information: Finished test DoesNotThrowOnFin in 0.1639264s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed again](http://aspnetci/viewLog.html?buildId=516729&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@halter73 , a special delivery for you.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed again](http://aspnetci/viewLog.html?buildId=517251&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed again](http://aspnetci/viewLog.html?buildId=517893&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed again](http://aspnetci/viewLog.html?buildId=517546&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed again](http://aspnetci/viewLog.html?buildId=517539&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed with about the same error](http://aspnetci/viewLog.html?buildId=520521&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed with about the same error](http://aspnetci/viewLog.html?buildId=520647&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed with about the same error](http://aspnetci/viewLog.html?buildId=522255&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed with about the same error](http://aspnetci/viewLog.html?buildId=525064&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.
