### ISSUE TITLE
Unexpected end of request content during multipart/form-data upload

### ISSUE THREAD

**Issue by simonmsims** [aspnet/KestrelHttpServer#2781]
We're using AspNetCore 2.1.2 on production where multipart/form-data uploads are sometimes (~1% out all the upload requests) failing with following exception:

```
Unexpected end of request content.

Exception: Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException

source: Microsoft.AspNetCore.Server.Kestrel.Core
target: Throw
module: Microsoft.AspNetCore.Server.Kestrel.Core.dll

   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.BufferedReadStream.EnsureBufferedAsync(Int32 minCount, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync():

{"method":"POST","path":"/api/v1/file","query":"","accept":"application/json, text/plain, */*","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) LoopEmail/4.2.0-beta2 Chrome/59.0.3071.115 Electron/1.8.3 Safari/537.36"}: {"received":2503398,"checkpoint-rendered":0}
ENDRQ: HTTP 500 /api/v1/file 
size=0

Checkpoints:
    (start)
0ms:
    rendered
125782ms:
    awaited
0ms:
    (log)

at: LogMiddleware.Invoke:210
```

Also unable to reproduce it the lab using tight upload loops with both small and large test files.

**Comment by Tratcher** [comment]
That's the expected error when the client disconnects before finishing the upload.

**Comment by simonmsims** [comment]
Ok, then I suppose we'll just update logging on our side to treat it as such, thanks.
