### ISSUE TITLE
Invalid request line: '/company/916/projects HTTP/1.1\x0D\x0A'

### ISSUE THREAD

**Issue by youhou71** [aspnet/KestrelHttpServer#2804]
Hello,

We're experiencing some strange behavior a couple of times (or less) per day.

___When we receive a bad request, we receive 5 to 10 in a short time___

## Description

We randomly get a bad request when calling several function with the detail:

```
Invalid request line: '/xxxxxx/id/xxxxxx HTTP/1.1\x0D\x0A'
```

The associated stack trace:

```
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectRequestLine(Byte* requestLine, Int32 length)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.GetUnknownMethod(Byte* data, Int32 length, Int32& methodLength)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.IHttpParser<TRequestHandler>.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

## Technical informations

* The client that calls the function is a .NET Framework 4.6 console application
* The server is a .NET Core 2.1 application

### Server

```csharp
[Route("company")]
[Authorize]
public class CompanyController : Controller
{
    [HttpGet("{id}/projects")]
    [ProducesResponseType(typeof(List<DTO.APIEntity.CRM_Project_Lite>), 200)]
    [ProducesResponseType(typeof(string), 404)]
    public IActionResult GetProjects(int id)
    {
        /*...*/
    }
}
```

### Client

We init the `APIClient` class into a session variable for out ASP. Net client application.

```csharp
public class APIClient
{
    string s_BaseUrl;
    public static HttpClient _client = new HttpClient();

    protected HttpResponseMessage get(string RelativeUrl)
    {
        string s_url = (s_BaseUrl + RelativeUrl).Replace("+", "%2B");
        try
        {
            return _client.GetAsync(s_url).Result;
        }
        catch (Exception e)
        {
            /* Exception management */
            /* ... */
            throw;
        }
    }

    public List<CFAST.CRM.DTO.APIEntity.CRM_Project_Lite> Company_GetProjects(int company_id)
    {
        var resp = get(string.Format(@"/company/{0}/projects", company_id));
        return resp.Content.ReadAsAsync<List<CFAST.CRM.DTO.APIEntity.CRM_Project_Lite>>().Result;
    }
}
```

Do you have any clues of the problem ?

**Comment by Tratcher** [comment]
Similar bug: https://github.com/aspnet/KestrelHttpServer/issues/1580, but that was fixed in 2.0.

**Comment by youhou71** [comment]
Indeed, I had read this issue.
What's weird is that my application references `Microsoft.AspNetCore.All` in version "2.1.2" which itself references `Microsoft.AspNetCore.Server.Kestrel.Core` in version "2.1.2".

Therefore, I do not understand.
Should I add the `Microsoft.AspNetCore.Server.Kestrel.Core` Nuget directly to my project in addition to` Microsoft.AspNetCore.All` ?

**Comment by Tratcher** [comment]
No, I only pointed it out as similar symptoms.

There's not enough information here to debug the problem. Ideally you'd be able to reproduce it in a small project you could share. Failing that, any diagnostics you could collect like logs, network traces, dumps, etc. might be useful.

**Comment by muratg** [comment]
@youhou71 Let us know when you can add a GitHub repo?  Thanks.

**Comment by youhou71** [comment]
I could send you a sample project Monday but I'm not sure if I can reproduce the bug.

**Comment by davidfowl** [comment]
We’ve had http parsing issues in the past, the best thing to help narrow it down would be to capture a network trace when it happens. See 
https://github.com/aspnet/KestrelHttpServer/issues/2151 for a similar issue

**Comment by youhou71** [comment]
Here is one of the logs provided by ElasticSearch thanks to the class "BadRequestDiagnosticAdapter"

File: [log.txt](https://github.com/aspnet/KestrelHttpServer/files/2282873/log.txt)

**Comment by youhou71** [comment]
These two PUT requests do not need a body in my case because the goal is just to change a boolean in the database.
Should I run a test passing the value of "HttpClient.DefaultRequestHeaders.ExpectContinue" to "false" on my .Net Framework client ?

**Comment by Tratcher** [comment]
If they do not need a body then why do they say they have one? Declaring a body (content-length) but failing to send it breaks the protocol.

Why are you trying to change your .NET HttpClient? Those requests claim to be coming from the Go-http-client. Is that true or are you setting the user-agent header on your .NET HttpClient?

**Comment by youhou71** [comment]
Actually, my client application is an ASP.Net Framework application deployed on IIS. My server application (API) is an ASP.Net Core 2.1 application deployed in a Docker on a Linux.

The infrastructure is not my responsibility and I do not have access to this information for the moment.
If I make sure to stop sending the body if it is not needed, do you think it will solve the problem?

If I modify the call of my API in this way, the body should not be sent anymore?

```csharp

// body:        This is my body (object)
// _client:      My static HttpClient

var response = body != null ? _client.PutAsJsonAsync(s_url, body).Result : _client.PutAsync(s_url, new StringContent("")).Result;
```

**Comment by muratg** [comment]
> If I make sure to stop sending the body if it is not needed, do you think it will solve the problem?

Yes, I recommend giving this a try.

**Comment by youhou71** [comment]
Ok, I'll give it a try with these settings and I'll come back to you with new info as soon as I get it.

**Comment by Tratcher** [comment]
```
PUT /project/306/technical-validation HTTP/1.1\r\nHost: v2.cfast.fr\r\nUser-Agent: Go-http-client/1.1\r\nContent-Length: 4\r\nAuthorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkzQTlDRDkxNEJBRDVDRDRFNzIzMjIxOTk4NzIxM0JCODNFNTMzNDgiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJrNm5Oa1V1dFhOVG5JeUlabUhJVHU0UGxNMGcifQ.eyJuYmYiOjE1MzQxNDAzNDIsImV4cCI6MTUzNDE3NjM0MiwiaXNzIjoiaHR0cHM6Ly92Mi5jZmFzdC5mci9hdXRoIiwiYXVkIjpbImh0dHBzOi8vdjIuY2Zhc3QuZnIvYXV0aC9yZXNvdXJjZXMiLCJhdXRoIiwiY2Zhc3QiLCJjcGsiLCJjcm0iLCJlbWFpbGVyIiwiaWRlbnRpdHkiLCJvcmRlciJdLCJjbGllbnRfaWQiOiJjZmFzdC53ZWIiLCJzdWIiOiJTdGVwaGFuSSIsImF1dGhfdGltZSI6MTUzNDE0MDM0MiwiaWRwIjoibG9jYWwiLCJlbWFpbCI6InN0ZXBoYW4ucGVycmluQG9wdGlvbnN0ZWxlY29tLmZyIiwibG9jYWxlIjoiZnItRlIiLCJ6b25laW5mbyI6IkV1cm9wZS9QYXJpcyIsIm9yZyI6IklOIiwicm9sZSI6WyJhdXRoLmFkbU9yZyIsImNwayIsImVtYWlsIl0sInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJhdXRoIiwiY2Zhc3QiLCJjcGsiLCJjcm0iLCJlbWFpbGVyIiwiaWRlbnRpdHkiLCJvcmRlciIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJwYXNzd29yZCJdfQ.ZuSNEBIwtaftZi0wxanQNsGOxn3ssGB632XTbfT90TqHN_rqLmLz9ieOHhR-M-NW4_PWRWEy3xFEF1b9QVtemAnbK1IK_-XfmnN07LZU2jpUvBcI9ZiFWC2o0wArAmBryWm67TpNXUKruhPwMJYApM8bbldSuoM5pbt9XN1Ljw9d63kH_vkyeMuYop5xhR41GHvI7l0jU85mLkr1BLEDWW84DQ0TuHikR_otc2hIkWL-OKv3wYZrtMcdNaQlq9BCx_QKFbsJ_eOslkq76ROnx8e23V1tsBdfW6B3M6x2rddmp9KpeJACDQjdaCFFb1myJyF1IQjhdKiO518M8cxKCo-03HwbIP-LMsZxJrP3runtQTZR7uO0ESwSeYigHMyEqyVBPSlmhdSo6l9E6giceLJ22Dz4fEOMfLQUOCEZ98DxlmhAqGeQS3M-eNe0qlkIFEzJwvbv-xLnqH5CW5ODGfXKyd0HRMCYC4BCuqbGoUlDzM_oavgA34WrmJvYoy1REjOgXKC-Yt_Zqj7YCSxXIGT23oIwr7SWpAQ0TEFqGYFNVAhhHbDZjSFZ8UQa3bIwrDnM6I5OdAfGukPXnYBTYtVoyDU3Ce1P_NTPH2kYcSQT-0HtpLEO9aZqLEU4wyyHMKN0MXjchEog3j8oSM3kEY8uQ2cQX-audnZ1TuSJQ9w\r\nContent-Type: application/json; charset=utf-8\r\nExpect: 100-continue\r\nX-Forwarded-For: 10.47.128.4\r\nX-Forwarded-Host: v2.cfast.fr\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Prefix: /api/crm\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Server: 6dedfcc9a37f\r\nX-Real-Ip: 10.47.128.4\r\nAccept-Encoding: gzip\r\n\r\n

PUT /project/306/billing-validation HTTP/1.1\r\nHost: v2.cfast.fr\r\nUser-Agent: Go-http-client/1.1\r\nContent-Length: 4\r\nAuthorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjkzQTlDRDkxNEJBRDVDRDRFNzIzMjIxOTk4NzIxM0JCODNFNTMzNDgiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJrNm5Oa1V1dFhOVG5JeUlabUhJVHU0UGxNMGcifQ.eyJuYmYiOjE1MzQxNDAzNDIsImV4cCI6MTUzNDE3NjM0MiwiaXNzIjoiaHR0cHM6Ly92Mi5jZmFzdC5mci9hdXRoIiwiYXVkIjpbImh0dHBzOi8vdjIuY2Zhc3QuZnIvYXV0aC9yZXNvdXJjZXMiLCJhdXRoIiwiY2Zhc3QiLCJjcGsiLCJjcm0iLCJlbWFpbGVyIiwiaWRlbnRpdHkiLCJvcmRlciJdLCJjbGllbnRfaWQiOiJjZmFzdC53ZWIiLCJzdWIiOiJTdGVwaGFuSSIsImF1dGhfdGltZSI6MTUzNDE0MDM0MiwiaWRwIjoibG9jYWwiLCJlbWFpbCI6InN0ZXBoYW4ucGVycmluQG9wdGlvbnN0ZWxlY29tLmZyIiwibG9jYWxlIjoiZnItRlIiLCJ6b25laW5mbyI6IkV1cm9wZS9QYXJpcyIsIm9yZyI6IklOIiwicm9sZSI6WyJhdXRoLmFkbU9yZyIsImNwayIsImVtYWlsIl0sInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJhdXRoIiwiY2Zhc3QiLCJjcGsiLCJjcm0iLCJlbWFpbGVyIiwiaWRlbnRpdHkiLCJvcmRlciIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJwYXNzd29yZCJdfQ.ZuSNEBIwtaftZi0wxanQNsGOxn3ssGB632XTbfT90TqHN_rqLmLz9ieOHhR-M-NW4_PWRWEy3xFEF1b9QVtemAnbK1IK_-XfmnN07LZU2jpUvBcI9ZiFWC2o0wArAmBryWm67TpNXUKruhPwMJYApM8bbldSuoM5pbt9XN1Ljw9d63kH_vkyeMuYop5xhR41GHvI7l0jU85mLkr1BLEDWW84DQ0TuHikR_otc2hIkWL-OKv3wYZrtMcdNaQlq9BCx_QKFbsJ_eOslkq76ROnx8e23V1tsBdfW6B3M6x2rddmp9KpeJACDQjdaCFFb1myJyF1IQjhdKiO518M8cxKCo-03HwbIP-LMsZxJrP3runtQTZR7uO0ESwSeYigHMyEqyVBPSlmhdSo6l9E6giceLJ22Dz4fEOMfLQUOCEZ98DxlmhAqGeQS3M-eNe0qlkIFEzJwvbv-xLnqH5CW5ODGfXKyd0HRMCYC4BCuqbGoUlDzM_oavgA34WrmJvYoy1REjOgXKC-Yt_Zqj7YCSxXIGT23oIwr7SWpAQ0TEFqGYFNVAhhHbDZjSFZ8UQa3bIwrDnM6I5OdAfGukPXnYBTYtVoyDU3Ce1P_NTPH2kYcSQT-0HtpLEO9aZqLEU4wyyHMKN0MXjchEog3j8oSM3kEY8uQ2cQX-audnZ1TuSJQ9w\r\nContent-Type: application/json; charset=utf-8\r\nExpect: 100-continue\r\nX-Forwarded-For: 10.47.128.4\r\nX-Forwarded-Host: v2.cfast.fr\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Prefix: /api/crm\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Server: 6dedfcc9a37f\r\nX-Real-Ip: 10.47.128.4\r\nAccept-Encoding: gzip\r\n\r\n
```

You still have me confused. Is your app setting `User-Agent: Go-http-client`, or is that coming from a different client? .NET's HttpClient handles 100 Continue's correctly and you shouldn't have to change anything.

**Comment by youhou71** [comment]
Actually, all I know is that we use nginx as load-balancer and that our applications are nested in dockers.

The person who manages all that part is on leave, so I can not ask him for advice.
Can nginx be the origin of 100-continuous?

**Comment by Tratcher** [comment]
Unlikely

**Comment by youhou71** [comment]
I did not have any new errors after the following manipulations:
* Set the value of `HttpClient.DefaultRequestHeaders.ExpectContinue` to "false" on my .Net Framework client
* Set the value of `System.Net.ServicePointManager.Expect100Continue` to "false"
* Change the method if the body is null to:

```csharp

// body:         This is my body (object)
// _client:      My static HttpClient

var response = body != null ? _client.PutAsJsonAsync(s_url, body).Result : _client.PutAsync(s_url, new StringContent("")).Result;
```

Therefore, I will wait for the return of my sys admin (the 27th of August) to tell him about this problem and try to unravel this story of `User-Agent: Go-http-client`.

**Comment by muratg** [comment]
@youhou71 Closing this. Please reopen (or file another one) if you have evidence that you're not using a buggy client.
