### ISSUE TITLE
Error -32 EPIPE broken pipe

### ISSUE THREAD

**Issue by dopare** [aspnet/KestrelHttpServer#283]
Getting such an error after first request

warning : [Microsoft.AspNet.Server.Kestrel] Connection processing ended abnormally
Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -32 EPIPE broken pipe
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.Microsoft.AspNet.Server.Kestrel.Http.ISocketOutput.Write(ArraySegment1 buffer, Boolean immediate)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.WriteChunkedResponseSuffix()
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.ProduceEnd(Exception ex)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__77.MoveNext()

running on OS X 
1.0.0-beta8          coreclr x64          darwin

**Comment by muratg** [comment]
@dopare Does this still repro with RC1/RC2 bits?   Also, what client are you using?

**Comment by dopare** [comment]
@muratg cannot reproduce on RC1, thanks, closing the issue.

**Comment by muratg** [comment]
Thanks @dopare!
