### ISSUE TITLE
Tests aborted on linux and OSX

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2876]
Seen this a few times now

```
  Starting test group: UnitTests/netcoreapp2.2
  Microsoft (R) Test Execution Command Line Tool Version 15.7.0
  Copyright (c) Microsoft Corporation.  All rights reserved.

  Starting test execution, please wait...
  [xUnit.net 00:00:01.30]     ServerPipeListenForConnections [FAIL]
  [xUnit.net 00:00:01.32]     ServerPipeDispatchConnections [FAIL]
  [xUnit.net 00:00:01.33]     InitAndCloseServerPipe [FAIL]
  The active test run was aborted. Reason: Assertion Failed
  ThreadId is incorrect
     at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvMemory.Validate(Boolean closed) in /kestrel/src/Kestrel.Transport.Libuv/Internal/Networking/UvMemory.cs:line 84
     at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_close(UvLoopHandle handle) in /kestrel/src/Kestrel.Transport.Libuv/Internal/Networking/LibuvFunctions.cs:line 111
     at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.ReleaseHandle() in /kestrel/src/Kestrel.Transport.Libuv/Internal/Networking/UvLoopHandle.cs:line 48
     at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
     at System.Runtime.InteropServices.SafeHandle.Finalize()

  [xUnit.net 00:00:20.89]     ContentLength_Received_MultipleDataFramesOverSize_Reset [SKIP]
  Skipped  ContentLength_Received_MultipleDataFramesOverSize_Reset

  Total tests: Unknown. Passed: 6427. Failed: 0. Skipped: 1.
  Test execution time: 45.0423 Seconds
  Test Run Aborted.
```

**Comment by halter73** [comment]
I've never seen this before. This would have to be from the libuv unit test project which hasn't been touched in a very long time.

@davidfowl Can you capture a stack trace in the UvLoopHandle constructor and before calling loop_close in ReleaseHandle print the stack trace `if (ThreadId == Thread.CurrentThread.ManagedThreadId)`.

**Comment by muratg** [comment]
Hi @davidfowl. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by davidfowl** [comment]
Thanks for that generic text @muratg :trollface:
