### ISSUE TITLE
Test failure: HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/KestrelHttpServer#2894]
This test [fails](http://aspnetci/viewLog.html?buildId=546543&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
System.AggregateException : An error occurred while writing to logger(s). (Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. )
---- System.Exception : Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs:line 165
   at Microsoft.AspNetCore.Testing.CompositeKestrelTrace.NotAllConnectionsClosedGracefully() in /_/test/shared/CompositeKestrelTrace.cs:line 100
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 215
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 215
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.Dispose() in /_/src/Kestrel.Core/KestrelServer.cs:line 223
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer.Dispose() in /_/test/shared/TransportTestHelpers/TestServer.cs:line 123
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate() in /_/test/Kestrel.Transport.FunctionalTests/ResponseTests.cs:line 630
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 74
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
------- Stdout: -------
| [0.007s] TestLifetime Information: Starting test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate at 2018-09-06T23:31:37
| [111.630s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [112.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [112.051s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [112.052s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 65111
| [112.859s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGKA2BSLG05" started.
| [125.870s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLGKA2BSLG05" aborted.
| [125.871s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLGKA2BSLG05" sending FIN.
| [126.026s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [131.362s] Microsoft.AspNetCore.Server.Kestrel Debug: Some connections failed to close gracefully during server shutdown.
| [131.367s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Server shutdown exception
| System.AggregateException: An error occurred while writing to logger(s). (Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. ) ---> System.Exception: Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
|    at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 74
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
|    --- End of inner exception stack trace ---
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
|    at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs:line 165
|    at Microsoft.AspNetCore.Testing.CompositeKestrelTrace.NotAllConnectionsClosedGracefully() in /_/test/shared/CompositeKestrelTrace.cs:line 100
|    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 215
|    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StopAsync(CancellationToken cancellationToken)
|    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
| ---> (Inner Exception #0) System.Exception: Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
|    at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 74
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
| [140.581s] TestLifetime Information: Finished test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment]
Rate failure?  @Tratcher @halter73

**Comment by Tratcher** [comment]
Graceful shutdown failure. We're tracking a few of those.

**Comment by halter73** [comment]
Weird that the test took 111.630s to even start.

**Comment by JunTaoLuo** [comment]
This doesn't seem to have failed in a long time now and some changes were made to the test in https://github.com/aspnet/KestrelHttpServer/pull/2992/files. Closing now and we'll let RaaS file new issues if it fails again.
