### ISSUE TITLE
Flaky test: RequestsCanBeAbortedMidRead

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2897]
```
09:41:50   [xUnit.net 00:00:46.55]     RequestsCanBeAbortedMidRead(listenOptions: http://127.0.0.1:0) [FAIL]
09:41:50   Failed   RequestsCanBeAbortedMidRead(listenOptions: http://127.0.0.1:0)
09:41:50   Error Message:
09:41:50    System.TimeoutException : The operation at /_/test/shared/TaskTimeoutExtensions.cs:12 timed out after reaching the limit of 30000ms.
09:41:50   Stack Trace:
09:41:50      at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
09:41:50      at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.RequestsCanBeAbortedMidRead(ListenOptions listenOptions) in /_/test/Kestrel.Transport.FunctionalTests/RequestTests.cs:line 661
09:41:50   --- End of stack trace from previous location where exception was thrown ---
09:41:50   Standard Output Messages:
09:41:50    | [0.000s] TestLifetime Information: Starting test RequestsCanBeAbortedMidRead-http://127.0.0.1:0 at 2018-09-06T16:41:19
09:41:50    | [0.001s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
09:41:50    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
09:41:50    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
09:41:50    | [0.003s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 40666
09:41:50    | [0.003s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK2U58SPF9" started.
09:41:50    | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http:///  5
09:41:50    | [0.005s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK2U58SPF9" completed keep alive response.
09:41:50    | [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.3423ms 200 
09:41:50    | [0.005s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK2U58SPF9", Request id "0HLGK2U58SPF9:00000001": started reading request body.
09:41:50    | [0.005s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK2U58SPF9", Request id "0HLGK2U58SPF9:00000001": done reading request body.
09:41:50    | [0.005s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLGK2U58SPF9", Request id "0HLGK2U58SPF9:00000001": the application completed without reading the entire request body.
09:41:50    | [0.051s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http:///  5
09:41:50    | [0.052s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK2U58SPF9", Request id "0HLGK2U58SPF9:00000002": started reading request body.
09:41:50    | [0.052s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLGK2U58SPF9", Request id "0HLGK2U58SPF9:00000002": the application aborted the connection.
09:41:50    | [0.052s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK2U58SPF9" disconnecting.
09:41:50    | [0.052s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLGK2U58SPF9" sending FIN.
09:41:50    | [0.052s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK2U58SPF9", Request id "0HLGK2U58SPF9:00000002": done reading request body.
09:41:50    | [0.053s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLGK2U58SPF9", Request id "0HLGK2U58SPF9:00000002": An unhandled exception was thrown by the application.
09:41:50    | System.Threading.Tasks.TaskCanceledException: The request was aborted ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
09:41:50    |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
09:41:50    |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
09:41:50    |    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
09:41:50    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.RawStream.ReadAsyncInternal(Memory`1 destination) in /_/src/Kestrel.Core/Adapter/Internal/RawStream.cs:line 145
09:41:50    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.AdaptedPipeline.ReadInputAsync(Stream stream) in /_/src/Kestrel.Core/Adapter/Internal/AdaptedPipeline.cs:line 170
09:41:50    |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
09:41:50    |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
09:41:50    |    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
09:41:50    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync() in /_/src/Kestrel.Core/Internal/Http/Http1MessageBody.cs:line 130
09:41:50    |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
09:41:50    |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
09:41:50    |    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
09:41:50    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.CopyToAsync(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/MessageBody.cs:line 86
09:41:50    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 157
09:41:50    |    --- End of inner exception stack trace ---
09:41:50    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 161
09:41:50    |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<>c__DisplayClass18_0.<<RequestsCanBeAbortedMidRead>b__2>d.MoveNext() in /_/test/Kestrel.Transport.FunctionalTests/RequestTests.cs:line 619
09:41:50    | --- End of stack trace from previous location where exception was thrown ---
09:41:50    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 542
09:41:50    | [0.055s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 3.7932ms 0 
09:41:50    | [0.055s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK2U58SPF9" stopped.
09:41:50    | [0.059s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
09:41:50    | [30.060s] TestLifetime Information: Finished test RequestsCanBeAbortedMidRead-http://127.0.0.1:0 in 30.0590539s
```

This might be due to my changes to respect the cancellation token.

cc @halter73

**Comment by davidfowl** [comment]
Here's another trace from VSTS

```
 Failed   RequestsCanBeAbortedMidRead(listenOptions: http://127.0.0.1:0)
2018-09-06T18:54:15.6842196Z   Error Message:
2018-09-06T18:54:15.6844284Z    System.TimeoutException : The operation at /_/test/shared/TaskTimeoutExtensions.cs:12 timed out after reaching the limit of 30000ms.
2018-09-06T18:54:15.6859020Z   Stack Trace:
2018-09-06T18:54:15.6862195Z      at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
2018-09-06T18:54:15.6862590Z      at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.RequestsCanBeAbortedMidRead(ListenOptions listenOptions) in /_/test/Kestrel.Transport.FunctionalTests/RequestTests.cs:line 661
2018-09-06T18:54:15.6865644Z   --- End of stack trace from previous location where exception was thrown ---
2018-09-06T18:54:15.6868004Z   Standard Output Messages:
2018-09-06T18:54:15.6871069Z    | [0.000s] TestLifetime Information: Starting test RequestsCanBeAbortedMidRead-http://127.0.0.1:0 at 2018-09-06T18:53:45
2018-09-06T18:54:15.6873431Z    | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
2018-09-06T18:54:15.6876195Z    | [0.007s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
2018-09-06T18:54:15.6878770Z    | [0.007s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
2018-09-06T18:54:15.6881592Z    | [0.007s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 3268
2018-09-06T18:54:15.6885674Z    | [0.008s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK581T2N09" started.
2018-09-06T18:54:15.6888070Z    | [0.009s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http:///  5
2018-09-06T18:54:15.6890465Z    | [0.030s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK581T2N09" completed keep alive response.
2018-09-06T18:54:15.6893240Z    | [0.030s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 21.5323ms 200 
2018-09-06T18:54:15.6893578Z    | [0.030s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK581T2N09", Request id "0HLGK581T2N09:00000001": started reading request body.
2018-09-06T18:54:15.6897718Z    | [0.031s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK581T2N09", Request id "0HLGK581T2N09:00000001": done reading request body.
2018-09-06T18:54:15.6898142Z    | [0.032s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLGK581T2N09", Request id "0HLGK581T2N09:00000001": the application completed without reading the entire request body.
2018-09-06T18:54:15.6898550Z    | [0.034s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http:///  5
2018-09-06T18:54:15.6902035Z    | [0.034s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK581T2N09", Request id "0HLGK581T2N09:00000002": started reading request body.
2018-09-06T18:54:15.6902422Z    | [0.035s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLGK581T2N09", Request id "0HLGK581T2N09:00000002": the application aborted the connection.
2018-09-06T18:54:15.6902741Z    | [0.035s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK581T2N09" disconnecting.
2018-09-06T18:54:15.6903955Z    | [0.035s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLGK581T2N09" sending FIN.
2018-09-06T18:54:15.6904272Z    | [0.035s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
2018-09-06T18:54:15.6906485Z    | [0.035s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK581T2N09", Request id "0HLGK581T2N09:00000002": done reading request body.
2018-09-06T18:54:15.6906947Z    | [0.036s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLGK581T2N09", Request id "0HLGK581T2N09:00000002": An unhandled exception was thrown by the application.
2018-09-06T18:54:15.6907412Z    | System.Threading.Tasks.TaskCanceledException: The request was aborted ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
2018-09-06T18:54:15.6907781Z    |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
2018-09-06T18:54:15.6908037Z    |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
2018-09-06T18:54:15.6908295Z    |    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
2018-09-06T18:54:15.6908618Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync() in /_/src/Kestrel.Core/Internal/Http/Http1MessageBody.cs:line 45
2018-09-06T18:54:15.6911025Z    |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
2018-09-06T18:54:15.6911258Z    |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
2018-09-06T18:54:15.6911465Z    |    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
2018-09-06T18:54:15.6911771Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.CopyToAsync(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/MessageBody.cs:line 86
2018-09-06T18:54:15.6912164Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 157
2018-09-06T18:54:15.6912472Z    |    --- End of inner exception stack trace ---
2018-09-06T18:54:15.6913074Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 161
2018-09-06T18:54:15.6913525Z    |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<>c__DisplayClass18_0.<<RequestsCanBeAbortedMidRead>b__2>d.MoveNext() in /_/test/Kestrel.Transport.FunctionalTests/RequestTests.cs:line 619
2018-09-06T18:54:15.6913850Z    | --- End of stack trace from previous location where exception was thrown ---
2018-09-06T18:54:15.6914176Z    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 540
2018-09-06T18:54:15.6914491Z    | [0.037s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 3.1356ms 0 
2018-09-06T18:54:15.6914764Z    | [0.038s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK581T2N09" stopped.
2018-09-06T18:54:15.6915034Z    | [30.055s] TestLifetime Information: Finished test RequestsCanBeAbortedMidRead-http://127.0.0.1:0 in 30.0556308s
2018-09-06T18:54:15.6915244Z   
```

**Comment by davidfowl** [comment]
The request aborted token isn't firing in both cases.

**Comment by halter73** [comment]
Do you have any links to the failed runs on the CI?

**Comment by davidfowl** [comment]
https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/master/job/linux-Configuration_Release_prtest/51/consoleFull

**Comment by davidfowl** [comment]
https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/release_2.2/job/linux-Configuration_Release_prtest/224/consoleFull

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=571239&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2 at 9:29:46 PM:
- ConnectionClosedWhenKeepAliveTimeoutExpires

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=31048) on master at 6:28:51 PM:
- AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterCooldownExpires

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=31695) on release/2.2 at 7:45:14 PM:
- AppCanHandleClientAbortingConnectionMidResponse

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=34308) on release/2.2 at 11:01:45 PM:
- AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterCooldownExpires

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585272&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master at 1:50:55 PM:
- ServerCanAbortConnectionAfterUnobservedClose

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585268&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:50:55 PM:
- ServerCanAbortConnectionAfterUnobservedClose

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585675&buildTypeId=XPlat_Windows_Win8_Universe) on master at 3:03:03 PM:
- ServerCanAbortConnectionAfterUnobservedClose

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=587230&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 1:24:55 AM:
- AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterEndOfStream

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=587586&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 6:27:40 PM:
- AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterEndOfStream

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588085&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 6:33:52 PM:
- AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterEndOfStream

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588315&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 12:47:33 PM:
- AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterEndOfStream

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588949&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:15:09 PM:
- AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterEndOfStream

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=589639&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 3:00:47 PM:
- AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterCooldownExpires
