### ISSUE TITLE
Flaky test: SynchronousWritesAllowedByDefault

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2898]
Seems like it's related to graceful shutdown not working properly

```
10:51:58   [xUnit.net 00:00:06.41]     SynchronousWritesAllowedByDefault [FAIL]
10:51:58   Failed   SynchronousWritesAllowedByDefault
10:51:58   Error Message:
10:51:58    System.AggregateException : An error occurred while writing to logger(s). (Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. )
10:51:58   ---- System.Exception : Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
10:51:58   Stack Trace:
10:51:58      at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
10:51:58      at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs:line 164
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 192
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 177
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.Dispose() in /_/src/Kestrel.Core/KestrelServer.cs:line 222
10:51:58      at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
10:51:58      at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.Dispose()
10:51:58      at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
10:51:58      at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.TestServer.Dispose() in /_/test/Kestrel.InMemory.FunctionalTests/TestTransport/TestServer.cs:line 111
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ResponseTests.SynchronousWritesAllowedByDefault() in /_/test/Kestrel.InMemory.FunctionalTests/ResponseTests.cs:line 2332
10:51:58   --- End of stack trace from previous location where exception was thrown ---
10:51:58   ----- Inner Stack Trace -----
10:51:58      at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 74
10:51:58      at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
10:51:58   Standard Output Messages:
10:51:58    | [0.001s] TestLifetime Information: Starting test SynchronousWritesAllowedByDefault at 2018-09-06T17:51:51
10:51:58    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
10:51:58    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
10:51:58    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly testhost
10:51:58    | [0.003s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" started.
10:51:58    | [0.464s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  
10:51:58    | [0.468s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" completed keep alive response.
10:51:58    | [0.468s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 3.8665ms 200 
10:51:58    | [0.629s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  
10:51:58    | [0.630s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" completed keep alive response.
10:51:58    | [0.630s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.9389ms 200 
10:51:58    | [0.651s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
10:51:58    | [5.653s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" disconnecting.
10:51:58    | [5.654s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" stopped.
10:51:58    | [5.710s] Microsoft.AspNetCore.Server.Kestrel Debug: Some connections failed to close gracefully during server shutdown.
10:51:58    | [5.711s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Server shutdown exception
10:51:58    | System.AggregateException: An error occurred while writing to logger(s). (Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. ) ---> System.Exception: Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
10:51:58    |    at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 74
10:51:58    |    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
10:51:58    |    --- End of inner exception stack trace ---
10:51:58    |    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
10:51:58    |    at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
10:51:58    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs:line 164
10:51:58    |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 192
10:51:58    |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StopAsync(CancellationToken cancellationToken)
10:51:58    |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
10:51:58    | ---> (Inner Exception #0) System.Exception: Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
10:51:58    |    at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 74
10:51:58    |    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
10:51:58    | [5.724s] TestLifetime Information: Finished test SynchronousWritesAllowedByDefault in 5.7229068s
```

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585272&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master at 1:50:55 PM:
- WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585268&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:50:55 PM:
- WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585675&buildTypeId=XPlat_Windows_Win8_Universe) on master at 3:03:03 PM:
- WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken
