### ISSUE TITLE
Test failure: NonListenerPipeConnectionsAreLoggedAndIgnored

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/KestrelHttpServer#2907]
This test [fails](http://aspnetci/viewLog.html?buildId=549061&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) occasionally with the following error:
```
System.IO.InvalidDataException : No StatusCode found in ''
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStatus(String response)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.ReadResponse(Stream stream)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.ListenerPrimaryTests.AssertResponseEventually(Uri address, String expected, String[] allowed, Int32 maxRetries, Int32 retryDelay) in /_/test/Kestrel.Transport.Libuv.Tests/ListenerPrimaryTests.cs:line 281
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.ListenerPrimaryTests.NonListenerPipeConnectionsAreLoggedAndIgnored() in /_/test/Kestrel.Transport.Libuv.Tests/ListenerPrimaryTests.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
NonListenerPipeConnectionsAreLoggedAndIgnored [failed with about the same error](http://aspnetci/viewLog.html?buildId=557323&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=562167&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) on 2.2:
- NonListenerPipeConnectionsAreLoggedAndIgnored


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment]
@JunTaoLuo could you take a look please?

**Comment by JunTaoLuo** [comment]
This is another manifestation of empty responses on macOS. I'll add functionality to retry tests since this is an OS level bug we can't fix and we don't want to lose test coverage.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=577076&buildTypeId=Releases_21Public_OsxUniverse) on 2.1 at 10:47:21 PM:
- NonListenerPipeConnectionsAreLoggedAndIgnored

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=35392) on master at 6:54:43 PM:
- CanRebindToMultipleEndPoints
