### ISSUE TITLE
Test failed: Some connections failed to close gracefully during server shutdown.

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2919]
Fall out from my change here https://github.com/aspnet/KestrelHttpServer/pull/2834.

https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/master/job/windows-Configuration_Debug_prtest/52/consoleFull

cc @halter73 

```
[xUnit.net 00:00:06.41]     SynchronousWritesAllowedByDefault [FAIL]
10:51:58   Failed   SynchronousWritesAllowedByDefault
10:51:58   Error Message:
10:51:58    System.AggregateException : An error occurred while writing to logger(s). (Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. )
10:51:58   ---- System.Exception : Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
10:51:58   Stack Trace:
10:51:58      at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
10:51:58      at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs:line 164
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 192
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 177
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.Dispose() in /_/src/Kestrel.Core/KestrelServer.cs:line 222
10:51:58      at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
10:51:58      at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.Dispose()
10:51:58      at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
10:51:58      at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.TestServer.Dispose() in /_/test/Kestrel.InMemory.FunctionalTests/TestTransport/TestServer.cs:line 111
10:51:58      at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ResponseTests.SynchronousWritesAllowedByDefault() in /_/test/Kestrel.InMemory.FunctionalTests/ResponseTests.cs:line 2332
10:51:58   --- End of stack trace from previous location where exception was thrown ---
10:51:58   ----- Inner Stack Trace -----
10:51:58      at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 74
10:51:58      at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
10:51:58   Standard Output Messages:
10:51:58    | [0.001s] TestLifetime Information: Starting test SynchronousWritesAllowedByDefault at 2018-09-06T17:51:51
10:51:58    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
10:51:58    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
10:51:58    | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly testhost
10:51:58    | [0.003s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" started.
10:51:58    | [0.464s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  
10:51:58    | [0.468s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" completed keep alive response.
10:51:58    | [0.468s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 3.8665ms 200 
10:51:58    | [0.629s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  
10:51:58    | [0.630s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" completed keep alive response.
10:51:58    | [0.630s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.9389ms 200 
10:51:58    | [0.651s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
10:51:58    | [5.653s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" disconnecting.
10:51:58    | [5.654s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGK45MGFATA" stopped.
10:51:58    | [5.710s] Microsoft.AspNetCore.Server.Kestrel Debug: Some connections failed to close gracefully during server shutdown.
10:51:58    | [5.711s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Server shutdown exception
10:51:58    | System.AggregateException: An error occurred while writing to logger(s). (Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. ) ---> System.Exception: Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
10:51:58    |    at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 74
10:51:58    |    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
10:51:58    |    --- End of inner exception stack trace ---
10:51:58    |    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
10:51:58    |    at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
10:51:58    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs:line 164
10:51:58    |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Kestrel.Core/KestrelServer.cs:line 192
10:51:58    |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StopAsync(CancellationToken cancellationToken)
10:51:58    |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
10:51:58    | ---> (Inner Exception #0) System.Exception: Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
10:51:58    |    at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 74
10:51:58    |    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
10:51:58    | [5.724s] TestLifetime Information: Finished test SynchronousWritesAllowedByDefault in 5.7229068s
```

**Comment by davidfowl** [comment]
Again here different test this time:

https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/master/job/windows-Configuration_Release_prtest/71/consoleFull

**Comment by davidfowl** [comment]
```
| [0.014s] TestLifetime Information: Starting test AppCanHandleClientAbortingConnectionMidRequest-http://127.0.0.1:0 at 2018-10-05T18:10:01
11:10:44    | [0.345s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
11:10:44    | [2.638s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
11:10:44    | [2.638s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
11:10:44    | [2.640s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 50259
11:10:44    | [2.690s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHATN33NEJ1" started.
11:10:44    | [32.701s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
11:10:44    | [32.701s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLHATN33NEJ1" received FIN.
11:10:44    | [32.702s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLHATN33NEJ1" closing because: "The client closed the connection."
11:10:44    | [32.702s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLHATN33NEJ1" sending FIN.
11:10:44    | [32.702s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHATN33NEJ1" disconnecting.
11:10:44    | [37.713s] Microsoft.AspNetCore.Server.Kestrel Debug: Some connections failed to close gracefully during server shutdown.
11:10:44    | [37.716s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLHATN33NEJ1" closing because: "The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout."
11:10:44    | [38.718s] Microsoft.AspNetCore.Server.Kestrel Debug: Some connections failed to abort during server shutdown.
11:10:44    | [38.719s] TestLifetime Information: Finished test 
```
