### ISSUE TITLE
.NET Core 2.1: UvException: Error -107 ENOTCONN socket is not connected

### ISSUE THREAD

**Issue by ZOXEXIVO** [aspnet/KestrelHttpServer#2920]
Last week see see this error in our logs:

```
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -107 ENOTCONN socket is not connected
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.GetPeerIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection..ctor(ListenerContext context, UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerSecondary.ReadStartCallback(UvStreamHandle handle, Int32 status)
```

It should be fixed with changing loglevel in v2.1 release https://github.com/aspnet/KestrelHttpServer/issues/2045, https://github.com/aspnet/KestrelHttpServer/issues/2583, https://github.com/aspnet/KestrelHttpServer/issues/2658, but we see it now

We use this packages:
```
<PackageReference Include="Microsoft.AspNetCore" Version="2.1.2" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv" Version="2.1.2" />
```

and build app with docker image
`microsoft/dotnet:2.1-sdk`
and run it with 
`microsoft/dotnet:2.1-aspnetcore-runtime`

Last build date from container - 23 August 2018

New sockets transport we shutted down, because https://github.com/aspnet/KestrelHttpServer/issues/2694

**Comment by muratg** [comment]
Did you recently upgrade to 2.1 by any chance? I wonder if you may have an older container running still. Because like you said, it should have been fixed already.

Can you run `dotnet info` inside your container and paste the output? (You can `docker exec -it --rm  YOUR_CONTAINER_NAME bash` to get a shell to it. If you have it running under Kubernetes, you can `kubectl exec --it YOUR_CONTAINER NAME` instead.)

**Comment by ZOXEXIVO** [comment]
dotnet info result:

```
Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by muratg** [comment]
That looks good. I am not sure why you would still get these logs. 

Any chance you recently update to 2.1 and you had the logs from a previous deployment?

**Comment by ZOXEXIVO** [comment]
As i said - last container build and deploy - 23 august 2018.
This error appears twice a week with 100-200 errors.

**Comment by halter73** [comment]
@OXEXIVO I'm certain that either something wasn't updated to 2.1.3 or that the logs occurred prior to the upgrade taking effect. Starting in 2.1.3, there is nothing that logs "ListenerSecondary.OnConnection" anymore.

Can you provide us with the output of `lsof -p <PID>` where the `<PID>` is that of your `dotnet exec` process?

**Comment by ZOXEXIVO** [comment]
@halter73 Last error date - 12 September, and we not changing anything on server

**Comment by ZOXEXIVO** [comment]
Catched today
![image](https://user-images.githubusercontent.com/14014921/46138794-8558d400-c255-11e8-814e-e307d0b48c86.png)

**Comment by halter73** [comment]
@ZOXEXIVO You should look at the dependences for the process logging that error. That error is simply not logged by in anywhere in Kestrel 2.1.3. Moreover, that error isn't logged by any version of the Sockets transport.
