### ISSUE TITLE
Test failure: RegisterAddresses_HostName_Success

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/KestrelHttpServer#2938]
This test [fails](http://aspnetci/viewLog.html?buildId=555473&buildTypeId=Releases_22xPublic_OsxUniverse) occasionally with the following error:
```
System.Net.Sockets.SocketException : Operation timed out
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/test/Kestrel.Transport.BindTests/AddressRegistrationTests.cs:line 191
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success() in /_/test/Kestrel.Transport.BindTests/AddressRegistrationTests.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test RegisterAddresses_HostName_Success at 2018-09-17T17:21:36
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.BindTests
| [75.120s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [75.126s] TestLifetime Information: Finished test RegisterAddresses_HostName_Success in 75.1275877s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ListenAnyIP_HostName_Success [failed with about the same error](http://aspnetci/viewLog.html?buildId=555473&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment]
@muratg - please assign.

**Comment by muratg** [comment]
Assigning to @JunTaoLuo. cc @halter73

**Comment by JunTaoLuo** [comment]
This is macOS only as well. I'm wondering if this is another manifestation of empty responses on macOS which ends up causing a timeout elsewhere in our code.
