### ISSUE TITLE
.NET core app hangs on exit and on failed to bind on consecutive restart

### ISSUE THREAD

**Issue by slav** [aspnet/KestrelHttpServer#2957]
We have a .NET Core 2.1 app running on Windows Server in Azure VM. It's using default ManagedSocket, but we think the issue was there with libuv too.

After the application has been running for a while (days), when we try to shut it down, it hangs for several (5-10) minutes. When we look at it in ProcessExplorer to look at managed threads, there're non. There's single non-managed, empty thread. After a while the app exits (or gets shut down by windows? But nothing in event log). When we try to restart it again we're getting the following error.

We're launching the app as a service through NSSM, which launches cmd batch file with command to launch the application.

Neither netstat nor netsh http show urlacl show that port 8080 is used. It's as if the socket is bound to, but no one is listening on it so port doesn't show up in use anywhere.

The only solution is to restart the machine.

I'm at a loss at why the app hangs on shut down or why we can't restart it on the same port again. It launches fine on the other ports. If it hasn't been running for a while, but a short time period it shuts down fine.

The app is being pinged either by Azure LB for health check, so maybe some connection remain opens.

I'm at a loss at how to even begin to diagnose this situation? This started when we switched the app from .NET Framework to .NET Core. It worked fine in .NET Framework, never had a situation with shutdown hanging with no managed threads and then address being already in use while netstat not showing the port being used by any process.

```
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://0.0.0.0:8080: address already in use. ---> Microsoft.AspNetCore.Connections.Add
ressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted ---> System.Net.Sockets
.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext cont
ext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext cont
ext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions
 serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken can
cellationToken)
```

**Comment by Tratcher** [comment]
Can you attach a debugger when it's hung on shutdown? Checking the active thread stacks at this point would be interesting.

**Comment by slav** [comment]
@Tratcher - usually I get list of thread with Process Explorer, which allows to get current stack trace for each thread. However, Process Explorer showed no managed threads... When the app is running normally it is showing the threads correctly.

It's as if the app itself has shut down, but the process can't end because some resources is locked and after a while the system kills the process anyway, but resource (socket?) never gets unlocked. This is pure speculation though.

Also, forgot to mention. This doesn't happen every time, but quite frequently. Maybe 50% of the time.

**Comment by muratg** [comment]
@slav Were you able to repro and attach a debugger when it's hung?

**Comment by slav** [comment]
@muratg - we'll try that. However, the main issue for me is that app can't start reporting that the socket is in use even after the process shuts down and there's no evidence of the port being in use anywhere. Any advice on what or why might be causing this or how we could look into this?

**Comment by muratg** [comment]
I don't know how to identify why the port would be in use, but not detected via netstat. (I'm assuming you're doing a `netstat -an | findstr 8080` from an _admin_ cmd.)  

I'd recommend trying to uncover the root cause, hence the recommendation for the debugging and looking at the stack traces of various threads.
