### ISSUE TITLE
Test failure: AbortingTheConnectionSendsFIN

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/KestrelHttpServer#2958]
This test [fails](http://aspnetci/viewLog.html?buildId=562018&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.AbortingTheConnectionSendsFIN() in /_/test/Kestrel.Transport.FunctionalTests/RequestTests.cs:line 521
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test AbortingTheConnectionSendsFIN at 2018-09-26T06:58:07
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.006s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.006s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests
| [0.007s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLH3FLF6K8JJ" started.
| [0.007s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  
| [0.008s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLH3FLF6K8JJ", Request id "0HLH3FLF6K8JJ:00000001": the application aborted the connection.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLH3FLF6K8JJ" disconnecting.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLH3FLF6K8JJ" sending FIN.
| [0.008s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.634ms 0 
| [0.008s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLH3FLF6K8JJ" stopped.
| [0.094s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.096s] TestLifetime Information: Finished test AbortingTheConnectionSendsFIN in 0.0951793s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment]
cc @Tratcher @halter73 @JunTaoLuo

**Comment by ryanbrandenburg** [comment]
@muratg who is looking into this?

**Comment by halter73** [comment]
This test is verifying exactly what happened here doesn't happen. HttpContext.Abort() should result in socket.Receive() returning 0. This is mainly to ensure the Socket transport keeps the same behavior historically exhibited by the libuv transport. 

Having different behavior led to flakiness in other tests. Early versions of the socket transport immediately called Socket.Dispose() on abort leading to the client reporting SocketExceptions complaining about the remote host forcibly closing connections. The fix for this behavior was to always call _socket.Shutdown(SocketShutdown.Both) before Socket.Dispose which we do.

I'm not sure why this happened or what else we can do. TeamCity is reporting "6866 runs / 1 failures / 0 ignored Success rate: 100.0%". If it fails again, we could add retries. I ran the test locally without the call to _socket.Shutdown(SocketShutdown.Both) and it failed reliably 10 times in a row in a loop, so it could still serve as a useful regression test with the retries.

**Comment by muratg** [comment]
@halter73 Do you think it's a "rare" product issue then?

**Comment by halter73** [comment]
It seems very rare. And it's certainly not a test issue.

**Comment by muratg** [comment]
@Eilon should we do more investigation on this? Based on its rarity, I recommend closing this and seeing if it reproduces again.

**Comment by Eilon** [comment]
If it happened once, why wouldn't it happen again? And what would we do differently the second time?

**Comment by muratg** [comment]
@halter73 Let's take another look after preview3 is done.

**Comment by muratg** [comment]
@Eilon my main point was priority of this compared to everything else, based on rarity. Stephen can take another look once we're done with preview3 check-ins.

**Comment by Eilon** [comment]
Waiting a bit is fine. I just don't want to wait forever 😄

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=579139&buildTypeId=XPlat_Windows_Win10Universe) on master at 2:16:38 PM:
- RequestsCanBeAbortedMidRead
