### ISSUE TITLE
Don't throw UvException directly to users

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#299]
Kestrel request and response Streams should throw IOExceptions, not UvExceptions.
```
An exception of type 'Microsoft.AspNet.Server.Kestrel.Networking.UvException' occurred in mscorlib.dll but was not handled in user code

Additional information: Error -4081 ECANCELED operation canceled

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<WriteChunkedAsync>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<WriteAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Glimpse.Server.Resources.ServerSentEventResponse.<SendData>d__5.MoveNext() in C:\Users\antho\Projects\Glimpse.Prototype\src\Glimpse.Server\Resources\HttpContextExtensions.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Glimpse.Server.Internal.Resources.MessageStreamResource.<>c__DisplayClass4_0.<<Configure>b__1>d.MoveNext() in C:\Users\antho\Projects\Glimpse.Prototype\src\Glimpse.Server\Internal\Resources\MessageStreamResource.cs:line 63
https://github.com/Glimpse/Glimpse.Prototype/blob/dev/src/Glimpse.Server/Internal/Resources/MessageStreamResource.cs#L63
```

**Comment by halter73** [comment]
Fixed by https://github.com/aspnet/KestrelHttpServer/pull/325

**Comment by omuleanu** [comment]
I'm also getting this in rc1-final while debugging, 
"An exception of type 'Microsoft.AspNet.Server.Kestrel.Networking.UvException' occurred in mscorlib.dll but was not handled in user code

Additional information: Error -4077 ECONNRESET connection reset by peer"
on line `writer.Write(str)` in WriteTo method, custom helper, implements IHtmlContent

**Comment by halter73** [comment]
`Response.Write` will no longer throw in RC2 unless you pass in a canceled CancellationToken (such as `RequestAborted). In RC1, writes can fail if there are connection issues.
