### ISSUE TITLE
Kestrel ended slowly. And when I run it again, I get an error that the port is in use.

### ISSUE THREAD

**Issue by wxilas21** [aspnet/KestrelHttpServer#3074]
> ### Situation

These events are left in the event viewer.
Event ID : 16002
Closing a TCP socket with local port number 50000 in process 3584 is taking longer than expected. The local port number may not be available until the close operation is completed. This happens typically due to misbehaving network drivers. Ensure latest updates are installed for Windows and any third-party networking software including NIC drivers, firewalls, or other security products.  

These events are left in the event viewer.
Event ID: 1002
The program GameServer.exe version 0.0.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Action Center control panel.
 Process ID: f78
 Start Time: 01d4756a17377dab
 Termination Time: 4294967295
 Application Path: C:\Server\GameServers\GameServer.exe
 Report Id: 87a58e30-e15d-11e8-8217-0ab6b219a55a
 Faulting package full name: 
 Faulting package-relative application ID: 

I need help with what to do.

**Comment by wxilas21** [comment]
It happened many times. And I think it happens when a specific packet arrives. I also have a dump of waiting processes when I quit.

Thank you for your interest in this question.

### This is the log when a specific packet arrives.

Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line: '\x03\x00\x00+&\xE0\x00\x00\x00\x00\x00Cookie: mstshash=hello\x0D\x0A'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectRequestLine(Byte* requestLine, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.GetUnknownMethod(Byte* data, Int32 length, Int32& methodLength)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.IHttpParser<TRequestHandler>.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

**Comment by wxilas21** [comment]
> Was this a one time occurrence or do you have a way to reproduce it? Can you capture a dump when it happens?

It happened many times. And I think it happens when a specific packet arrives. I also have a dump of waiting processes when I quit.

Thank you for your interest in this question.

This is the log when a specific packet arrives.
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line: '\x03\x00\x00+&\xE0\x00\x00\x00\x00\x00Cookie: mstshash=hello\x0D\x0A'
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser1.RejectRequestLine(Byte* requestLine, Int32 length) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser1.GetUnknownMethod(Byte* data, Int32 length, Int32& methodLength)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser1.ParseRequestLine(TRequestHandler handler, ReadOnlySequence1& buffer, SequencePosition& consumed, SequencePosition& examined) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser1.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.IHttpParser.ParseRequestLine(TRequestHandler handler, ReadOnlySequence1& buffer, SequencePosition& consumed, SequencePosition& examined) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence1 buffer, SequencePosition& consumed, SequencePosition& examined)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence1 buffer, SequencePosition& consumed, SequencePosition& examined) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

**Comment by Tratcher** [comment]
What's generating that request?

What version of Kestrel are you using?

**Comment by wxilas21** [comment]
### Execution environment
Using AWS EC2
Windows server 2012 R2 Version 6.3 ( build 9600)

### What version of Kestrel are you using?
I used Dotnet core SDK 2.1.403, Runtime 2.1.5

### What's generating that request?
This is a request from an anonymous user.

**Comment by wxilas21** [comment]
I have a dump file about this problem.

**Comment by wxilas21** [comment]
Yesterday, I left the office after running the kestrel server 2.1.3 SampleApp and when I came to work today, the same issue arose. And we found the same error log in the event viewer.

**Comment by wxilas21** [comment]
Why does this issue occur in my environment when I run and test Kestrel 2.1.3 SampleApp? What am I missing?

**Comment by Tratcher** [comment]
Do you mean this [SampleApp](https://github.com/aspnet/KestrelHttpServer/tree/40a9b18c439a44093a3d2bd124513aedfa53599a/samples/SampleApp) or another one? With or without HTTPS?

That BadHttpRequestException is complaining about a maliciously malformed request (@blowdart). Kestrel should be able to handle those exceptions. It's possible there's another malicious request it's not handling well. The [connection logs](https://github.com/aspnet/KestrelHttpServer/blob/40a9b18c439a44093a3d2bd124513aedfa53599a/samples/SampleApp/Startup.cs#L105) would be the best way to track down what the content is. Note you need to turn the [log level](https://github.com/aspnet/KestrelHttpServer/blob/40a9b18c439a44093a3d2bd124513aedfa53599a/samples/SampleApp/Startup.cs#L69-L70) up to Trace.

You may also want to try 2.2.0-preview3.

**Comment by wxilas21** [comment]
I thought I was using the Kestrel Server incorrectly, so I tried running the SampleApp project on Kestrel Server 2.1.3 on the server except HTTPS. 
I was embarrassed by the same phenomenon. And my Loglevel is Trace. I will test again with 2.2.0-preview3.

**Comment by muratg** [comment]
cc @shirhatti

**Comment by shirhatti** [comment]
This sounds very similar to a known bug in the TCP/IP stack in a recent [Windows KB4338824](https://support.microsoft.com/en-us/help/4338824/windows-81-update-kb4338824). It was mitigated by KB4345424. Can you please ensure you have the mitigation KB installed?

**Comment by wxilas21** [comment]
Thank you for your interest in the old issue. I will check if <a href="https://support.microsoft.com/en-us/help/4338824/windows-81-update-kb4338824" rel="nofollow">Windows KB4338824</a> is updated.
