### ISSUE TITLE
If a ConnectionFilter throws synchronously the server crashes

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#370]
The exception will be logged inside of UvStreamHandle.UvConnectionCb and rethrown.

    Hosting environment: Production
    Now listening on: http://localhost:5000
    Now listening on: https://localhost:5001
    Application started. Press Ctrl+C to shut down.
    dbug: Microsoft.AspNet.Server.Kestrel[1]
          Connection id "1" started.
    fail: Microsoft.AspNet.Server.Kestrel[0]
          UvConnectionCb
          System.Exception: Exception of type 'System.Exception' was thrown.
             at Microsoft.AspNet.Server.Kestrel.Filter.NoOpConnectionFilter.OnConnection(ConnectionFilterContext context) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Filter\NoOpConnectionFilter.cs:line 13
             at Microsoft.AspNet.Server.Kestrel.Http.Connection.Start() in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\Connection.cs:line 82
             at Microsoft.AspNet.Server.Kestrel.Http.Listener.DispatchConnection(UvStreamHandle socket) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\Listener.cs:line 80
             at Microsoft.AspNet.Server.Kestrel.Http.TcpListener.OnConnection(UvStreamHandle listenSocket, Int32 status) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\TcpListener.cs:line 53
             at Microsoft.AspNet.Server.Kestrel.Http.Listener.ConnectionCallback(UvStreamHandle stream, Int32 status, Exception error, Object state) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\Listener.cs:line 66
             at Microsoft.AspNet.Server.Kestrel.Http.TcpListener.<>c.<CreateListenSocket>b__1_0(UvStreamHandle stream, Int32 status, Exception error, Object state) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\TcpListener.cs:line 28

             at Microsoft.AspNet.Server.Kestrel.Networking.UvStreamHandle.UvConnectionCb(IntPtr handle, Int32 status) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Networking\UvStreamHandle.cs:line 132
    verb: Microsoft.AspNet.Hosting.Internal.HostingEngine[6]
          Hosting shutdown
    System.Exception: Exception of type 'System.Exception' was thrown.
       at Microsoft.AspNet.Server.Kestrel.Filter.NoOpConnectionFilter.OnConnection(ConnectionFilterContext context) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Filter\NoOpConnectionFilter.cs:line 13
       at Microsoft.AspNet.Server.Kestrel.Http.Connection.Start() in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\Connection.cs:line 82
       at Microsoft.AspNet.Server.Kestrel.Http.Listener.DispatchConnection(UvStreamHandle socket) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\Listener.cs:line 80
       at Microsoft.AspNet.Server.Kestrel.Http.TcpListener.OnConnection(UvStreamHandle listenSocket, Int32 status) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\TcpListener.cs:line 53
       at Microsoft.AspNet.Server.Kestrel.Http.Listener.ConnectionCallback(UvStreamHandle stream, Int32 status, Exception error, Object state) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\Listener.cs:line 66
       at Microsoft.AspNet.Server.Kestrel.Http.TcpListener.<>c.<CreateListenSocket>b__1_0(UvStreamHandle stream, Int32 status, Exception error, Object state) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Http\TcpListener.cs:line 28
       at Microsoft.AspNet.Server.Kestrel.Networking.UvStreamHandle.UvConnectionCb(IntPtr handle, Int32 status) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Networking\UvStreamHandle.cs:line 137
       at Microsoft.AspNet.Server.Kestrel.Networking.UvStreamHandle.<>c.<.cctor>b__20_0(IntPtr handle, Int32 status) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Networking\UvStreamHandle.cs:line 13
       at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)
       at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.run(UvLoopHandle handle, Int32 mode) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Networking\Libuv.cs:line 151
       at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Run(Int32 mode) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Networking\UvLoopHandle.cs:line 28
       at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart(Object parameter) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Infrastructure\KestrelThread.cs:line 226
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.AspNet.Server.Kestrel.KestrelThread.Stop(TimeSpan timeout) in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\Infrastructure\KestrelThread.cs:line 99
       at Microsoft.AspNet.Server.Kestrel.KestrelEngine.Dispose() in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\KestrelEngine.cs:line 46
       at Microsoft.AspNet.Server.Kestrel.KestrelServer.Dispose() in C:\Users\shalter\dev\Universe\KestrelHttpServer\src\Microsoft.AspNet.Server.Kestrel\KestrelServer.cs:line 122
       at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass35_0.<Start>b__1()
       at Microsoft.AspNet.Hosting.Internal.HostingEngine.Disposable.Dispose()
       at Microsoft.AspNet.Hosting.Internal.Application.Dispose()
       at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
       at Microsoft.AspNet.Hosting.Program.Main(String[] args)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
       at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()

Fortunately, this issue doesn't affect HttpsConnectionFilter since all exceptions will be surfaced through a faulted task.

**Comment by cesarbs** [comment]
Closed by https://github.com/aspnet/KestrelHttpServer/pull/403.
