### ISSUE TITLE
Concurrent reads are not supported consequences

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#451]
```
Unhandled Exception: System.InvalidOperationException: Concurrent reads are not supported.
   at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.OnCompleted(Action continuation)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitUnsafeOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by benaadams** [comment]
Also need to workout why was going concurrent reads - but that could be user code.

**Comment by benaadams** [comment]
Fairly convinced this state is caused by calling code; but it crashes the server which is undesirable.
