### ISSUE TITLE
AV in Kestrel during long haul with Ngnix.

### ISSUE THREAD

**Issue by SajayAntony** [aspnet/KestrelHttpServer#621]
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput.ProducingStart()
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame.CreateResponseHeader(Byte[] statusBytes, Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame.ProduceStartAndFireOnStarting()
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame.<WriteAsyncAwaited>d__121.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame.WriteAsyncAwaited(ArraySegment`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame.WriteAsync(ArraySegment`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Http.FrameResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.<FlushInternalAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternalAsync(Boolean flushEncoder)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultAsync>d__44.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultFilterAsync>d__43.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.InvokeResultFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultFilterAsync>d__43.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.InvokeResultFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__42.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.InvokeAllResultFiltersAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResourceFilterAsync>d__37.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.InvokeResourceFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResourceFilterAsync>d__37.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.InvokeResourceFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.InvokeActionAsync(HttpContext httpContext, ActionDescriptor actionDescriptor)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.RequestProcessingAsync()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```

@yuwaMSFT is currently working on getting a coredump for this. 
Ran with **500-1000 clients** against it for 10 hours. (It may happen in just 2 to 3 hours).

1. Install dnvm and DNX, and libuv
  https://docs.asp.net/en/latest/getting-started/installing-on-linux.html

  sudo apt-get install unzip curl
  curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh

  sudo apt-get install libunwind8 gettext libssl-dev libcurl4-openssl-dev zlib1g libicu-dev uuid-dev
dnvm upgrade -r coreclr

  sudo apt-get install make automake libtool curl
  curl -sSL https://github.com/libuv/libuv/archive/v1.8.0.tar.gz | sudo tar zxfv - -C /usr/local/src
  cd /usr/local/src/libuv-1.8.0
  sudo sh autogen.sh
  sudo ./configure
  sudo make
  sudo make install
  sudo rm -rf /usr/local/src/libuv-1.8.0 && cd ~/
  sudo ldconfig

2. Install Mono if needed:
http://www.mono-project.com/docs/getting-started/install/linux/

3. Create a ASP.Net application
4. Run application on specific port, say http://localhost:5000
5. Install Nginx
sudo apt-get install nginx
6. Create and enable a site
    a. Create a configuration file for a new site and enable reverse proxy:
    /etc/nginx/sites-available/mysite
```
    server {
            listen 8080;
        
            location / {
                    proxy_set_header    Host $host;
                    proxy_set_header    X-Real-IP   $remote_addr;
                    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_pass  http://localhost:5000;
            }
    }```    
    b. Link the configuration as enabled site:
    ln -s /etc/nginx/sites-available/mysite /etc/nginx/sites-enabled/mysite
    c. Restart nginx
    sudo service nginx restart

**Comment by yuwaMSFT** [comment]
Got a core dump. The file is to big...Will share with Stephen/+Cesar offline

**Comment by cesarbs** [comment]
> Ran with 500-1000 clients against it for 10

For 10 what? :grin:

**Comment by yuwaMSFT** [comment]
updated the step...10 hours, but it may happen in just 2-3 hours.

**Comment by SajayAntony** [comment]
@cesarbs typo. 10 hours.

**Comment by Eilon** [comment]
It's assigned to @yuwaMSFT , should it be assigned to someone else?

**Comment by halter73** [comment]
Yeah. @yuwaMSFT emailed @cesarbs and me a link to a network share with the coredump. I haven't gotten a chance to look at it yet.

**Comment by SajayAntony** [comment]
@Eilon looks like  @halter73 or @cesarbs should be able to go ahead with it. Please assign appropriately.

**Comment by Eilon** [comment]
Parking on @halter73 's plate for now.

**Comment by halter73** [comment]
This is a dupe of #723 or vice versa. Should I close this since more recent discussion has happened on the other issue?
