### ISSUE TITLE
System.Threading.ThreadStateException: Thread is dead; state cannot be accessed.

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#644]
This only happens in non-dev builds since it is #ifdefed out.

    System.Threading.ThreadStateException: Thread is dead; state cannot be accessed.
       at System.Threading.Thread.SetBackgroundNative(Boolean isBackground)
       at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.Stop(TimeSpan timeout)
       at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.Dispose()
       at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose()
       at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
       at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
       at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
       at HelloWorldMvc.Startup.Main(String[] args)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
       at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()

**Comment by benaadams** [comment]
sigh...

Could set them background before thread.start? Still have a main thread that is blocked until disposal and that's what's calling the stops of the other threads?

**Comment by halter73** [comment]
Yeah. I was thinking about doing it after the thread.IsAlive check, but even that would race. I'll verify setting it before thread.Start works. It's hiding other start errors kinda like the old null ref in listener.dispose.

**Comment by benaadams** [comment]
PR #646

**Comment by shhsu** [comment]
NOTE: This is a blocking issue for my performance testing.

**Comment by SajayAntony** [comment]
@Eilon could this be marked partner-blocking?

**Comment by halter73** [comment]
@SajayAntony @shhsu #646 doesn't fix the blocking issue. It only fixes shutdown in certain circumstances.

The stacktrace that `KestrelServer.Start` is calling `KestrelServer.Dispose`. That means there's a startup exception that is supposed to be rethrown, but isn't because of the shutdown issue (which is only happening because the server didn't fully start). If we can see the first chance exception, you can probably avoid the shutdown issue altogether.

 I still haven't been able to repro this issue to verify #646 fixes it. I've even tried forcing a startup failure by starting two processes and having the both try to attach to the same ports. Have you been able to repro @benaadams?

**Comment by halter73** [comment]
OK I was able to reproduce the issue by renaming libuv.dll in my ~/nuget/packages folder.

I'm about 99% sure that there is an issue loading `libuv.so` since that's one of the only things that would stop the "KestreThread" before `KestrelThread.Stop` is called. Maybe an unversioned `libuv.so` isn't in your library load path?

Make sure you are following the directions here to install libuv: http://docs.asp.net/en/latest/getting-started/installing-on-linux.html#install-libuv

**Comment by shhsu** [comment]
I did install the livuv from this instruction and the problem is still here.

**Comment by shhsu** [comment]
This lab machine has run kestrel before. It just started to fail last Friday
Any reason to believe that all the sudden the library is the issue here? Is there any new code that would cause it? Or could this be something else

**Comment by halter73** [comment]
The Microsoft.AspNetCore.Server.Kestrel 1.0.0-rc2-16436 package from the https://www.myget.org/F/aspnetvolatiledev/ feed includes #646. If you use that feed, you should see the underlying error without having to find the first-chance exception.

**Comment by shhsu** [comment]
For the record

The problem hidden below was that the user running the application does not have permission to libuv. The error should have been 

(Exception from HRESULT: 0x8007007E)) ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init(Libuv uv)

If it wasn't hidden.
The solution to the problem would be to properly install libuv following the steps

http://docs.asp.net/en/latest/getting-started/installing-on-linux.html

And ensure that the current user have run/execute permission to libuv afterwards
