### ISSUE TITLE
Sporadic ThrowingAfterPartialWriteKillsConnection test failures on AppVeyor

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#658]
Example output:

    Microsoft.AspNetCore.Server.KestrelTests.EngineTests.ThrowingAfterPartialWriteKillsConnection(testContext: TestServiceContext { App = null, AppLifetime = LifetimeNotImplemented { ApplicationStarted = (throws NotImplementedException), ApplicationStopped = (throws NotImplementedException), ApplicationStopping = (throws NotImplementedException) }, DateHeaderValueManager = TestDateHeaderValueManager { }, FrameFactory = null, Log = TestKestrelTrace { }, ... }) [FAIL]
      timeout
      Expected: True
      Actual:   False
      Stack Trace:
        C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\TestConnection.cs(75,0): at Microsoft.AspNetCore.Server.KestrelTests.TestConnection.<Receive>d__8.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\TestConnection.cs(122,0): at Microsoft.AspNetCore.Server.KestrelTests.TestConnection.<ReceiveEnd>d__10.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        C:\projects\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\EngineTests.cs(742,0): at Microsoft.AspNetCore.Server.KestrelTests.EngineTests.<ThrowingAfterPartialWriteKillsConnection>d__26.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    Microsoft.AspNetCore.Server.KestrelTests

https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.2334
https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.2364

**Comment by halter73** [comment]
We should probably not bother consuming the rest of the request when we are going to subsequently just kill the connection after an app failure.

[Here](https://github.com/aspnet/KestrelHttpServer/blob/37055517eec452e0aaec5f08ae6010c99ac3fdd0/src/Microsoft.AspNetCore.Server.Kestrel/Http/FrameOfT.cs#L103) it's probably worth checking if `_requestProcessingStopping` was set by `ProduceEnd` due to an application failure. It would be fairly easy to write a test that consistently kept the connection open after an application error if we sent an incomplete request, but that doesn't explain the test failure since the test send a complete request.

**Comment by benaadams** [comment]
If its ProduceEnd+Consume interaction that causes this I might have a fix for it in updated PR for the chunking. Just working though the sending of bad request based on headers.
