### ISSUE TITLE
Wrong HTTP version in test response

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#672]
ChunkedRequestTests.TrailingHeadersAreParsed failed with HTTP/1.0 in a response when HTTP/1.1 was expected. This could mean that SocketInput was corrupted somehow, but there are a lot of other possible causes. Test output:

    Microsoft.AspNetCore.Server.KestrelTests.ChunkedRequestTests.TrailingHeadersAreParsed(testContext: TestServiceContext { App = null, AppLifetime = LifetimeNotImplemented { ApplicationStarted = (throws NotImplementedException), ApplicationStopped = (throws NotImplementedException), ApplicationStopping = (throws NotImplementedException) }, DateHeaderValueManager = TestDateHeaderValueManager { }, FrameFactory = null, Log = TestKestrelTrace { }, ... }) [FAIL]
      Assert.Equal() Failure
                       ↓ (pos 7)
      Expected: HTTP/1.1 200 OK\r\nContent-Length: 11\r\n\r\nHello Wor···
      Actual:   HTTP/1.0 200 OK\r\nContent-Length: 11\r\n\r\nHello Wor···
                       ↑ (pos 7)
      Stack Trace:
           at Microsoft.AspNetCore.Server.KestrelTests.TestConnection.<Receive>d__8.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           at Microsoft.AspNetCore.Server.KestrelTests.TestConnection.<ReceiveEnd>d__10.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           at Microsoft.AspNetCore.Server.KestrelTests.ChunkedRequestTests.<TrailingHeadersAreParsed>d__7.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

https://travis-ci.org/aspnet/KestrelHttpServer/jobs/113269625#L3940

**Comment by cesarbs** [comment]
I'll look at this once I'm done with #667.

**Comment by halter73** [comment]
This is my first time seeing this so it might be hard to repro. Fortunately, you have a low powered VM that seems to help and the test that failed is pretty new, so maybe it won't be so bad. I suggest running just this test in a loop.

**Comment by cesarbs** [comment]
I'm not seeing the exact same thing but I'm getting the failure below. Very inconsistent though. Need to run on a loop for several minutes until I hit it.

    Microsoft.AspNetCore.Server.KestrelTests.ChunkedRequestTests.TrailingHeadersAreParsed(testContext: TestServiceContext { App = null, AppLifetime = LifetimeNotImplemented { ApplicationStarted = (throws NotImplementedException), ApplicationStopped = (throws NotImplementedException), ApplicationStopping = (throws NotImplementedException) }, DateHeaderValueManager = TestDateHeaderValueManager { }, FrameFactory = null, Log = TestKestrelTrace { }, ... }) [FAIL]
      Assert.Equal() Failure
                ? (pos 0)
      Expected: HTTP/1.1 200 OK\r\nContent-Length: 11\r\n\r\nHe···
      Actual:
                ? (pos 0)

**Comment by benaadams** [comment]
Output errors written to TestLogger to console?

**Comment by cesarbs** [comment]
?

**Comment by benaadams** [comment]
TestLogger doesn't actually output any errors; if you enable output to console (think its either just commented out or you just need to add a one liner) then it will normally output something interesting related to why the test goes wrong
