### ISSUE TITLE
Error starting web application after deploying a build built by Visual Studio Team Services

### ISSUE THREAD

**Issue by eriksendc** [aspnet/KestrelHttpServer#685]
Hi All,

Sorry in advance if I've posted this in the wrong place. If you think I have just let me know.

I've got an ASP.NET 5 (rc1-final) web application whose code I keep in Visual Studio Team Services (VSTS). I recently got VSTS builds working (I borrowed the build-related info from this article: https://msdn.microsoft.com/en-us/library/vs/alm/build/azure/deploy-aspnet5).

Once a VSTS build is complete you can download the build's artifacts by interacting with the VSTS UI. The result is that you get a file named drop.zip that contains wwwroot and approot which are populated just like if I did a build and publish locally from within Visual Studio.

The issue is that if I extract wwwroot and approot from drop.zip and put them on my QA web server, I get the following error:

Error: Unable to load application or execute command 'Microsoft.AspNet.Server.Kestrel'. Available commands: web, ef.
System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadFile(String assemblyPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

So I followed the link in the error message and I get that I need to put `<loadFromRemoteSources enabled="true" />` into some config file, but I'm not sure which one. Would it be in Kestrel's or my application's web.config or somewhere else?

Thanks!
-Brian Eriksen

**Comment by Tratcher** [comment]
Before you extract the zip check it's properties and see if it is marked as "blocked". If so, unblock it before extracting it. This is a Windows security feature on executable internet downloads.

**Comment by eriksendc** [comment]
Thanks, @Tratcher. In fact I was only testing things with a drop.zip that I manually downloaded from VSTS. I now have built a small client that pulls a specific build's drop.zip down via the VSTS REST Api, and when I write the zip file to disk myself the file isn't "blocked" to begin with. So when Chrome downloads the file for you then the the "blocked" status is set for the file.

Anyways, I did do some research and you can delete the "blocked" status programmatically. I used this info to incorporating unblocking (until I realized I didn't need it): http://stackoverflow.com/questions/6375599/is-this-pinvoke-code-correct-and-reliable

-Brian Eriksen
