### ISSUE TITLE
HTTP 502.3 Bad Gateway / Error -4082 EBUSY resource busy or locked /  Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf()

### ISSUE THREAD

**Issue by santos222** [aspnet/KestrelHttpServer#694]
I'm getting HTTP 502.3 Bad Gateway (i have the correct Http Platform Handler installed). In the logs I see the following stack strace (towards the end I get the same error Unhandled Exception: Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4082 EBUSY resource busy or locked ).

This happens only when I deploy to a staging/prod Windows Server 2008 R2 - I can debug ok using IISExpress and it works fine on a website hosted by IIS (Windows 7). I have also just tested this on Windows Server 2012 and it works fine. Any ideas?

** Other information:
DNX 4.5.1
IIS 7.5 Windows Server 2008 R2
httpPlatformHandler is correctly installed and enabled in handler mappings (IIS management console)

Log trace:

Hosting environment: Production
Now listening on: http://localhost:19685
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
Request starting HTTP/1.1 GET http://localhost:60/api/values/5 
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
Executing action method Mvc6.Sample.Controllers.ValuesController.Get with arguments (5) - ModelState is Valid'
info: Microsoft.AspNet.Mvc.Infrastructure.ObjectResultExecutor[1]
Executing ObjectResult, writing value Microsoft.AspNet.Mvc.ActionContext.
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
Executed action Mvc6.Sample.Controllers.ValuesController.Get in 0.0234ms
fail: Microsoft.AspNet.Server.Kestrel[0]
KestrelThread.DoPostWork
System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf()'.
at Microsoft.AspNet.Server.Kestrel.Networking.UvWriteReq.Init(UvLoopHandle loop)
at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.WriteContext.DoWriteIfNeeded()
at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.WriteAllPending()
at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.<>c.b__15_0(SocketOutput _this)
at Microsoft.AspNet.Server.Kestrel.KestrelThread.<>c__301.<post>b__30_0(Object callback2, Object state2) at Microsoft.AspNet.Server.Kestrel.KestrelThread.DoPostWork() System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf()'. at Microsoft.AspNet.Server.Kestrel.Networking.UvWriteReq.Init(UvLoopHandle loop) at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.WriteContext.DoWriteIfNeeded() at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.WriteAllPending() at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.<>c.<schedulewrite>b__15_0(SocketOutput _this) at Microsoft.AspNet.Server.Kestrel.KestrelThread.<>c__301.b__30_0(Object callback2, Object state2)
at Microsoft.AspNet.Server.Kestrel.KestrelThread.DoPostWork()
at Microsoft.AspNet.Server.Kestrel.KestrelThread.OnPost()
at Microsoft.AspNet.Server.Kestrel.Networking.UvAsyncHandle.AsyncCb(IntPtr handle)
at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)
at Microsoft.AspNet.Server.Kestre...(UvLoopHandle handle, Int32 mode)
at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNet.Server.Kestrel.KestrelThread.Stop(TimeSpan timeout)
at Microsoft.AspNet.Server.Kestrel.KestrelEngine.Dispose()
at Microsoft.AspNet.Server.Kestrel.ServerFactory.<>c__DisplayClass4_0.b__0()
at Microsoft.AspNet.Server.Kestrel.Disposable.Dispose(Boolean disposing)
at Microsoft.AspNet.Server.Kestrel.Disposable.Dispose()
at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.b__1()
at Microsoft.AspNet.Hosting.Internal.HostingEngine.Disposable.Dispose()
at Microsoft.AspNet.Hosting.Internal.Application.Dispose()
at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.b__0()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
Unhandled Exception: Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4082 EBUSY resource busy or locked
at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.loop_close(UvLoopHandle handle)
at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.ReleaseHandle()
at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
at System.Runtime.InteropServices.SafeHandle.Finalize()

**Comment by benaadams** [comment]
package conflicts? You are using `Microsoft.AspNet.Server.Kestrel` does that mean you are using the RC1 feeds from nuget rather than the myget feeds? (or are using specific RC1 versions)

**Comment by Tratcher** [comment]
Are you sure you installed .NET 4.5.1? You may just have 4.5.0. https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.marshal.sizeof(v=vs.110).aspx

**Comment by santos222** [comment]
@Tratcher Good spot, that was it. Thanks for your help everyone, I will close the issue.
