### ISSUE TITLE
Race when consuming start line and headers sent immediately before client FIN

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#704]
Example test failure due to the bug:

    [Test collection for Microsoft.AspNetCore.Server.KestrelTests.EngineTests (1)] Microsoft.AspNetCore.Server.KestrelTests.EngineTests.ZeroContentLengthSetAutomaticallyAfterNoWrites(testContext: TestServiceContext { App = null, AppLifetime = LifetimeNotImplemented { ApplicationStarted = (throws NotImplementedException), ApplicationStopped = (throws NotImplementedException), ApplicationStopping = (throws NotImplementedException) }, DateHeaderValueManager = TestDateHeaderValueManager { }, FrameFactory = null, Log = TestKestrelTrace { }, ... })
    [16:48:45]
    [Microsoft.AspNetCore.Server.KestrelTests.EngineTests.ZeroContentLengthSetAutomaticallyAfterNoWrites(testContext: TestServiceContext { App = null, AppLifetime = LifetimeNotImplemented { ApplicationStarted = (throws NotImplementedException), ApplicationStopped = (throws NotImplementedException), ApplicationStopping = (throws NotImplementedException) }, DateHeaderValueManager = TestDateHeaderValueManager { }, FrameFactory = null, Log = TestKestrelTrace { }, ... })] Assert.Equal() Failure
                                           (pos 38)
    Expected: úúúontent-Length: 0\r\n\r\nHTTP/1.0 200 OK\r\nConnection: keep-alive\r\núúú
    Actual:   úúúontent-Length: 0\r\n\r\n
                                           (pos 38)
       at Microsoft.AspNetCore.Server.KestrelTests.TestConnection.<Receive>d__8.MoveNext() in D:\b\w\e70224f4ea5e88a1\KestrelHttpServer\test\Microsoft.AspNetCore.Server.KestrelTests\TestConnection.cs:line 85
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Server.KestrelTests.TestConnection.<ReceiveEnd>d__10.MoveNext() in D:\b\w\e70224f4ea5e88a1\KestrelHttpServer\test\Microsoft.AspNetCore.Server.KestrelTests\TestConnection.cs:line 122
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.AspNetCore.Server.KestrelTests.EngineTests.<ZeroContentLengthSetAutomaticallyAfterNoWrites>d__18.MoveNext() in D:\b\w\e70224f4ea5e88a1\KestrelHttpServer\test\Microsoft.AspNetCore.Server.KestrelTests\EngineTests.cs:line 433
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task

**Comment by halter73** [comment]
This fix isn't complete. There are currently a bunch of other places RemoteIntakeFin is checked that is vulnerable to the same race.

**Comment by cesarbs** [comment]
Oops :grin:
