### ISSUE TITLE
OperationCanceledException under load

### ISSUE THREAD

**Issue by anpete** [aspnet/KestrelHttpServer#748]
Not sure if this is expected, so filing just in case. While investigating our internal MusicStore stress scenario I'm seeing an OperationCanceledException raised occasionally when the number of clients > ~50.

Stack:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Http.Extensions.StreamCopyOperation.<CopyToAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
warn: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      The response has already started, the error handler will not be executed.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKR44KL0RBVP": An unhandled exception was thrown by the application.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Http.Extensions.StreamCopyOperation.<CopyToAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**Comment by Eilon** [comment]
This magic number 50 sounds suspiciously like https://github.com/aspnet/Coherence-Signed/issues/268, not that I have any idea whether it's related at all.

**Comment by mikeharder** [comment]
@anpete: Are you using HTTP or HTTPS?  Can you share steps to reproduce this?  How often does it repro?

**Comment by anpete** [comment]
@mikeharder Looks like this is no longer repro'ing - after https://github.com/aspnet/MusicStore/commit/fb4fadb0b10301b09326b8a9f78b6f1893210cb3

Let me know if you still want to investigate.

**Comment by mikeharder** [comment]
It's by design that this exception is raised if a client disconnects before reading a full response, which is likely what was happening before your changes.

**Comment by gdoron** [comment]
@mikeharder  @Eilon 
If it is caused by client disconnection, the level shouldn't be error.
It pollutes our log with stuff that aren't really errors and no actions need to be taken.

Am I right?

**Comment by mikeharder** [comment]
@halter73, @cesarbs: What log level is used for client disconnects?  I think they should be `Information` or lower.

**Comment by benaadams** [comment]
Its an exception that's being thrown in "user code" e.g. the StaticFiles middleware, Kestrel doesn't know its not serious.

**Comment by mikeharder** [comment]
@benaadams: Then maybe StaticFilesMiddleware shouldn't throw an unhandled exception for client disconnects?

**Comment by Tratcher** [comment]
The request has definitely failed and the pipeline should abort. Most of this issue is about how much log noise is generated.

OperationCanceledException somewhat special because we know those are what we throw if the client disconnected. We could choose catch to log them differently, especially if we know the client has disconnected (e.g. HttpContext.RequestAborted.IsCancellationRequested).

**Comment by gdoron** [comment]
@Tratcher 
>  Most of this issue is about how much log noise is generated.

We have a video playing as a "background image" on our homepage. A LOT.

**Comment by benaadams** [comment]
Change the exception type? (e.g. OperationCanceledException->HttpDisconnectException) so it can be distinguished from an OperationCanceledException arising in user code?

**Comment by Tratcher** [comment]
No, you don't want to mess up the Stream/Task exception contract.

**Comment by benaadams** [comment]
Could still catch a derived exception with `catch (OperationCanceledException ex)` just allows for differentiation?

**Comment by halter73** [comment]
Agreed. I think StaticFiles should `catch (OperationCanceledException ex)` and check `HttpContext.RequestAborted.IsCancellationRequested`. If the `RequestAborted` token is canceled, log something about a client disconnect at an information or lower log level. Otherwise, rethrow.

**Comment by Tratcher** [comment]
We'd have to write that kind of code into every middleware and framework. That's a very expensive solution to an otherwise minor problem.

**Comment by halter73** [comment]
@Tratcher Only middleware that writes responses while passing in the RequestAborted token to WriteAsync/SendFile needs to change. What other than StaticFiles actually does that? I'm guessing there's not too many other examples. I've seen several complaints for StaticFiles throwing an uncaught `OperationCanceledException`, but never for anything else.

It's really not necessary to pass in the RequestAborted token when writing small or cached responses since the following written bytes will be quickly thrown away.

**Comment by muratg** [comment]
I asked @halter73 to file a bug on StaticFiles to continue the discussion there. We can reach the decision there later.

**Comment by halter73** [comment]
This issue was moved to aspnet/StaticFiles#150
