### ISSUE TITLE
Creating .NET Core empty web app called 'web' silently fails to launch in VS (it just hangs on launch)

### ISSUE THREAD

**Issue by BillHiebert** [aspnet/KestrelHttpServer#824]
Create a new Empty .NET Core Web app in VS
Call it "web"

Hit F5 (to launch under IIS Express)

Actual:
It fails to launch (spinning Edge icon waiting for it to load) - there are not even an IIS Express logs to debug the issue

What's happening is kestrel is throwing the following exception. It only repros with projects named "web" and when hosted in iisexpress.

Unhandled Exception: System.AggregateException: One or more errors occurred. (Error -4092 EACCES permission denied) ---> Microsoft.AspNetCore.Server.Kestrel.Networking.UvException: Error -4092 EACCES permission denied

at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
at Microsoft.AspNetCore.Server.Kestrel.Networking.UvTcpHandle.Bind(ServerAddress address)
at Microsoft.AspNetCore.Server.Kestrel.Http.TcpListenerPrimary.CreateListenSocket()
at Microsoft.AspNetCore.Server.Kestrel.Http.Listener.<>c.<StartAsync>b__6_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Server.Kestrel.Http.ListenerPrimary.<StartAsync>d__9.MoveNext()
--- End of inner exception stack trace ---

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.CreateServer(ServerAddress address)
at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
at web.Program.Main(String[] args)

**Comment by benaadams** [comment]
The error means the port Kestrel is trying to listen on already has something listening on it

**Comment by halter73** [comment]
@benaadams Agreed that that is the most likely explanation. @cesarbs Said he was able to repro and that he would debug it.

**Comment by cesarbs** [comment]
@benaadams I'm not sure. When you try to listen on a port that's already in use you normally get an `EADDRINUSE`.

**Comment by cesarbs** [comment]
Interesting find here. Look what happens to the address Kestrel tries to bind to when the project is named "web":

![image](https://cloud.githubusercontent.com/assets/924164/15300460/ad5fdd82-1b5d-11e6-8eea-a70e95dd7b02.png)

Compare to any other project:

![image](https://cloud.githubusercontent.com/assets/924164/15300511/efa9d738-1b5d-11e6-9545-2e7468084762.png)

Looks like the issue is coming from ANCM. cc @pan-wang

**Comment by cesarbs** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
Specifically, the ASPNETCORE_APPL_PATH is set to `ROOT/WEBHOST/WEB` for some reason. Is `WEB` a reserved site name in IIS/Express?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#176
