### ISSUE TITLE
Kestrel Connection processing ended abnormally

### ISSUE THREAD

**Issue by hmnzr** [aspnet/KestrelHttpServer#937]
Hi, 

I have a similar issue to https://github.com/aspnet/KestrelHttpServer/issues/915 when using Kestrel

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 50.5596ms 200 application/javascript
warn: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<!0> System.Threading.Tasks.ValueTask`1.op_Implicit(System.Threading.Tasks.Task`1<!0>)'.
   at Microsoft.AspNetCore.Server.Kestrel.Http.MessageBody.ForContentLength.ReadAsyncImplementation(ArraySegment`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Http.MessageBody.Consume(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**dotnet --info**
```
.NET Command Line Tools (1.0.0-preview2-003119)

Product Information:
 Version:            1.0.0-preview2-003119
 Commit SHA-1 hash:  0708fe095e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**project.json**

```
{
  "version": "0.0.1-*",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authorization": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.HttpOverrides": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-final",
    "Microsoft.Extensions.DependencyInjection": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "HelpDesk.Services": "1.0.0-*"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [ "UI", "Views", "wwwroot", "logs", "web.config", "config.*", "*.pfx" ]
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "scripts": {
    "prepublish": [ "npm install", "grunt buildDevelop" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

I also have a class library project with netcoreapp1.0 framework referenced by asp.net project

Suspicious, but library `Microsoft.AspNetCore.Server.Kestrel` within my project has version `1.0.0-rc2-final`, and sub-dependency `System.Threading.Task.Extensions` with `4.0.0` version.
New asp.net project has the same version of Kestrel, but  `System.Threading.Task.Extensions` has the `4.0.0-rc2-24027` version.
This is also true for some other sub-dependencies.

**Comment by halter73** [comment]
Make sure your referencing the `4.0.0-rc2-24027` version of `System.Threading.Task.Extensions` when depending on  the `1.0.0-rc2-final` version of `Microsoft.AspNetCore.Server.Kestrel`. Both these packages are on nuget.org.

It looks like there's a binary incompatibility between the `4.0.0-rc2-24027` and `4.0.0` versions of `System.Threading.Task.Extensions`. The `4.0.0` version should only be available on myget right now.

Since you're using rc2 packages, make sure you don't have any myget sources in your `NuGet.Config` files. Then [clear all you nuget package caches](http://stackoverflow.com/questions/30933277/how-to-clear-nuget-package-cache-using-command-line).

If that doesn't fix things, please include a link to a gist with your `project.lock.json`.

**Comment by benaadams** [comment]
@halter73 will current dev make it into RTM? (thinking specifically this PR https://github.com/aspnet/KestrelHttpServer/pull/889)

**Comment by moozzyk** [comment]
@benaadams - https://github.com/aspnet/KestrelHttpServer/commits/release is what's in release (PR#889 is included)

**Comment by hmnzr** [comment]
Thank you, I just cleared nuget cache, all works fine.

**Comment by halter73** [comment]
Glad to hear it!
