### ISSUE TITLE
ObjectDisposedException while shutting down

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/KestrelHttpServer#946]
I'm running the RTM bits and got the following stack trace after pressing CTRL+C on the `dotnet run` command line on Windows:

```
Unhandled Exception: System.ObjectDisposedException: The SafeHandle was closed.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.PostCloseHandle(Action`1 callback, IntPtr handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvHandle.ReleaseHandle()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```

By that time, Kestrel had seen two requests on localhost: One for `/` that sent a `context.Response.Redirect('/foo/')` and the one for `/foo/` that returned a 404.

I cannot reproduce this on subsequent runs.

**Comment by Tragetaschen** [comment]
It also happens just with the 404-request for `/foo/`

**Comment by Tragetaschen** [comment]
I think the problem is that Autofac as my DI container doesn't provide an `IServiceProvider` that implements `IDisposable`. That means the entire application stops by ways of the finalizer.

Isn't the `IServiceProvider` that's returned from `ConfigureServices` required to implement `IDisposable`?

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/DependencyInjection/issues/379

**Comment by muratg** [comment]
Dup of the DI issue linked above
