### ISSUE TITLE
"ObjectDisposedException: Safe handle has been closed" when running FunctionalTests on OSX

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#972]
The following exception was thrown once when running FunctionalTests on OSX.  No test failures were reported before the exception:

```
Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvAsyncHandle.Send()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.PostCloseHandle(Action`1 callback, IntPtr handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvHandle.ReleaseHandle()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```

**Comment by Tragetaschen** [comment]
That's the same stack trace as in #946. Do those tests properly dispose Kestrel?

**Comment by halter73** [comment]
@Tragetaschen The tests do dispose `KestrelServer`. It's somewhat harder to mess that up in the functional tests where we pretty much always use `using (WebHostBuilder.Build())`. The error happens fairly infrequently, and looks like it could be due to some sort of shutdown race.
