### ISSUE TITLE
Published ASP.NET Core app doesn't work on IIS

### ISSUE THREAD

**Issue by szelpe** [aspnet/KestrelHttpServer#984]
My ASP.NET Core web application works fine when I use it with `dotnet run`, but after publishing the website using Visual Studio and set up IIS to host the published artifact it only shows blank screen, returning 500 internal server error. Running `dotnet run` on the published artifact still works fine, the error only occurs if I try to run under IIS. I've followed the docs: https://docs.asp.net/en/latest/publishing/iis.html

I'd appreciate any help.

Here is the error log collected by turning on `stdoutLogEnabled`:

```
Hosting environment: Production
Content root path: D:\ProjectsRoot\NextRcIssues\NextRcIssues\bin\Release\PublishOutput
Now listening on: http://localhost:10874
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Request starting HTTP/1.1 GET http://localhost:6300/ 
fail: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HKTCKACFV25H": An unhandled exception was thrown by the application.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: offset
at Microsoft.Extensions.Primitives.StringSegment..ctor(String buffer, Int32 offset, Int32 length)
at Microsoft.AspNetCore.Http.Internal.HeaderSegmentCollection.Enumerator.get_Current()
at Microsoft.AspNetCore.Http.Internal.ParsingHelpers.<GetHeaderSplitImplementation>d__2.MoveNext()
at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at Microsoft.AspNetCore.Http.Internal.ParsingHelpers.GetHeaderSplit(IHeaderDictionary headers, String key)
at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.ApplyForwarders(HttpContext context)
at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**Comment by davidfowl** [comment]
Looks like an issue with the header parsing (nothing to do with Kestrel BTW). Can you turn on connection logging? That might show the request data https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/Startup.cs#L42

**Comment by szelpe** [comment]
Thanks David, I wasn't sure if it's Kestrel related or not.

After turning on connection logging I have the following:

```
Hosting environment: Production
Content root path: D:\ProjectsRoot\NextRcIssues\NextRcIssues\bin\Debug\PublishOutput
Now listening on: http://localhost:31049
Application started. Press Ctrl+C to shut down.
dbug: LoggingConnectionFilter[0]
      ReadAsync[904] 47 45 54 20 2F 20 48 54 54 50 2F 31 2E 31 0D 0A 43 61 63 68 65 2D 43 6F 6E 74 72 6F 6C 3A 20 6D 61 78 2D 61 67 65 3D 30 0D 0A 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 4B 65 65 70 2D 41 6C 69 76 65 0D 0A 41 63 63 65 70 74 3A 20 74 65 78 74 2F 68 74 6D 6C 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 78 68 74 6D 6C 2B 78 6D 6C 2C 61 70 70 6C 69 63 61 74 69 6F 6E 2F 78 6D 6C 3B 71 3D 30 2E 39 2C 69 6D 61 67 65 2F 77 65 62 70 2C 2A 2F 2A 3B 71 3D 30 2E 38 0D 0A 41 63 63 65 70 74 2D 45 6E 63 6F 64 69 6E 67 3A 20 67 7A 69 70 2C 20 64 65 66 6C 61 74 65 2C 20 73 64 63 68 0D 0A 41 63 63 65 70 74 2D 4C 61 6E 67 75 61 67 65 3A 20 65 6E 2D 55 53 2C 65 6E 3B 71 3D 30 2E 38 2C 68 75 3B 71 3D 30 2E 36 0D 0A 43 6F 6F 6B 69 65 3A 20 2E 41 53 50 58 41 55 54 48 3D 30 39 44 45 44 41 37 31 38 35 46 42 43 43 30 42 44 34 41 36 38 46 42 39 30 31 45 33 35 30 38 34 38 35 33 36 32 43 30 32 44 43 32 36 32 31 42 44 38 46 34 37 39 42 38 37 36 44 35 33 43 43 34 43 30 31 38 46 38 31 42 42 35 43 45 35 32 41 42 32 43 46 42 38 31 35 38 36 38 45 43 44 31 35 39 32 43 30 38 36 35 37 43 46 39 35 34 42 45 34 34 42 38 33 39 44 43 37 33 33 34 39 36 31 42 35 45 42 33 42 43 37 31 30 32 36 35 38 36 44 46 32 45 37 43 41 44 34 31 46 37 45 37 44 46 30 32 30 34 30 42 30 34 42 34 46 43 45 30 42 38 34 37 31 44 35 30 34 30 33 32 43 42 38 43 34 32 39 33 35 46 45 41 37 34 30 38 38 32 39 41 41 44 45 45 36 44 41 44 35 32 35 35 34 43 45 30 44 32 46 31 41 46 46 30 33 34 39 38 35 41 37 33 41 34 36 43 44 31 43 46 38 34 43 41 33 35 33 44 37 42 45 34 38 30 34 36 38 46 34 30 41 45 45 36 33 38 33 30 45 31 39 45 42 35 38 46 32 31 32 46 35 31 30 43 43 44 46 3B 20 4A 53 45 53 53 49 4F 4E 49 44 3D 33 44 39 43 33 46 31 38 38 31 44 38 33 41 38 39 34 38 44 37 36 36 46 46 36 37 35 43 37 42 34 32 0D 0A 48 6F 73 74 3A 20 6C 6F 63 61 6C 68 6F 73 74 3A 36 33 30 30 0D 0A 55 73 65 72 2D 41 67 65 6E 74 3A 20 4D 6F 7A 69 6C 6C 61 2F 35 2E 30 20 28 57 69 6E 64 6F 77 73 20 4E 54 20 36 2E 33 3B 20 57 4F 57 36 34 29 20 41 70 70 6C 65 57 65 62 4B 69 74 2F 35 33 37 2E 33 36 20 28 4B 48 54 4D 4C 2C 20 6C 69 6B 65 20 47 65 63 6B 6F 29 20 43 68 72 6F 6D 65 2F 35 31 2E 30 2E 32 37 30 34 2E 31 30 33 20 53 61 66 61 72 69 2F 35 33 37 2E 33 36 0D 0A 55 70 67 72 61 64 65 2D 49 6E 73 65 63 75 72 65 2D 52 65 71 75 65 73 74 73 3A 20 31 0D 0A 58 2D 4F 72 69 67 69 6E 61 6C 2D 46 6F 72 77 61 72 64 65 64 2D 46 6F 72 3A 20 0D 0A 58 2D 46 6F 72 77 61 72 64 65 64 2D 46 6F 72 3A 20 2C 20 5B 3A 3A 31 5D 3A 33 32 37 38 31 0D 0A 4D 53 2D 41 53 50 4E 45 54 43 4F 52 45 2D 54 4F 4B 45 4E 3A 20 61 34 66 39 65 66 36 34 2D 33 64 36 37 2D 34 66 39 64 2D 39 30 66 65 2D 36 38 64 35 32 66 63 63 63 65 66 33 0D 0A 58 2D 46 6F 72 77 61 72 64 65 64 2D 50 72 6F 74 6F 3A 20 68 74 74 70 0D 0A 0D 0A 
      GET / HTTP/1.1
      Cache-Control: max-age=0
      Connection: Keep-Alive
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
      Accept-Encoding: gzip, deflate, sdch
      Accept-Language: en-US,en;q=0.8,hu;q=0.6
      Cookie: .ASPXAUTH=09DEDA7185FBCC0BD4A68FB901E3508485362C02DC2621BD8F479B876D53CC4C018F81BB5CE52AB2CFB815868ECD1592C08657CF954BE44B839DC7334961B5EB3BC71026586DF2E7CAD41F7E7DF02040B04B4FCE0B8471D504032CB8C42935FEA7408829AADEE6DAD52554CE0D2F1AFF034985A73A46CD1CF84CA353D7BE480468F40AEE63830E19EB58F212F510CCDF; JSESSIONID=3D9C3F1881D83A8948D766FF675C7B42
      Host: localhost:6300
      User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
      Upgrade-Insecure-Requests: 1
      X-Original-Forwarded-For: 
      X-Forwarded-For: , [::1]:32781
      MS-ASPNETCORE-TOKEN: a4f9ef64-3d67-4f9d-90fe-68d52fcccef3
      X-Forwarded-Proto: http
      
      
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:6300/  
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKTES6OS14JP": An unhandled exception was thrown by the application.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: offset
   at Microsoft.Extensions.Primitives.StringSegment..ctor(String buffer, Int32 offset, Int32 length)
   at Microsoft.AspNetCore.Http.Internal.HeaderSegmentCollection.Enumerator.get_Current()
   at Microsoft.AspNetCore.Http.Internal.ParsingHelpers.<GetHeaderSplitImplementation>d__2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Http.Internal.ParsingHelpers.GetHeaderSplit(IHeaderDictionary headers, String key)
   at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.ApplyForwarders(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 108.2118ms 200 
dbug: LoggingConnectionFilter[0]
      Write[111] 48 54 54 50 2F 31 2E 31 20 35 30 30 20 49 6E 74 65 72 6E 61 6C 20 53 65 72 76 65 72 20 45 72 72 6F 72 0D 0A 44 61 74 65 3A 20 4D 6F 6E 2C 20 31 38 20 4A 75 6C 20 32 30 31 36 20 30 38 3A 30 31 3A 31 36 20 47 4D 54 0D 0A 43 6F 6E 74 65 6E 74 2D 4C 65 6E 67 74 68 3A 20 30 0D 0A 53 65 72 76 65 72 3A 20 4B 65 73 74 72 65 6C 0D 0A 0D 0A 
      HTTP/1.1 500 Internal Server Error
      Date: Mon, 18 Jul 2016 08:01:16 GMT
      Content-Length: 0
      Server: Kestrel
      
      
dbug: LoggingConnectionFilter[0]
      WriteAsync[0] 
```

I assume the problem is with either `X-Forwarded-For` or `X-Original-Forwarded-For` header.

**Comment by davidfowl** [comment]
Closing this out
