### ISSUE TITLE
[win:net461]Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation

### ISSUE THREAD

**Issue by Rurouni** [aspnet/KestrelHttpServer#992]
Hello, 
After upgrading to RTM asp.core packages I am having following exception on startup:
```
System.BadImageFormatException occurred
  FileName=System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  FusionLog=""
  HResult=-2146234280
  Message=Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
  Source=Microsoft.AspNetCore.Server.Kestrel
  StackTrace:
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.Constants.GetECONNRESET()
       at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.Constants..cctor()
  InnerException: 
       HResult=-2146234280
       Message=Cannot load a reference assembly for execution.
       InnerException: 
```
I am running Kestrel within ServiceFabric and project type is normal csproj+project.json with:
```
{
    "version": "1.0.0-*",
    "dependencies": {
        "Autofac.Extensions.DependencyInjection": "4.0.0-rc2-240",
        "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
        "Microsoft.AspNetCore.Cors": "1.0.0",
        "Microsoft.AspNetCore.Diagnostics": "1.0.0",
        "Microsoft.AspNetCore.Identity": "1.0.0",
        "Microsoft.AspNetCore.Mvc.Core": "1.0.0",
        "Microsoft.AspNetCore.Mvc.Formatters.Json": "1.0.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "Serilog.Exceptions": "2.0.0",
        "Serilog.Extensions.Logging": "1.0.0",
        "Serilog.Sinks.Elasticsearch": "4.0.142",
        "System.IdentityModel.Tokens.Jwt": "5.0.0"
    },

    "frameworks": {
        "net461": {}
    },

    "runtimes": {
        "win-x64": {}
    }
}
```
It feels like it's some mixup with packages with csproj+project.json setup and win-x64 target
because if I manually override System.Runtime.InteropServices.RuntimeInformation.dll from runtime section of nuget package it works... so I have a workaround atm, but would be nice to understand why it doesn't work out of the box

**Comment by davidfowl** [comment]
The answer is pretty complicated but it has to do with the chosen runtime and the fact that there's gaps with the current csproj + project.json experience. To make it work correctly try this RID instead:

https://github.com/davidfowl/AspNetCoreCsproj/blob/master/MyWebApplication/project.json#L9

and add this to your csproj

https://github.com/davidfowl/AspNetCoreCsproj/blob/master/MyWebApplication/MyWebApplication.csproj#L14-L16

**Comment by Rurouni** [comment]
Hi David,
I have tried that fix with caveat that it should it be <BaseNuGetRuntimeIdentifier>win7</BaseNuGetRuntimeIdentifier>  eitherwise it comes with error that you should have win7-x64-x64 in project.json.
But whilst it copies libuv.dll correctly, for some reason System.Runtime.InteropServices.RuntimeInformation.dll is still reference one
In any case I am happy with such fix for now
```
    <Content Include="..\packages\Libuv\1.9.0\runtimes\win7-x64\native\*" Condition="'$(Platform)' == 'x64'">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>True</Visible>
    </Content>
    <Content Include="..\packages\System.Runtime.InteropServices.RuntimeInformation\4.0.0\runtimes\win\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll" Condition="'$(Platform)' == 'x64'">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>True</Visible>
    </Content>
```
so i am closing this as it's not really a kestrel bug
