### ISSUE TITLE
Unable to debug asp.net core 1 app  

### ISSUE THREAD

**Issue by caste1969** [aspnet/KestrelHttpServer#995]
Hi all, I have a problem with all app that I create using asp.net.core 1.
VS2015 build app, and then we start debug (also try  from cmd) it stop with this error:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime. (D:\swdev\Valassis\Promohub\Valassis.Coupon.Web\bin\Release\PublishOutput\demo.exe.Config line 3)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Net.Configuration.SettingsSectionInternal.get_Section()
   at System.Net.Sockets.Socket.InitializeSockets()
   at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvTcpHandle.CreateIPEndpoint(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Http.Listener.<>c.<StartAsync>b__6_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Http.ListenerPrimary.<StartAsync>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Valassis.Coupon.Web.Program.Main(String[] args) in..
```
Have any idea?
Thank you
caste1969

**Comment by davidfowl** [comment]
The error is pretty specific. What's in your config file on line 3:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime. (D:\swdev\Valassis\Promohub\Valassis.Coupon.Web\bin\Release\PublishOutput\demo.exe.Config line 3)
```

**Comment by caste1969** [comment]
Hi, I send in attachment a simple project that have this problem.
File that have problem is the same for all project and is the .exe..config that VS create after build:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="1.1.37.0" newVersion="1.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reflection.Metadata" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="1.2.0.0" newVersion="1.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="6.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
At line 3 there is section runtime.
Thanks
[pippo3.zip](https://github.com/aspnet/KestrelHttpServer/files/372931/pippo3.zip)

**Comment by halter73** [comment]
pippo3.zip works fine on my machine. I think this is an issue with your installation of .NET. This isn't unheard of according to [this SO post](http://stackoverflow.com/a/402639/719967). Maybe you can try reinstalling from an [official source](https://www.microsoft.com/en-us/download/details.aspx?id=48130).

**Comment by caste1969** [comment]
I think too was an issue with my installation of .Net, but I don't understand why it was happened. After two days of installing/uninstalling VS, ..Net, with any result, I rebuild my machine completely. Now works all..
Many thanks..
